read_lib techlib/mod_nangate45.mdt
read_netlist mod_netlist/b08.v
set_nonscan_ff _870_ _871_ _872_ _873_ _874_ _875_ _876_
set_nine_valued_logic on
build_circuit --frame 1
set_fault_type saf
add_fault --all
set_per_target_timeout 5.0
set_static_compression off
set_dynamic_compression off
run_atpg
report_statistics > /home/yenchulo/ScanForge/FAN_ATPG/rpt_verify/b08_x10_t1_all.rpt
report_fault > /home/yenchulo/ScanForge/FAN_ATPG/rpt_verify/b08_x10_t1_all_faults.txt
exit
