/* Generated by Yosys 0.65 (git sha1 9d0cdb855, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module b03(CK, request1, request2, request3, request4, grant_o_0_, grant_o_1_, grant_o_2_, grant_o_3_, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  input CK;
  wire CK;
    wire reset;
  input request1;
  wire request1;
  input request2;
  wire request2;
  input request3;
  wire request3;
  input request4;
  wire request4;
    output grant_o_0_;
  output grant_o_1_;
  output grant_o_2_;
  output grant_o_3_;
    wire grant_o_0_;
  wire grant_o_1_;
  wire grant_o_2_;
  wire grant_o_3_;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire coda0_0_;
  wire coda0_1_;
  wire coda0_2_;
  wire coda1_0_;
  wire coda1_1_;
  wire coda1_2_;
  wire coda2_0_;
  wire coda2_1_;
  wire coda2_2_;
  wire coda3_0_;
  wire coda3_1_;
  wire coda3_2_;
  wire fu1;
  wire fu2;
  wire fu3;
  wire fu4;
  wire grant_0_;
  wire grant_1_;
  wire grant_2_;
  wire grant_3_;
  wire ru1;
  wire ru2;
  wire ru3;
  wire ru4;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  INV_X1 _134_ (
    .A(ru1),
    .ZN(_102_)
  );
  INV_X1 _135_ (
    .A(stato_2_),
    .ZN(_103_)
  );
  INV_X1 _136_ (
    .A(coda2_2_),
    .ZN(_061_)
  );
  INV_X1 _137_ (
    .A(fu4),
    .ZN(_062_)
  );
  INV_X1 _138_ (
    .A(ru3),
    .ZN(_063_)
  );
  INV_X1 _139_ (
    .A(coda1_2_),
    .ZN(_064_)
  );
  INV_X1 _140_ (
    .A(coda2_1_),
    .ZN(_065_)
  );
  INV_X1 _141_ (
    .A(ru2),
    .ZN(_066_)
  );
  INV_X1 _142_ (
    .A(coda0_2_),
    .ZN(_067_)
  );
  INV_X1 _143_ (
    .A(coda0_0_),
    .ZN(_068_)
  );
  INV_X1 _144_ (
    .A(coda2_0_),
    .ZN(_069_)
  );
  INV_X1 _145_ (
    .A(reset),
    .ZN(_002_)
  );
  OR3_X1 _146_ (
    .A1(fu4),
    .A2(fu3),
    .A3(fu2),
    .ZN(_070_)
  );
  OAI21_X1 _147_ (
    .A(stato_1_),
    .B1(_070_),
    .B2(fu1),
    .ZN(_071_)
  );
  NOR3_X1 _148_ (
    .A1(_067_),
    .A2(coda0_0_),
    .A3(coda0_1_),
    .ZN(_072_)
  );
  MUX2_X1 _149_ (
    .A(_072_),
    .B(grant_3_),
    .S(_071_),
    .Z(_060_)
  );
  NOR2_X1 _150_ (
    .A1(stato_1_),
    .A2(stato_0_),
    .ZN(_073_)
  );
  INV_X1 _151_ (
    .A(_073_),
    .ZN(_000_)
  );
  MUX2_X1 _152_ (
    .A(request1),
    .B(ru1),
    .S(_073_),
    .Z(_059_)
  );
  MUX2_X1 _153_ (
    .A(request4),
    .B(ru4),
    .S(_073_),
    .Z(_058_)
  );
  MUX2_X1 _154_ (
    .A(fu1),
    .B(ru1),
    .S(stato_2_),
    .Z(_057_)
  );
  OAI21_X1 _155_ (
    .A(_071_),
    .B1(stato_1_),
    .B2(_103_),
    .ZN(_074_)
  );
  NOR3_X1 _156_ (
    .A1(_063_),
    .A2(ru2),
    .A3(_001_),
    .ZN(_075_)
  );
  AOI211_X1 _157_ (
    .A(ru3),
    .B(ru2),
    .C1(ru4),
    .C2(_062_),
    .ZN(_076_)
  );
  AND2_X1 _158_ (
    .A1(ru2),
    .A2(fu2),
    .ZN(_077_)
  );
  NOR4_X1 _159_ (
    .A1(ru1),
    .A2(_075_),
    .A3(_076_),
    .A4(_077_),
    .ZN(_078_)
  );
  OAI21_X1 _160_ (
    .A(stato_2_),
    .B1(fu1),
    .B2(_102_),
    .ZN(_079_)
  );
  OAI21_X1 _161_ (
    .A(_074_),
    .B1(_078_),
    .B2(_079_),
    .ZN(_080_)
  );
  MUX2_X1 _162_ (
    .A(coda1_2_),
    .B(coda3_2_),
    .S(stato_1_),
    .Z(_081_)
  );
  MUX2_X1 _163_ (
    .A(_081_),
    .B(coda2_2_),
    .S(_080_),
    .Z(_056_)
  );
  NOR2_X1 _164_ (
    .A1(_065_),
    .A2(stato_1_),
    .ZN(_082_)
  );
  MUX2_X1 _165_ (
    .A(_082_),
    .B(coda3_1_),
    .S(_080_),
    .Z(_055_)
  );
  MUX2_X1 _166_ (
    .A(fu4),
    .B(ru4),
    .S(stato_2_),
    .Z(_054_)
  );
  MUX2_X1 _167_ (
    .A(fu3),
    .B(ru3),
    .S(stato_2_),
    .Z(_053_)
  );
  MUX2_X1 _168_ (
    .A(coda0_2_),
    .B(coda2_2_),
    .S(stato_1_),
    .Z(_083_)
  );
  MUX2_X1 _169_ (
    .A(_083_),
    .B(coda1_2_),
    .S(_080_),
    .Z(_052_)
  );
  MUX2_X1 _170_ (
    .A(request3),
    .B(ru3),
    .S(_073_),
    .Z(_051_)
  );
  MUX2_X1 _171_ (
    .A(grant_o_3_),
    .B(grant_3_),
    .S(stato_2_),
    .Z(_050_)
  );
  NOR2_X1 _172_ (
    .A1(_061_),
    .A2(stato_1_),
    .ZN(_084_)
  );
  MUX2_X1 _173_ (
    .A(_084_),
    .B(coda3_2_),
    .S(_080_),
    .Z(_049_)
  );
  MUX2_X1 _174_ (
    .A(coda1_1_),
    .B(coda3_1_),
    .S(stato_1_),
    .Z(_085_)
  );
  MUX2_X1 _175_ (
    .A(_085_),
    .B(coda2_1_),
    .S(_080_),
    .Z(_048_)
  );
  MUX2_X1 _176_ (
    .A(coda0_0_),
    .B(coda2_0_),
    .S(stato_1_),
    .Z(_086_)
  );
  MUX2_X1 _177_ (
    .A(_086_),
    .B(coda1_0_),
    .S(_080_),
    .Z(_047_)
  );
  MUX2_X1 _178_ (
    .A(coda0_1_),
    .B(coda2_1_),
    .S(stato_1_),
    .Z(_087_)
  );
  MUX2_X1 _179_ (
    .A(_087_),
    .B(coda1_1_),
    .S(_080_),
    .Z(_046_)
  );
  NAND3_X1 _180_ (
    .A1(coda0_2_),
    .A2(coda0_0_),
    .A3(coda0_1_),
    .ZN(_088_)
  );
  NAND2_X1 _181_ (
    .A1(grant_0_),
    .A2(_071_),
    .ZN(_089_)
  );
  OAI21_X1 _182_ (
    .A(_089_),
    .B1(_088_),
    .B2(_071_),
    .ZN(_045_)
  );
  NOR3_X1 _183_ (
    .A1(coda0_2_),
    .A2(_068_),
    .A3(coda0_1_),
    .ZN(_090_)
  );
  MUX2_X1 _184_ (
    .A(_090_),
    .B(grant_1_),
    .S(_071_),
    .Z(_044_)
  );
  MUX2_X1 _185_ (
    .A(request2),
    .B(ru2),
    .S(_073_),
    .Z(_043_)
  );
  MUX2_X1 _186_ (
    .A(grant_o_0_),
    .B(grant_0_),
    .S(stato_2_),
    .Z(_042_)
  );
  MUX2_X1 _187_ (
    .A(grant_o_1_),
    .B(grant_1_),
    .S(stato_2_),
    .Z(_041_)
  );
  MUX2_X1 _188_ (
    .A(fu2),
    .B(ru2),
    .S(stato_2_),
    .Z(_040_)
  );
  MUX2_X1 _189_ (
    .A(grant_o_2_),
    .B(grant_2_),
    .S(stato_2_),
    .Z(_039_)
  );
  AOI211_X1 _190_ (
    .A(ru1),
    .B(stato_1_),
    .C1(_066_),
    .C2(_063_),
    .ZN(_091_)
  );
  AOI21_X1 _191_ (
    .A(_091_),
    .B1(stato_1_),
    .B2(_064_),
    .ZN(_092_)
  );
  MUX2_X1 _192_ (
    .A(_092_),
    .B(coda0_2_),
    .S(_080_),
    .Z(_038_)
  );
  NOR3_X1 _193_ (
    .A1(ru1),
    .A2(ru2),
    .A3(stato_1_),
    .ZN(_093_)
  );
  AOI21_X1 _194_ (
    .A(_093_),
    .B1(stato_1_),
    .B2(coda1_0_),
    .ZN(_094_)
  );
  INV_X1 _195_ (
    .A(_094_),
    .ZN(_095_)
  );
  MUX2_X1 _196_ (
    .A(_095_),
    .B(coda0_0_),
    .S(_080_),
    .Z(_037_)
  );
  AOI211_X1 _197_ (
    .A(ru1),
    .B(stato_1_),
    .C1(_066_),
    .C2(ru3),
    .ZN(_096_)
  );
  AOI21_X1 _198_ (
    .A(_096_),
    .B1(stato_1_),
    .B2(coda1_1_),
    .ZN(_097_)
  );
  INV_X1 _199_ (
    .A(_097_),
    .ZN(_098_)
  );
  MUX2_X1 _200_ (
    .A(_098_),
    .B(coda0_1_),
    .S(_080_),
    .Z(_036_)
  );
  AND3_X1 _201_ (
    .A1(_067_),
    .A2(_068_),
    .A3(coda0_1_),
    .ZN(_099_)
  );
  MUX2_X1 _202_ (
    .A(_099_),
    .B(grant_2_),
    .S(_071_),
    .Z(_035_)
  );
  MUX2_X1 _203_ (
    .A(coda1_0_),
    .B(coda3_0_),
    .S(stato_1_),
    .Z(_100_)
  );
  MUX2_X1 _204_ (
    .A(_100_),
    .B(coda2_0_),
    .S(_080_),
    .Z(_034_)
  );
  NOR2_X1 _205_ (
    .A1(_069_),
    .A2(stato_1_),
    .ZN(_101_)
  );
  MUX2_X1 _206_ (
    .A(_101_),
    .B(coda3_0_),
    .S(_080_),
    .Z(_033_)
  );
  INV_X1 _207_ (
    .A(reset),
    .ZN(_003_)
  );
  INV_X1 _208_ (
    .A(reset),
    .ZN(_004_)
  );
  INV_X1 _209_ (
    .A(reset),
    .ZN(_005_)
  );
  INV_X1 _210_ (
    .A(reset),
    .ZN(_006_)
  );
  INV_X1 _211_ (
    .A(reset),
    .ZN(_007_)
  );
  INV_X1 _212_ (
    .A(reset),
    .ZN(_008_)
  );
  INV_X1 _213_ (
    .A(reset),
    .ZN(_009_)
  );
  INV_X1 _214_ (
    .A(reset),
    .ZN(_010_)
  );
  INV_X1 _215_ (
    .A(reset),
    .ZN(_011_)
  );
  INV_X1 _216_ (
    .A(reset),
    .ZN(_012_)
  );
  INV_X1 _217_ (
    .A(reset),
    .ZN(_013_)
  );
  INV_X1 _218_ (
    .A(reset),
    .ZN(_014_)
  );
  INV_X1 _219_ (
    .A(reset),
    .ZN(_015_)
  );
  INV_X1 _220_ (
    .A(reset),
    .ZN(_016_)
  );
  INV_X1 _221_ (
    .A(reset),
    .ZN(_017_)
  );
  INV_X1 _222_ (
    .A(reset),
    .ZN(_018_)
  );
  INV_X1 _223_ (
    .A(reset),
    .ZN(_019_)
  );
  INV_X1 _224_ (
    .A(reset),
    .ZN(_020_)
  );
  INV_X1 _225_ (
    .A(reset),
    .ZN(_021_)
  );
  INV_X1 _226_ (
    .A(reset),
    .ZN(_022_)
  );
  INV_X1 _227_ (
    .A(reset),
    .ZN(_023_)
  );
  INV_X1 _228_ (
    .A(reset),
    .ZN(_024_)
  );
  INV_X1 _229_ (
    .A(reset),
    .ZN(_025_)
  );
  INV_X1 _230_ (
    .A(reset),
    .ZN(_026_)
  );
  INV_X1 _231_ (
    .A(reset),
    .ZN(_027_)
  );
  INV_X1 _232_ (
    .A(reset),
    .ZN(_028_)
  );
  INV_X1 _233_ (
    .A(reset),
    .ZN(_029_)
  );
  INV_X1 _234_ (
    .A(reset),
    .ZN(_030_)
  );
  INV_X1 _235_ (
    .A(reset),
    .ZN(_031_)
  );
  INV_X1 _236_ (
    .A(reset),
    .ZN(_032_)
  );
  SDFFR_X1 _237_ (
    .CK(CK),
    .D(_040_),
    .Q(fu2),
    .RN(_011_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _238_ (
    .CK(CK),
    .D(_042_),
    .Q(grant_o_0_),
    .RN(_013_),
    .SE(test_se),
    .SI(fu2)
  );
  SDFFR_X1 _239_ (
    .CK(CK),
    .D(_041_),
    .Q(grant_o_1_),
    .RN(_012_),
    .SE(test_se),
    .SI(grant_o_0_)
  );
  SDFFR_X1 _240_ (
    .CK(CK),
    .D(_039_),
    .Q(grant_o_2_),
    .RN(_010_),
    .SE(test_se),
    .SI(grant_o_1_)
  );
  SDFFR_X1 _241_ (
    .CK(CK),
    .D(_050_),
    .Q(grant_o_3_),
    .RN(_022_),
    .SE(test_se),
    .SI(grant_o_2_)
  );
  SDFFR_X1 _242_ (
    .CK(CK),
    .D(_043_),
    .Q(ru2),
    .RN(_014_),
    .SE(test_se),
    .SI(grant_o_3_)
  );
  SDFFR_X1 _243_ (
    .CK(CK),
    .D(_051_),
    .Q(ru3),
    .RN(_023_),
    .SE(test_se),
    .SI(ru2)
  );
  SDFFR_X1 _244_ (
    .CK(CK),
    .D(_037_),
    .Q(coda0_0_),
    .RN(_008_),
    .SE(test_se),
    .SI(ru3)
  );
  SDFFR_X1 _245_ (
    .CK(CK),
    .D(_036_),
    .Q(coda0_1_),
    .RN(_007_),
    .SE(test_se),
    .SI(coda0_0_)
  );
  SDFFR_X1 _246_ (
    .CK(CK),
    .D(_038_),
    .Q(coda0_2_),
    .RN(_009_),
    .SE(test_se),
    .SI(coda0_1_)
  );
  SDFFR_X1 _247_ (
    .CK(CK),
    .D(_033_),
    .Q(coda3_0_),
    .RN(_002_),
    .SE(test_se),
    .SI(coda0_2_)
  );
  SDFFR_X1 _248_ (
    .CK(CK),
    .D(_055_),
    .Q(coda3_1_),
    .RN(_027_),
    .SE(test_se),
    .SI(coda3_0_)
  );
  SDFFR_X1 _249_ (
    .CK(CK),
    .D(_049_),
    .Q(coda3_2_),
    .RN(_020_),
    .SE(test_se),
    .SI(coda3_1_)
  );
  SDFFR_X1 _250_ (
    .CK(CK),
    .D(_047_),
    .Q(coda1_0_),
    .RN(_018_),
    .SE(test_se),
    .SI(coda3_2_)
  );
  SDFFR_X1 _251_ (
    .CK(CK),
    .D(_046_),
    .Q(coda1_1_),
    .RN(_017_),
    .SE(test_se),
    .SI(coda1_0_)
  );
  SDFFR_X1 _252_ (
    .CK(CK),
    .D(_052_),
    .Q(coda1_2_),
    .RN(_024_),
    .SE(test_se),
    .SI(coda1_1_)
  );
  SDFFR_X1 _253_ (
    .CK(CK),
    .D(_053_),
    .Q(fu3),
    .QN(_001_),
    .RN(_025_),
    .SE(test_se),
    .SI(coda1_2_)
  );
  SDFFR_X1 _254_ (
    .CK(CK),
    .D(_054_),
    .Q(fu4),
    .RN(_026_),
    .SE(test_se),
    .SI(fu3)
  );
  SDFFR_X1 _255_ (
    .CK(CK),
    .D(_034_),
    .Q(coda2_0_),
    .RN(_003_),
    .SE(test_se),
    .SI(fu4)
  );
  SDFFR_X1 _256_ (
    .CK(CK),
    .D(_048_),
    .Q(coda2_1_),
    .RN(_019_),
    .SE(test_se),
    .SI(coda2_0_)
  );
  SDFFR_X1 _257_ (
    .CK(CK),
    .D(_056_),
    .Q(coda2_2_),
    .RN(_028_),
    .SE(test_se),
    .SI(coda2_1_)
  );
  SDFFR_X1 _258_ (
    .CK(CK),
    .D(_057_),
    .Q(fu1),
    .RN(_029_),
    .SE(test_se),
    .SI(coda2_2_)
  );
  SDFFR_X1 _259_ (
    .CK(CK),
    .D(_058_),
    .Q(ru4),
    .RN(_030_),
    .SE(test_se),
    .SI(fu1)
  );
  SDFFR_X1 _260_ (
    .CK(CK),
    .D(_059_),
    .Q(ru1),
    .RN(_031_),
    .SE(test_se),
    .SI(ru4)
  );
  SDFFR_X1 _261_ (
    .CK(CK),
    .D(_045_),
    .Q(grant_0_),
    .RN(_016_),
    .SE(test_se),
    .SI(ru1)
  );
  SDFFR_X1 _262_ (
    .CK(CK),
    .D(_044_),
    .Q(grant_1_),
    .RN(_015_),
    .SE(test_se),
    .SI(grant_0_)
  );
  SDFFR_X1 _263_ (
    .CK(CK),
    .D(_035_),
    .Q(grant_2_),
    .RN(_006_),
    .SE(test_se),
    .SI(grant_1_)
  );
  SDFFR_X1 _264_ (
    .CK(CK),
    .D(_060_),
    .Q(grant_3_),
    .RN(_032_),
    .SE(test_se),
    .SI(grant_2_)
  );
  SDFFS_X1 _265_ (
    .CK(CK),
    .D(_const0_),
    .Q(stato_0_),
    .SN(_005_),
    .SE(test_se),
    .SI(grant_3_)
  );
  SDFFR_X1 _266_ (
    .CK(CK),
    .D(stato_2_),
    .Q(stato_1_),
    .RN(_004_),
    .SE(test_se),
    .SI(stato_0_)
  );
  SDFFR_X1 _267_ (
    .CK(CK),
    .D(_000_),
    .Q(stato_2_),
    .RN(_021_),
    .SE(test_se),
    .SI(stato_1_)
  );

  LOGIC1_X1 _tie_reset (.Z(reset));
  LOGIC0_X1 _tie__const0_ (.Z(_const0_));
  wire _const0_;
  assign test_so = stato_2_;
endmodule