/* Generated by Yosys 0.38 (git sha1 543faed9c, gcc 11.4.0-1ubuntu1~22.04.3 -fPIC -Os) */

module b04(RESTART, AVERAGE, ENABLE, DATA_IN_0_, DATA_IN_1_, DATA_IN_2_, DATA_IN_3_, DATA_IN_4_, DATA_IN_5_, DATA_IN_6_, DATA_IN_7_, DATA_OUT_0_, DATA_OUT_1_, DATA_OUT_2_, DATA_OUT_3_, DATA_OUT_4_, DATA_OUT_5_, DATA_OUT_6_, DATA_OUT_7_, RESET, CK, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  input AVERAGE;
  wire AVERAGE;
  input CK;
  wire CK;
    input DATA_IN_0_;
  input DATA_IN_1_;
  input DATA_IN_2_;
  input DATA_IN_3_;
  input DATA_IN_4_;
  input DATA_IN_5_;
  input DATA_IN_6_;
  input DATA_IN_7_;
    wire DATA_IN_0_;
  wire DATA_IN_1_;
  wire DATA_IN_2_;
  wire DATA_IN_3_;
  wire DATA_IN_4_;
  wire DATA_IN_5_;
  wire DATA_IN_6_;
  wire DATA_IN_7_;
    output DATA_OUT_0_;
  output DATA_OUT_1_;
  output DATA_OUT_2_;
  output DATA_OUT_3_;
  output DATA_OUT_4_;
  output DATA_OUT_5_;
  output DATA_OUT_6_;
  output DATA_OUT_7_;
    wire DATA_OUT_0_;
  wire DATA_OUT_1_;
  wire DATA_OUT_2_;
  wire DATA_OUT_3_;
  wire DATA_OUT_4_;
  wire DATA_OUT_5_;
  wire DATA_OUT_6_;
  wire DATA_OUT_7_;
  input ENABLE;
  wire ENABLE;
  wire REG1_0_;
  wire REG1_1_;
  wire REG1_2_;
  wire REG1_30_;
  wire REG1_3_;
  wire REG1_4_;
  wire REG1_5_;
  wire REG1_6_;
  wire REG2_0_;
  wire REG2_1_;
  wire REG2_2_;
  wire REG2_30_;
  wire REG2_3_;
  wire REG2_4_;
  wire REG2_5_;
  wire REG2_6_;
  wire REG3_0_;
  wire REG3_1_;
  wire REG3_2_;
  wire REG3_30_;
  wire REG3_3_;
  wire REG3_4_;
  wire REG3_5_;
  wire REG3_6_;
  wire REG4_0_;
  wire REG4_1_;
  wire REG4_2_;
  wire REG4_30_;
  wire REG4_3_;
  wire REG4_4_;
  wire REG4_5_;
  wire REG4_6_;
  input RESET;
  wire RESET;
  input RESTART;
  wire RESTART;
  wire RLAST_0_;
  wire RLAST_1_;
  wire RLAST_2_;
  wire RLAST_3_;
  wire RLAST_4_;
  wire RLAST_5_;
  wire RLAST_6_;
  wire RLAST_7_;
  wire RMAX_0_;
  wire RMAX_1_;
  wire RMAX_2_;
  wire RMAX_30_;
  wire RMAX_3_;
  wire RMAX_4_;
  wire RMAX_5_;
  wire RMAX_6_;
  wire RMIN_0_;
  wire RMIN_1_;
  wire RMIN_2_;
  wire RMIN_30_;
  wire RMIN_3_;
  wire RMIN_4_;
  wire RMIN_5_;
  wire RMIN_6_;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  INV_X1 _470_ (
    .A(DATA_IN_7_),
    .ZN(_141_)
  );
  INV_X1 _471_ (
    .A(DATA_IN_6_),
    .ZN(_142_)
  );
  INV_X1 _472_ (
    .A(DATA_IN_5_),
    .ZN(_143_)
  );
  INV_X1 _473_ (
    .A(DATA_IN_4_),
    .ZN(_144_)
  );
  INV_X1 _474_ (
    .A(DATA_IN_3_),
    .ZN(_145_)
  );
  INV_X1 _475_ (
    .A(DATA_IN_2_),
    .ZN(_146_)
  );
  INV_X1 _476_ (
    .A(DATA_IN_1_),
    .ZN(_147_)
  );
  INV_X1 _477_ (
    .A(DATA_IN_0_),
    .ZN(_148_)
  );
  INV_X1 _478_ (
    .A(RLAST_3_),
    .ZN(_149_)
  );
  INV_X1 _479_ (
    .A(RLAST_2_),
    .ZN(_150_)
  );
  INV_X1 _480_ (
    .A(RLAST_1_),
    .ZN(_151_)
  );
  INV_X1 _481_ (
    .A(RLAST_0_),
    .ZN(_152_)
  );
  INV_X1 _482_ (
    .A(ENABLE),
    .ZN(_153_)
  );
  INV_X1 _483_ (
    .A(AVERAGE),
    .ZN(_154_)
  );
  INV_X1 _484_ (
    .A(RESTART),
    .ZN(_155_)
  );
  INV_X1 _485_ (
    .A(RESET),
    .ZN(_010_)
  );
  NOR2_X1 _486_ (
    .A1(stato_2_),
    .A2(stato_1_),
    .ZN(_156_)
  );
  INV_X1 _487_ (
    .A(_156_),
    .ZN(_000_)
  );
  NAND2_X1 _488_ (
    .A1(REG3_30_),
    .A2(_156_),
    .ZN(_157_)
  );
  NAND2_X1 _489_ (
    .A1(REG2_30_),
    .A2(stato_1_),
    .ZN(_158_)
  );
  NAND2_X1 _490_ (
    .A1(_157_),
    .A2(_158_),
    .ZN(_140_)
  );
  NAND2_X1 _491_ (
    .A1(REG3_6_),
    .A2(_156_),
    .ZN(_159_)
  );
  NAND2_X1 _492_ (
    .A1(REG2_6_),
    .A2(stato_1_),
    .ZN(_160_)
  );
  NAND2_X1 _493_ (
    .A1(_159_),
    .A2(_160_),
    .ZN(_139_)
  );
  NAND2_X1 _494_ (
    .A1(REG3_5_),
    .A2(_156_),
    .ZN(_161_)
  );
  NAND2_X1 _495_ (
    .A1(REG2_5_),
    .A2(stato_1_),
    .ZN(_162_)
  );
  NAND2_X1 _496_ (
    .A1(_161_),
    .A2(_162_),
    .ZN(_138_)
  );
  NAND2_X1 _497_ (
    .A1(REG3_4_),
    .A2(_156_),
    .ZN(_163_)
  );
  NAND2_X1 _498_ (
    .A1(REG2_4_),
    .A2(stato_1_),
    .ZN(_164_)
  );
  NAND2_X1 _499_ (
    .A1(_163_),
    .A2(_164_),
    .ZN(_137_)
  );
  NAND2_X1 _500_ (
    .A1(REG3_3_),
    .A2(_156_),
    .ZN(_165_)
  );
  NAND2_X1 _501_ (
    .A1(REG2_3_),
    .A2(stato_1_),
    .ZN(_166_)
  );
  NAND2_X1 _502_ (
    .A1(_165_),
    .A2(_166_),
    .ZN(_136_)
  );
  NAND2_X1 _503_ (
    .A1(REG3_2_),
    .A2(_156_),
    .ZN(_167_)
  );
  NAND2_X1 _504_ (
    .A1(REG2_2_),
    .A2(stato_1_),
    .ZN(_168_)
  );
  NAND2_X1 _505_ (
    .A1(_167_),
    .A2(_168_),
    .ZN(_135_)
  );
  NAND2_X1 _506_ (
    .A1(REG3_1_),
    .A2(_156_),
    .ZN(_169_)
  );
  NAND2_X1 _507_ (
    .A1(REG2_1_),
    .A2(stato_1_),
    .ZN(_170_)
  );
  NAND2_X1 _508_ (
    .A1(_169_),
    .A2(_170_),
    .ZN(_134_)
  );
  NAND2_X1 _509_ (
    .A1(REG3_0_),
    .A2(_156_),
    .ZN(_171_)
  );
  NAND2_X1 _510_ (
    .A1(REG2_0_),
    .A2(stato_1_),
    .ZN(_172_)
  );
  NAND2_X1 _511_ (
    .A1(_171_),
    .A2(_172_),
    .ZN(_133_)
  );
  NAND2_X1 _512_ (
    .A1(REG2_30_),
    .A2(_156_),
    .ZN(_173_)
  );
  NAND2_X1 _513_ (
    .A1(REG1_30_),
    .A2(stato_1_),
    .ZN(_174_)
  );
  NAND2_X1 _514_ (
    .A1(_173_),
    .A2(_174_),
    .ZN(_132_)
  );
  NAND2_X1 _515_ (
    .A1(REG2_6_),
    .A2(_156_),
    .ZN(_175_)
  );
  NAND2_X1 _516_ (
    .A1(REG1_6_),
    .A2(stato_1_),
    .ZN(_176_)
  );
  NAND2_X1 _517_ (
    .A1(_175_),
    .A2(_176_),
    .ZN(_131_)
  );
  NAND2_X1 _518_ (
    .A1(REG2_5_),
    .A2(_156_),
    .ZN(_177_)
  );
  NAND2_X1 _519_ (
    .A1(REG1_5_),
    .A2(stato_1_),
    .ZN(_178_)
  );
  NAND2_X1 _520_ (
    .A1(_177_),
    .A2(_178_),
    .ZN(_130_)
  );
  NAND2_X1 _521_ (
    .A1(REG2_4_),
    .A2(_156_),
    .ZN(_179_)
  );
  NAND2_X1 _522_ (
    .A1(REG1_4_),
    .A2(stato_1_),
    .ZN(_180_)
  );
  NAND2_X1 _523_ (
    .A1(_179_),
    .A2(_180_),
    .ZN(_129_)
  );
  NAND2_X1 _524_ (
    .A1(REG2_3_),
    .A2(_156_),
    .ZN(_181_)
  );
  NAND2_X1 _525_ (
    .A1(REG1_3_),
    .A2(stato_1_),
    .ZN(_182_)
  );
  NAND2_X1 _526_ (
    .A1(_181_),
    .A2(_182_),
    .ZN(_128_)
  );
  NAND2_X1 _527_ (
    .A1(REG2_2_),
    .A2(_156_),
    .ZN(_183_)
  );
  NAND2_X1 _528_ (
    .A1(REG1_2_),
    .A2(stato_1_),
    .ZN(_184_)
  );
  NAND2_X1 _529_ (
    .A1(_183_),
    .A2(_184_),
    .ZN(_127_)
  );
  NAND2_X1 _530_ (
    .A1(REG2_1_),
    .A2(_156_),
    .ZN(_185_)
  );
  NAND2_X1 _531_ (
    .A1(REG1_1_),
    .A2(stato_1_),
    .ZN(_186_)
  );
  NAND2_X1 _532_ (
    .A1(_185_),
    .A2(_186_),
    .ZN(_126_)
  );
  NAND2_X1 _533_ (
    .A1(REG2_0_),
    .A2(_156_),
    .ZN(_187_)
  );
  NAND2_X1 _534_ (
    .A1(REG1_0_),
    .A2(stato_1_),
    .ZN(_188_)
  );
  NAND2_X1 _535_ (
    .A1(_187_),
    .A2(_188_),
    .ZN(_125_)
  );
  NAND2_X1 _536_ (
    .A1(REG1_30_),
    .A2(_156_),
    .ZN(_189_)
  );
  NAND2_X1 _537_ (
    .A1(DATA_IN_7_),
    .A2(stato_1_),
    .ZN(_190_)
  );
  NAND2_X1 _538_ (
    .A1(_189_),
    .A2(_190_),
    .ZN(_124_)
  );
  NAND2_X1 _539_ (
    .A1(REG1_6_),
    .A2(_156_),
    .ZN(_191_)
  );
  NAND2_X1 _540_ (
    .A1(DATA_IN_6_),
    .A2(stato_1_),
    .ZN(_192_)
  );
  NAND2_X1 _541_ (
    .A1(_191_),
    .A2(_192_),
    .ZN(_123_)
  );
  NAND2_X1 _542_ (
    .A1(REG1_5_),
    .A2(_156_),
    .ZN(_193_)
  );
  NAND2_X1 _543_ (
    .A1(DATA_IN_5_),
    .A2(stato_1_),
    .ZN(_194_)
  );
  NAND2_X1 _544_ (
    .A1(_193_),
    .A2(_194_),
    .ZN(_122_)
  );
  NAND2_X1 _545_ (
    .A1(REG1_4_),
    .A2(_156_),
    .ZN(_195_)
  );
  NAND2_X1 _546_ (
    .A1(DATA_IN_4_),
    .A2(stato_1_),
    .ZN(_196_)
  );
  NAND2_X1 _547_ (
    .A1(_195_),
    .A2(_196_),
    .ZN(_121_)
  );
  NAND2_X1 _548_ (
    .A1(REG1_3_),
    .A2(_156_),
    .ZN(_197_)
  );
  NAND2_X1 _549_ (
    .A1(DATA_IN_3_),
    .A2(stato_1_),
    .ZN(_198_)
  );
  NAND2_X1 _550_ (
    .A1(_197_),
    .A2(_198_),
    .ZN(_120_)
  );
  NAND2_X1 _551_ (
    .A1(REG1_2_),
    .A2(_156_),
    .ZN(_199_)
  );
  NAND2_X1 _552_ (
    .A1(DATA_IN_2_),
    .A2(stato_1_),
    .ZN(_200_)
  );
  NAND2_X1 _553_ (
    .A1(_199_),
    .A2(_200_),
    .ZN(_119_)
  );
  NAND2_X1 _554_ (
    .A1(REG1_1_),
    .A2(_156_),
    .ZN(_201_)
  );
  NAND2_X1 _555_ (
    .A1(DATA_IN_1_),
    .A2(stato_1_),
    .ZN(_202_)
  );
  NAND2_X1 _556_ (
    .A1(_201_),
    .A2(_202_),
    .ZN(_118_)
  );
  NAND2_X1 _557_ (
    .A1(REG1_0_),
    .A2(_156_),
    .ZN(_203_)
  );
  NAND2_X1 _558_ (
    .A1(DATA_IN_0_),
    .A2(stato_1_),
    .ZN(_204_)
  );
  NAND2_X1 _559_ (
    .A1(_203_),
    .A2(_204_),
    .ZN(_117_)
  );
  AND2_X1 _560_ (
    .A1(_141_),
    .A2(RMAX_30_),
    .ZN(_205_)
  );
  NOR2_X1 _561_ (
    .A1(_141_),
    .A2(RMAX_30_),
    .ZN(_206_)
  );
  AND2_X1 _562_ (
    .A1(_142_),
    .A2(RMAX_6_),
    .ZN(_207_)
  );
  NOR2_X1 _563_ (
    .A1(_142_),
    .A2(RMAX_6_),
    .ZN(_208_)
  );
  AND2_X1 _564_ (
    .A1(_143_),
    .A2(RMAX_5_),
    .ZN(_209_)
  );
  NOR2_X1 _565_ (
    .A1(_143_),
    .A2(RMAX_5_),
    .ZN(_210_)
  );
  NOR2_X1 _566_ (
    .A1(_144_),
    .A2(RMAX_4_),
    .ZN(_211_)
  );
  AND2_X1 _567_ (
    .A1(_144_),
    .A2(RMAX_4_),
    .ZN(_212_)
  );
  NOR2_X1 _568_ (
    .A1(_145_),
    .A2(RMAX_3_),
    .ZN(_213_)
  );
  NAND2_X1 _569_ (
    .A1(_145_),
    .A2(RMAX_3_),
    .ZN(_214_)
  );
  NAND2_X1 _570_ (
    .A1(_146_),
    .A2(RMAX_2_),
    .ZN(_215_)
  );
  NAND2_X1 _571_ (
    .A1(_214_),
    .A2(_215_),
    .ZN(_216_)
  );
  NOR2_X1 _572_ (
    .A1(_146_),
    .A2(RMAX_2_),
    .ZN(_217_)
  );
  NOR2_X1 _573_ (
    .A1(_147_),
    .A2(RMAX_1_),
    .ZN(_218_)
  );
  AND2_X1 _574_ (
    .A1(_147_),
    .A2(RMAX_1_),
    .ZN(_219_)
  );
  NOR3_X1 _575_ (
    .A1(_148_),
    .A2(RMAX_0_),
    .A3(_219_),
    .ZN(_220_)
  );
  NOR3_X1 _576_ (
    .A1(_217_),
    .A2(_218_),
    .A3(_220_),
    .ZN(_221_)
  );
  NOR2_X1 _577_ (
    .A1(_216_),
    .A2(_221_),
    .ZN(_222_)
  );
  NOR2_X1 _578_ (
    .A1(_213_),
    .A2(_222_),
    .ZN(_223_)
  );
  NOR2_X1 _579_ (
    .A1(_212_),
    .A2(_223_),
    .ZN(_224_)
  );
  NOR3_X1 _580_ (
    .A1(_210_),
    .A2(_211_),
    .A3(_224_),
    .ZN(_225_)
  );
  NOR2_X1 _581_ (
    .A1(_209_),
    .A2(_225_),
    .ZN(_226_)
  );
  NOR2_X1 _582_ (
    .A1(_208_),
    .A2(_226_),
    .ZN(_227_)
  );
  NOR3_X1 _583_ (
    .A1(_206_),
    .A2(_207_),
    .A3(_227_),
    .ZN(_228_)
  );
  NOR2_X1 _584_ (
    .A1(_205_),
    .A2(_228_),
    .ZN(_229_)
  );
  NAND2_X1 _585_ (
    .A1(stato_1_),
    .A2(_229_),
    .ZN(_230_)
  );
  NOR2_X1 _586_ (
    .A1(RMIN_30_),
    .A2(_141_),
    .ZN(_231_)
  );
  AND2_X1 _587_ (
    .A1(RMIN_6_),
    .A2(_142_),
    .ZN(_232_)
  );
  NOR2_X1 _588_ (
    .A1(RMIN_5_),
    .A2(_143_),
    .ZN(_233_)
  );
  NAND2_X1 _589_ (
    .A1(RMIN_3_),
    .A2(_145_),
    .ZN(_234_)
  );
  OR2_X1 _590_ (
    .A1(RMIN_2_),
    .A2(_146_),
    .ZN(_235_)
  );
  NAND2_X1 _591_ (
    .A1(RMIN_2_),
    .A2(_146_),
    .ZN(_236_)
  );
  OR2_X1 _592_ (
    .A1(RMIN_1_),
    .A2(_147_),
    .ZN(_237_)
  );
  NAND2_X1 _593_ (
    .A1(RMIN_1_),
    .A2(_147_),
    .ZN(_238_)
  );
  NAND3_X1 _594_ (
    .A1(RMIN_0_),
    .A2(_148_),
    .A3(_237_),
    .ZN(_239_)
  );
  NAND3_X1 _595_ (
    .A1(_236_),
    .A2(_238_),
    .A3(_239_),
    .ZN(_240_)
  );
  NAND2_X1 _596_ (
    .A1(_235_),
    .A2(_240_),
    .ZN(_241_)
  );
  AND2_X1 _597_ (
    .A1(_234_),
    .A2(_241_),
    .ZN(_242_)
  );
  NOR2_X1 _598_ (
    .A1(RMIN_3_),
    .A2(_145_),
    .ZN(_243_)
  );
  NOR2_X1 _599_ (
    .A1(RMIN_4_),
    .A2(_144_),
    .ZN(_244_)
  );
  NOR3_X1 _600_ (
    .A1(_242_),
    .A2(_243_),
    .A3(_244_),
    .ZN(_245_)
  );
  NAND2_X1 _601_ (
    .A1(RMIN_5_),
    .A2(_143_),
    .ZN(_246_)
  );
  NAND2_X1 _602_ (
    .A1(RMIN_4_),
    .A2(_144_),
    .ZN(_247_)
  );
  NAND2_X1 _603_ (
    .A1(_246_),
    .A2(_247_),
    .ZN(_248_)
  );
  NOR2_X1 _604_ (
    .A1(_245_),
    .A2(_248_),
    .ZN(_249_)
  );
  AND2_X1 _605_ (
    .A1(RMIN_30_),
    .A2(_141_),
    .ZN(_250_)
  );
  NOR2_X1 _606_ (
    .A1(RMIN_6_),
    .A2(_142_),
    .ZN(_251_)
  );
  NOR3_X1 _607_ (
    .A1(_233_),
    .A2(_249_),
    .A3(_251_),
    .ZN(_252_)
  );
  NOR2_X1 _608_ (
    .A1(_232_),
    .A2(_252_),
    .ZN(_253_)
  );
  NOR2_X1 _609_ (
    .A1(_250_),
    .A2(_253_),
    .ZN(_254_)
  );
  NOR3_X1 _610_ (
    .A1(_230_),
    .A2(_231_),
    .A3(_254_),
    .ZN(_255_)
  );
  NOR2_X1 _611_ (
    .A1(_001_),
    .A2(_229_),
    .ZN(_256_)
  );
  NOR3_X1 _612_ (
    .A1(_156_),
    .A2(_255_),
    .A3(_256_),
    .ZN(_257_)
  );
  MUX2_X1 _613_ (
    .A(RMIN_30_),
    .B(DATA_IN_7_),
    .S(_257_),
    .Z(_116_)
  );
  MUX2_X1 _614_ (
    .A(RMIN_6_),
    .B(DATA_IN_6_),
    .S(_257_),
    .Z(_115_)
  );
  MUX2_X1 _615_ (
    .A(RMIN_5_),
    .B(DATA_IN_5_),
    .S(_257_),
    .Z(_114_)
  );
  MUX2_X1 _616_ (
    .A(RMIN_4_),
    .B(DATA_IN_4_),
    .S(_257_),
    .Z(_113_)
  );
  MUX2_X1 _617_ (
    .A(RMIN_3_),
    .B(DATA_IN_3_),
    .S(_257_),
    .Z(_112_)
  );
  MUX2_X1 _618_ (
    .A(RMIN_2_),
    .B(DATA_IN_2_),
    .S(_257_),
    .Z(_111_)
  );
  MUX2_X1 _619_ (
    .A(RMIN_1_),
    .B(DATA_IN_1_),
    .S(_257_),
    .Z(_110_)
  );
  MUX2_X1 _620_ (
    .A(RMIN_0_),
    .B(DATA_IN_0_),
    .S(_257_),
    .Z(_109_)
  );
  NAND2_X1 _621_ (
    .A1(_000_),
    .A2(_230_),
    .ZN(_258_)
  );
  MUX2_X1 _622_ (
    .A(DATA_IN_7_),
    .B(RMAX_30_),
    .S(_258_),
    .Z(_108_)
  );
  MUX2_X1 _623_ (
    .A(DATA_IN_6_),
    .B(RMAX_6_),
    .S(_258_),
    .Z(_107_)
  );
  MUX2_X1 _624_ (
    .A(DATA_IN_5_),
    .B(RMAX_5_),
    .S(_258_),
    .Z(_106_)
  );
  MUX2_X1 _625_ (
    .A(DATA_IN_4_),
    .B(RMAX_4_),
    .S(_258_),
    .Z(_105_)
  );
  MUX2_X1 _626_ (
    .A(DATA_IN_3_),
    .B(RMAX_3_),
    .S(_258_),
    .Z(_104_)
  );
  MUX2_X1 _627_ (
    .A(DATA_IN_2_),
    .B(RMAX_2_),
    .S(_258_),
    .Z(_103_)
  );
  MUX2_X1 _628_ (
    .A(DATA_IN_1_),
    .B(RMAX_1_),
    .S(_258_),
    .Z(_102_)
  );
  MUX2_X1 _629_ (
    .A(DATA_IN_0_),
    .B(RMAX_0_),
    .S(_258_),
    .Z(_101_)
  );
  NAND2_X1 _630_ (
    .A1(DATA_OUT_7_),
    .A2(_156_),
    .ZN(_259_)
  );
  NAND2_X1 _631_ (
    .A1(RLAST_7_),
    .A2(_153_),
    .ZN(_260_)
  );
  NAND2_X1 _632_ (
    .A1(ENABLE),
    .A2(AVERAGE),
    .ZN(_261_)
  );
  OR2_X1 _633_ (
    .A1(_009_),
    .A2(_261_),
    .ZN(_262_)
  );
  NAND2_X1 _634_ (
    .A1(_260_),
    .A2(_262_),
    .ZN(_263_)
  );
  NAND3_X1 _635_ (
    .A1(stato_1_),
    .A2(_155_),
    .A3(_263_),
    .ZN(_264_)
  );
  NAND2_X1 _636_ (
    .A1(_259_),
    .A2(_264_),
    .ZN(_100_)
  );
  NAND2_X1 _637_ (
    .A1(DATA_OUT_6_),
    .A2(_156_),
    .ZN(_265_)
  );
  NAND2_X1 _638_ (
    .A1(RLAST_6_),
    .A2(_153_),
    .ZN(_266_)
  );
  OR2_X1 _639_ (
    .A1(_008_),
    .A2(_261_),
    .ZN(_267_)
  );
  NAND2_X1 _640_ (
    .A1(_266_),
    .A2(_267_),
    .ZN(_268_)
  );
  NAND3_X1 _641_ (
    .A1(stato_1_),
    .A2(_155_),
    .A3(_268_),
    .ZN(_269_)
  );
  NAND2_X1 _642_ (
    .A1(_265_),
    .A2(_269_),
    .ZN(_099_)
  );
  NAND2_X1 _643_ (
    .A1(DATA_OUT_5_),
    .A2(_156_),
    .ZN(_270_)
  );
  NAND2_X1 _644_ (
    .A1(ENABLE),
    .A2(_154_),
    .ZN(_271_)
  );
  NAND2_X1 _645_ (
    .A1(DATA_IN_5_),
    .A2(REG4_5_),
    .ZN(_272_)
  );
  AND2_X1 _646_ (
    .A1(DATA_IN_4_),
    .A2(REG4_4_),
    .ZN(_273_)
  );
  AND2_X1 _647_ (
    .A1(DATA_IN_3_),
    .A2(REG4_3_),
    .ZN(_274_)
  );
  NAND2_X1 _648_ (
    .A1(DATA_IN_2_),
    .A2(REG4_2_),
    .ZN(_275_)
  );
  NAND2_X1 _649_ (
    .A1(DATA_IN_1_),
    .A2(REG4_1_),
    .ZN(_276_)
  );
  NAND2_X1 _650_ (
    .A1(DATA_IN_0_),
    .A2(REG4_0_),
    .ZN(_277_)
  );
  XOR2_X1 _651_ (
    .A(DATA_IN_1_),
    .B(REG4_1_),
    .Z(_278_)
  );
  NAND3_X1 _652_ (
    .A1(DATA_IN_0_),
    .A2(REG4_0_),
    .A3(_278_),
    .ZN(_279_)
  );
  NAND2_X1 _653_ (
    .A1(_276_),
    .A2(_279_),
    .ZN(_280_)
  );
  XOR2_X1 _654_ (
    .A(DATA_IN_2_),
    .B(REG4_2_),
    .Z(_281_)
  );
  NAND2_X1 _655_ (
    .A1(_280_),
    .A2(_281_),
    .ZN(_282_)
  );
  NAND2_X1 _656_ (
    .A1(_275_),
    .A2(_282_),
    .ZN(_283_)
  );
  XOR2_X1 _657_ (
    .A(DATA_IN_3_),
    .B(REG4_3_),
    .Z(_284_)
  );
  AND2_X1 _658_ (
    .A1(_283_),
    .A2(_284_),
    .ZN(_285_)
  );
  NOR2_X1 _659_ (
    .A1(_274_),
    .A2(_285_),
    .ZN(_286_)
  );
  NOR2_X1 _660_ (
    .A1(DATA_IN_4_),
    .A2(REG4_4_),
    .ZN(_287_)
  );
  NOR2_X1 _661_ (
    .A1(_273_),
    .A2(_287_),
    .ZN(_288_)
  );
  NOR3_X1 _662_ (
    .A1(_273_),
    .A2(_286_),
    .A3(_287_),
    .ZN(_289_)
  );
  OR2_X1 _663_ (
    .A1(_273_),
    .A2(_289_),
    .ZN(_290_)
  );
  XOR2_X1 _664_ (
    .A(DATA_IN_5_),
    .B(REG4_5_),
    .Z(_291_)
  );
  NAND2_X1 _665_ (
    .A1(_290_),
    .A2(_291_),
    .ZN(_292_)
  );
  NAND2_X1 _666_ (
    .A1(_272_),
    .A2(_292_),
    .ZN(_293_)
  );
  XOR2_X1 _667_ (
    .A(DATA_IN_6_),
    .B(REG4_6_),
    .Z(_294_)
  );
  XNOR2_X1 _668_ (
    .A(_293_),
    .B(_294_),
    .ZN(_295_)
  );
  OR2_X1 _669_ (
    .A1(_271_),
    .A2(_295_),
    .ZN(_296_)
  );
  OR2_X1 _670_ (
    .A1(_007_),
    .A2(_261_),
    .ZN(_297_)
  );
  NAND2_X1 _671_ (
    .A1(RLAST_5_),
    .A2(_153_),
    .ZN(_298_)
  );
  NAND4_X1 _672_ (
    .A1(_155_),
    .A2(_296_),
    .A3(_297_),
    .A4(_298_),
    .ZN(_299_)
  );
  NAND2_X1 _673_ (
    .A1(RMIN_5_),
    .A2(RMAX_5_),
    .ZN(_300_)
  );
  NAND2_X1 _674_ (
    .A1(RMIN_4_),
    .A2(RMAX_4_),
    .ZN(_301_)
  );
  NAND2_X1 _675_ (
    .A1(RMIN_3_),
    .A2(RMAX_3_),
    .ZN(_302_)
  );
  NAND2_X1 _676_ (
    .A1(RMIN_2_),
    .A2(RMAX_2_),
    .ZN(_303_)
  );
  NAND2_X1 _677_ (
    .A1(RMIN_1_),
    .A2(RMAX_1_),
    .ZN(_304_)
  );
  NAND2_X1 _678_ (
    .A1(RMIN_0_),
    .A2(RMAX_0_),
    .ZN(_305_)
  );
  XOR2_X1 _679_ (
    .A(RMIN_1_),
    .B(RMAX_1_),
    .Z(_306_)
  );
  NAND3_X1 _680_ (
    .A1(RMIN_0_),
    .A2(RMAX_0_),
    .A3(_306_),
    .ZN(_307_)
  );
  NAND2_X1 _681_ (
    .A1(_304_),
    .A2(_307_),
    .ZN(_308_)
  );
  XOR2_X1 _682_ (
    .A(RMIN_2_),
    .B(RMAX_2_),
    .Z(_309_)
  );
  NAND2_X1 _683_ (
    .A1(_308_),
    .A2(_309_),
    .ZN(_310_)
  );
  NAND2_X1 _684_ (
    .A1(_303_),
    .A2(_310_),
    .ZN(_311_)
  );
  XOR2_X1 _685_ (
    .A(RMIN_3_),
    .B(RMAX_3_),
    .Z(_312_)
  );
  NAND2_X1 _686_ (
    .A1(_311_),
    .A2(_312_),
    .ZN(_313_)
  );
  NAND2_X1 _687_ (
    .A1(_302_),
    .A2(_313_),
    .ZN(_314_)
  );
  XOR2_X1 _688_ (
    .A(RMIN_4_),
    .B(RMAX_4_),
    .Z(_315_)
  );
  NAND2_X1 _689_ (
    .A1(_314_),
    .A2(_315_),
    .ZN(_316_)
  );
  NAND2_X1 _690_ (
    .A1(_301_),
    .A2(_316_),
    .ZN(_317_)
  );
  XOR2_X1 _691_ (
    .A(RMIN_5_),
    .B(RMAX_5_),
    .Z(_318_)
  );
  NAND2_X1 _692_ (
    .A1(_317_),
    .A2(_318_),
    .ZN(_319_)
  );
  AND2_X1 _693_ (
    .A1(_300_),
    .A2(_319_),
    .ZN(_320_)
  );
  XOR2_X1 _694_ (
    .A(RMIN_6_),
    .B(RMAX_6_),
    .Z(_321_)
  );
  NOR2_X1 _695_ (
    .A1(_320_),
    .A2(_321_),
    .ZN(_322_)
  );
  AND2_X1 _696_ (
    .A1(_320_),
    .A2(_321_),
    .ZN(_323_)
  );
  OR3_X1 _697_ (
    .A1(_155_),
    .A2(_322_),
    .A3(_323_),
    .ZN(_324_)
  );
  NAND3_X1 _698_ (
    .A1(stato_1_),
    .A2(_299_),
    .A3(_324_),
    .ZN(_325_)
  );
  NAND2_X1 _699_ (
    .A1(_270_),
    .A2(_325_),
    .ZN(_098_)
  );
  NAND2_X1 _700_ (
    .A1(DATA_OUT_4_),
    .A2(_156_),
    .ZN(_326_)
  );
  OR2_X1 _701_ (
    .A1(_290_),
    .A2(_291_),
    .ZN(_327_)
  );
  NAND4_X1 _702_ (
    .A1(ENABLE),
    .A2(_154_),
    .A3(_292_),
    .A4(_327_),
    .ZN(_328_)
  );
  OR2_X1 _703_ (
    .A1(_006_),
    .A2(_261_),
    .ZN(_329_)
  );
  NAND2_X1 _704_ (
    .A1(RLAST_4_),
    .A2(_153_),
    .ZN(_330_)
  );
  NAND4_X1 _705_ (
    .A1(_155_),
    .A2(_328_),
    .A3(_329_),
    .A4(_330_),
    .ZN(_331_)
  );
  XNOR2_X1 _706_ (
    .A(_317_),
    .B(_318_),
    .ZN(_332_)
  );
  NAND2_X1 _707_ (
    .A1(RESTART),
    .A2(_332_),
    .ZN(_333_)
  );
  NAND3_X1 _708_ (
    .A1(stato_1_),
    .A2(_331_),
    .A3(_333_),
    .ZN(_334_)
  );
  NAND2_X1 _709_ (
    .A1(_326_),
    .A2(_334_),
    .ZN(_097_)
  );
  NAND2_X1 _710_ (
    .A1(DATA_OUT_3_),
    .A2(_156_),
    .ZN(_335_)
  );
  NOR3_X1 _711_ (
    .A1(_274_),
    .A2(_285_),
    .A3(_288_),
    .ZN(_336_)
  );
  NOR3_X1 _712_ (
    .A1(_271_),
    .A2(_289_),
    .A3(_336_),
    .ZN(_337_)
  );
  NOR2_X1 _713_ (
    .A1(_005_),
    .A2(_261_),
    .ZN(_338_)
  );
  NOR2_X1 _714_ (
    .A1(_149_),
    .A2(ENABLE),
    .ZN(_339_)
  );
  OR4_X1 _715_ (
    .A1(RESTART),
    .A2(_337_),
    .A3(_338_),
    .A4(_339_),
    .ZN(_340_)
  );
  XNOR2_X1 _716_ (
    .A(_314_),
    .B(_315_),
    .ZN(_341_)
  );
  NAND2_X1 _717_ (
    .A1(RESTART),
    .A2(_341_),
    .ZN(_342_)
  );
  NAND3_X1 _718_ (
    .A1(stato_1_),
    .A2(_340_),
    .A3(_342_),
    .ZN(_343_)
  );
  NAND2_X1 _719_ (
    .A1(_335_),
    .A2(_343_),
    .ZN(_096_)
  );
  NAND2_X1 _720_ (
    .A1(DATA_OUT_2_),
    .A2(_156_),
    .ZN(_344_)
  );
  NOR2_X1 _721_ (
    .A1(_283_),
    .A2(_284_),
    .ZN(_345_)
  );
  NOR3_X1 _722_ (
    .A1(_271_),
    .A2(_285_),
    .A3(_345_),
    .ZN(_346_)
  );
  NOR2_X1 _723_ (
    .A1(_004_),
    .A2(_261_),
    .ZN(_347_)
  );
  NOR2_X1 _724_ (
    .A1(_150_),
    .A2(ENABLE),
    .ZN(_348_)
  );
  OR4_X1 _725_ (
    .A1(RESTART),
    .A2(_346_),
    .A3(_347_),
    .A4(_348_),
    .ZN(_349_)
  );
  XNOR2_X1 _726_ (
    .A(_311_),
    .B(_312_),
    .ZN(_350_)
  );
  NAND2_X1 _727_ (
    .A1(RESTART),
    .A2(_350_),
    .ZN(_351_)
  );
  NAND3_X1 _728_ (
    .A1(stato_1_),
    .A2(_349_),
    .A3(_351_),
    .ZN(_352_)
  );
  NAND2_X1 _729_ (
    .A1(_344_),
    .A2(_352_),
    .ZN(_095_)
  );
  NAND2_X1 _730_ (
    .A1(DATA_OUT_1_),
    .A2(_156_),
    .ZN(_353_)
  );
  XNOR2_X1 _731_ (
    .A(_280_),
    .B(_281_),
    .ZN(_354_)
  );
  NOR2_X1 _732_ (
    .A1(_271_),
    .A2(_354_),
    .ZN(_355_)
  );
  NOR2_X1 _733_ (
    .A1(_003_),
    .A2(_261_),
    .ZN(_356_)
  );
  NOR2_X1 _734_ (
    .A1(_151_),
    .A2(ENABLE),
    .ZN(_357_)
  );
  OR4_X1 _735_ (
    .A1(RESTART),
    .A2(_355_),
    .A3(_356_),
    .A4(_357_),
    .ZN(_358_)
  );
  XNOR2_X1 _736_ (
    .A(_308_),
    .B(_309_),
    .ZN(_359_)
  );
  NAND2_X1 _737_ (
    .A1(RESTART),
    .A2(_359_),
    .ZN(_360_)
  );
  NAND3_X1 _738_ (
    .A1(stato_1_),
    .A2(_358_),
    .A3(_360_),
    .ZN(_361_)
  );
  NAND2_X1 _739_ (
    .A1(_353_),
    .A2(_361_),
    .ZN(_094_)
  );
  NAND2_X1 _740_ (
    .A1(DATA_OUT_0_),
    .A2(_156_),
    .ZN(_362_)
  );
  XOR2_X1 _741_ (
    .A(_277_),
    .B(_278_),
    .Z(_363_)
  );
  NOR2_X1 _742_ (
    .A1(_271_),
    .A2(_363_),
    .ZN(_364_)
  );
  NOR2_X1 _743_ (
    .A1(_002_),
    .A2(_261_),
    .ZN(_365_)
  );
  NOR2_X1 _744_ (
    .A1(_152_),
    .A2(ENABLE),
    .ZN(_366_)
  );
  XOR2_X1 _745_ (
    .A(_305_),
    .B(_306_),
    .Z(_367_)
  );
  NAND2_X1 _746_ (
    .A1(RESTART),
    .A2(_367_),
    .ZN(_368_)
  );
  OR4_X1 _747_ (
    .A1(RESTART),
    .A2(_364_),
    .A3(_365_),
    .A4(_366_),
    .ZN(_369_)
  );
  NAND3_X1 _748_ (
    .A1(stato_1_),
    .A2(_368_),
    .A3(_369_),
    .ZN(_370_)
  );
  NAND2_X1 _749_ (
    .A1(_362_),
    .A2(_370_),
    .ZN(_093_)
  );
  NAND2_X1 _750_ (
    .A1(RLAST_7_),
    .A2(_156_),
    .ZN(_371_)
  );
  MUX2_X1 _751_ (
    .A(RLAST_7_),
    .B(DATA_IN_7_),
    .S(ENABLE),
    .Z(_372_)
  );
  NOR2_X1 _752_ (
    .A1(_001_),
    .A2(_156_),
    .ZN(_373_)
  );
  NAND2_X1 _753_ (
    .A1(_372_),
    .A2(_373_),
    .ZN(_374_)
  );
  NAND2_X1 _754_ (
    .A1(_371_),
    .A2(_374_),
    .ZN(_092_)
  );
  NAND2_X1 _755_ (
    .A1(RLAST_6_),
    .A2(_156_),
    .ZN(_375_)
  );
  MUX2_X1 _756_ (
    .A(RLAST_6_),
    .B(DATA_IN_6_),
    .S(ENABLE),
    .Z(_376_)
  );
  NAND2_X1 _757_ (
    .A1(_373_),
    .A2(_376_),
    .ZN(_377_)
  );
  NAND2_X1 _758_ (
    .A1(_375_),
    .A2(_377_),
    .ZN(_091_)
  );
  NAND2_X1 _759_ (
    .A1(RLAST_5_),
    .A2(_156_),
    .ZN(_378_)
  );
  MUX2_X1 _760_ (
    .A(RLAST_5_),
    .B(DATA_IN_5_),
    .S(ENABLE),
    .Z(_379_)
  );
  NAND2_X1 _761_ (
    .A1(_373_),
    .A2(_379_),
    .ZN(_380_)
  );
  NAND2_X1 _762_ (
    .A1(_378_),
    .A2(_380_),
    .ZN(_090_)
  );
  NAND2_X1 _763_ (
    .A1(RLAST_4_),
    .A2(_156_),
    .ZN(_381_)
  );
  MUX2_X1 _764_ (
    .A(RLAST_4_),
    .B(DATA_IN_4_),
    .S(ENABLE),
    .Z(_382_)
  );
  NAND2_X1 _765_ (
    .A1(_373_),
    .A2(_382_),
    .ZN(_383_)
  );
  NAND2_X1 _766_ (
    .A1(_381_),
    .A2(_383_),
    .ZN(_089_)
  );
  NAND2_X1 _767_ (
    .A1(RLAST_3_),
    .A2(_156_),
    .ZN(_384_)
  );
  MUX2_X1 _768_ (
    .A(RLAST_3_),
    .B(DATA_IN_3_),
    .S(ENABLE),
    .Z(_385_)
  );
  NAND2_X1 _769_ (
    .A1(_373_),
    .A2(_385_),
    .ZN(_386_)
  );
  NAND2_X1 _770_ (
    .A1(_384_),
    .A2(_386_),
    .ZN(_088_)
  );
  NAND2_X1 _771_ (
    .A1(RLAST_2_),
    .A2(_156_),
    .ZN(_387_)
  );
  MUX2_X1 _772_ (
    .A(RLAST_2_),
    .B(DATA_IN_2_),
    .S(ENABLE),
    .Z(_388_)
  );
  NAND2_X1 _773_ (
    .A1(_373_),
    .A2(_388_),
    .ZN(_389_)
  );
  NAND2_X1 _774_ (
    .A1(_387_),
    .A2(_389_),
    .ZN(_087_)
  );
  NAND2_X1 _775_ (
    .A1(RLAST_1_),
    .A2(_156_),
    .ZN(_390_)
  );
  MUX2_X1 _776_ (
    .A(RLAST_1_),
    .B(DATA_IN_1_),
    .S(ENABLE),
    .Z(_391_)
  );
  NAND2_X1 _777_ (
    .A1(_373_),
    .A2(_391_),
    .ZN(_392_)
  );
  NAND2_X1 _778_ (
    .A1(_390_),
    .A2(_392_),
    .ZN(_086_)
  );
  NAND2_X1 _779_ (
    .A1(RLAST_0_),
    .A2(_156_),
    .ZN(_393_)
  );
  MUX2_X1 _780_ (
    .A(RLAST_0_),
    .B(DATA_IN_0_),
    .S(ENABLE),
    .Z(_394_)
  );
  NAND2_X1 _781_ (
    .A1(_373_),
    .A2(_394_),
    .ZN(_395_)
  );
  NAND2_X1 _782_ (
    .A1(_393_),
    .A2(_395_),
    .ZN(_085_)
  );
  NAND2_X1 _783_ (
    .A1(REG4_30_),
    .A2(_156_),
    .ZN(_396_)
  );
  NAND2_X1 _784_ (
    .A1(REG3_30_),
    .A2(stato_1_),
    .ZN(_397_)
  );
  NAND2_X1 _785_ (
    .A1(_396_),
    .A2(_397_),
    .ZN(_084_)
  );
  NAND2_X1 _786_ (
    .A1(REG4_6_),
    .A2(_156_),
    .ZN(_398_)
  );
  NAND2_X1 _787_ (
    .A1(REG3_6_),
    .A2(stato_1_),
    .ZN(_399_)
  );
  NAND2_X1 _788_ (
    .A1(_398_),
    .A2(_399_),
    .ZN(_083_)
  );
  NAND2_X1 _789_ (
    .A1(REG4_5_),
    .A2(_156_),
    .ZN(_400_)
  );
  NAND2_X1 _790_ (
    .A1(REG3_5_),
    .A2(stato_1_),
    .ZN(_401_)
  );
  NAND2_X1 _791_ (
    .A1(_400_),
    .A2(_401_),
    .ZN(_082_)
  );
  NAND2_X1 _792_ (
    .A1(REG4_4_),
    .A2(_156_),
    .ZN(_402_)
  );
  NAND2_X1 _793_ (
    .A1(REG3_4_),
    .A2(stato_1_),
    .ZN(_403_)
  );
  NAND2_X1 _794_ (
    .A1(_402_),
    .A2(_403_),
    .ZN(_081_)
  );
  NAND2_X1 _795_ (
    .A1(REG4_3_),
    .A2(_156_),
    .ZN(_404_)
  );
  NAND2_X1 _796_ (
    .A1(REG3_3_),
    .A2(stato_1_),
    .ZN(_405_)
  );
  NAND2_X1 _797_ (
    .A1(_404_),
    .A2(_405_),
    .ZN(_080_)
  );
  NAND2_X1 _798_ (
    .A1(REG4_2_),
    .A2(_156_),
    .ZN(_406_)
  );
  NAND2_X1 _799_ (
    .A1(REG3_2_),
    .A2(stato_1_),
    .ZN(_407_)
  );
  NAND2_X1 _800_ (
    .A1(_406_),
    .A2(_407_),
    .ZN(_079_)
  );
  NAND2_X1 _801_ (
    .A1(REG4_1_),
    .A2(_156_),
    .ZN(_408_)
  );
  NAND2_X1 _802_ (
    .A1(REG3_1_),
    .A2(stato_1_),
    .ZN(_409_)
  );
  NAND2_X1 _803_ (
    .A1(_408_),
    .A2(_409_),
    .ZN(_078_)
  );
  NAND2_X1 _804_ (
    .A1(REG4_0_),
    .A2(_156_),
    .ZN(_410_)
  );
  NAND2_X1 _805_ (
    .A1(REG3_0_),
    .A2(stato_1_),
    .ZN(_411_)
  );
  NAND2_X1 _806_ (
    .A1(_410_),
    .A2(_411_),
    .ZN(_077_)
  );
  INV_X1 _807_ (
    .A(RESET),
    .ZN(_011_)
  );
  INV_X1 _808_ (
    .A(RESET),
    .ZN(_012_)
  );
  INV_X1 _809_ (
    .A(RESET),
    .ZN(_013_)
  );
  INV_X1 _810_ (
    .A(RESET),
    .ZN(_014_)
  );
  INV_X1 _811_ (
    .A(RESET),
    .ZN(_015_)
  );
  INV_X1 _812_ (
    .A(RESET),
    .ZN(_016_)
  );
  INV_X1 _813_ (
    .A(RESET),
    .ZN(_017_)
  );
  INV_X1 _814_ (
    .A(RESET),
    .ZN(_018_)
  );
  INV_X1 _815_ (
    .A(RESET),
    .ZN(_019_)
  );
  INV_X1 _816_ (
    .A(RESET),
    .ZN(_020_)
  );
  INV_X1 _817_ (
    .A(RESET),
    .ZN(_021_)
  );
  INV_X1 _818_ (
    .A(RESET),
    .ZN(_022_)
  );
  INV_X1 _819_ (
    .A(RESET),
    .ZN(_023_)
  );
  INV_X1 _820_ (
    .A(RESET),
    .ZN(_024_)
  );
  INV_X1 _821_ (
    .A(RESET),
    .ZN(_025_)
  );
  INV_X1 _822_ (
    .A(RESET),
    .ZN(_026_)
  );
  INV_X1 _823_ (
    .A(RESET),
    .ZN(_027_)
  );
  INV_X1 _824_ (
    .A(RESET),
    .ZN(_028_)
  );
  INV_X1 _825_ (
    .A(RESET),
    .ZN(_029_)
  );
  INV_X1 _826_ (
    .A(RESET),
    .ZN(_030_)
  );
  INV_X1 _827_ (
    .A(RESET),
    .ZN(_031_)
  );
  INV_X1 _828_ (
    .A(RESET),
    .ZN(_032_)
  );
  INV_X1 _829_ (
    .A(RESET),
    .ZN(_033_)
  );
  INV_X1 _830_ (
    .A(RESET),
    .ZN(_034_)
  );
  INV_X1 _831_ (
    .A(RESET),
    .ZN(_035_)
  );
  INV_X1 _832_ (
    .A(RESET),
    .ZN(_036_)
  );
  INV_X1 _833_ (
    .A(RESET),
    .ZN(_037_)
  );
  INV_X1 _834_ (
    .A(RESET),
    .ZN(_038_)
  );
  INV_X1 _835_ (
    .A(RESET),
    .ZN(_039_)
  );
  INV_X1 _836_ (
    .A(RESET),
    .ZN(_040_)
  );
  INV_X1 _837_ (
    .A(RESET),
    .ZN(_041_)
  );
  INV_X1 _838_ (
    .A(RESET),
    .ZN(_042_)
  );
  INV_X1 _839_ (
    .A(RESET),
    .ZN(_043_)
  );
  INV_X1 _840_ (
    .A(RESET),
    .ZN(_044_)
  );
  INV_X1 _841_ (
    .A(RESET),
    .ZN(_045_)
  );
  INV_X1 _842_ (
    .A(RESET),
    .ZN(_046_)
  );
  INV_X1 _843_ (
    .A(RESET),
    .ZN(_047_)
  );
  INV_X1 _844_ (
    .A(RESET),
    .ZN(_048_)
  );
  INV_X1 _845_ (
    .A(RESET),
    .ZN(_049_)
  );
  INV_X1 _846_ (
    .A(RESET),
    .ZN(_050_)
  );
  INV_X1 _847_ (
    .A(RESET),
    .ZN(_051_)
  );
  INV_X1 _848_ (
    .A(RESET),
    .ZN(_052_)
  );
  INV_X1 _849_ (
    .A(RESET),
    .ZN(_053_)
  );
  INV_X1 _850_ (
    .A(RESET),
    .ZN(_054_)
  );
  INV_X1 _851_ (
    .A(RESET),
    .ZN(_055_)
  );
  INV_X1 _852_ (
    .A(RESET),
    .ZN(_056_)
  );
  INV_X1 _853_ (
    .A(RESET),
    .ZN(_057_)
  );
  INV_X1 _854_ (
    .A(RESET),
    .ZN(_058_)
  );
  INV_X1 _855_ (
    .A(RESET),
    .ZN(_059_)
  );
  INV_X1 _856_ (
    .A(RESET),
    .ZN(_060_)
  );
  INV_X1 _857_ (
    .A(RESET),
    .ZN(_061_)
  );
  INV_X1 _858_ (
    .A(RESET),
    .ZN(_062_)
  );
  INV_X1 _859_ (
    .A(RESET),
    .ZN(_063_)
  );
  INV_X1 _860_ (
    .A(RESET),
    .ZN(_064_)
  );
  INV_X1 _861_ (
    .A(RESET),
    .ZN(_065_)
  );
  INV_X1 _862_ (
    .A(RESET),
    .ZN(_066_)
  );
  INV_X1 _863_ (
    .A(RESET),
    .ZN(_067_)
  );
  INV_X1 _864_ (
    .A(RESET),
    .ZN(_068_)
  );
  INV_X1 _865_ (
    .A(RESET),
    .ZN(_069_)
  );
  INV_X1 _866_ (
    .A(RESET),
    .ZN(_070_)
  );
  INV_X1 _867_ (
    .A(RESET),
    .ZN(_071_)
  );
  INV_X1 _868_ (
    .A(RESET),
    .ZN(_072_)
  );
  INV_X1 _869_ (
    .A(RESET),
    .ZN(_073_)
  );
  INV_X1 _870_ (
    .A(RESET),
    .ZN(_074_)
  );
  INV_X1 _871_ (
    .A(RESET),
    .ZN(_075_)
  );
  INV_X1 _872_ (
    .A(RESET),
    .ZN(_076_)
  );
  SDFFR_X1 _873_ (
    .CK(CK),
    .D(_077_),
    .Q(REG4_0_),
    .QN(_002_),
    .RN(_010_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _874_ (
    .CK(CK),
    .D(_078_),
    .Q(REG4_1_),
    .QN(_003_),
    .RN(_011_),
    .SE(test_se),
    .SI(REG4_0_)
  );
  SDFFR_X1 _875_ (
    .CK(CK),
    .D(_079_),
    .Q(REG4_2_),
    .QN(_004_),
    .RN(_012_),
    .SE(test_se),
    .SI(REG4_1_)
  );
  SDFFR_X1 _876_ (
    .CK(CK),
    .D(_080_),
    .Q(REG4_3_),
    .QN(_005_),
    .RN(_013_),
    .SE(test_se),
    .SI(REG4_2_)
  );
  SDFFR_X1 _877_ (
    .CK(CK),
    .D(_081_),
    .Q(REG4_4_),
    .QN(_006_),
    .RN(_014_),
    .SE(test_se),
    .SI(REG4_3_)
  );
  SDFFR_X1 _878_ (
    .CK(CK),
    .D(_082_),
    .Q(REG4_5_),
    .QN(_007_),
    .RN(_015_),
    .SE(test_se),
    .SI(REG4_4_)
  );
  SDFFR_X1 _879_ (
    .CK(CK),
    .D(_083_),
    .Q(REG4_6_),
    .QN(_008_),
    .RN(_016_),
    .SE(test_se),
    .SI(REG4_5_)
  );
  SDFFR_X1 _880_ (
    .CK(CK),
    .D(_084_),
    .Q(REG4_30_),
    .QN(_009_),
    .RN(_017_),
    .SE(test_se),
    .SI(REG4_6_)
  );
  SDFFRS_X1 _881_ (
    .CK(CK),
    .D(_const0_),
    .Q(stato_0_),
    .RN(_const1_),
    .SN(_018_),
    .SE(test_se),
    .SI(REG4_30_)
  );
  SDFFR_X1 _882_ (
    .CK(CK),
    .D(_000_),
    .Q(stato_1_),
    .QN(_001_),
    .RN(_019_),
    .SE(test_se),
    .SI(stato_0_)
  );
  SDFFR_X1 _883_ (
    .CK(CK),
    .D(stato_0_),
    .Q(stato_2_),
    .RN(_020_),
    .SE(test_se),
    .SI(stato_1_)
  );
  SDFFR_X1 _884_ (
    .CK(CK),
    .D(_085_),
    .Q(RLAST_0_),
    .RN(_021_),
    .SE(test_se),
    .SI(stato_2_)
  );
  SDFFR_X1 _885_ (
    .CK(CK),
    .D(_086_),
    .Q(RLAST_1_),
    .RN(_022_),
    .SE(test_se),
    .SI(RLAST_0_)
  );
  SDFFR_X1 _886_ (
    .CK(CK),
    .D(_087_),
    .Q(RLAST_2_),
    .RN(_023_),
    .SE(test_se),
    .SI(RLAST_1_)
  );
  SDFFR_X1 _887_ (
    .CK(CK),
    .D(_088_),
    .Q(RLAST_3_),
    .RN(_024_),
    .SE(test_se),
    .SI(RLAST_2_)
  );
  SDFFR_X1 _888_ (
    .CK(CK),
    .D(_089_),
    .Q(RLAST_4_),
    .RN(_025_),
    .SE(test_se),
    .SI(RLAST_3_)
  );
  SDFFR_X1 _889_ (
    .CK(CK),
    .D(_090_),
    .Q(RLAST_5_),
    .RN(_026_),
    .SE(test_se),
    .SI(RLAST_4_)
  );
  SDFFR_X1 _890_ (
    .CK(CK),
    .D(_091_),
    .Q(RLAST_6_),
    .RN(_027_),
    .SE(test_se),
    .SI(RLAST_5_)
  );
  SDFFR_X1 _891_ (
    .CK(CK),
    .D(_092_),
    .Q(RLAST_7_),
    .RN(_028_),
    .SE(test_se),
    .SI(RLAST_6_)
  );
  SDFFR_X1 _892_ (
    .CK(CK),
    .D(_093_),
    .Q(DATA_OUT_0_),
    .RN(_029_),
    .SE(test_se),
    .SI(RLAST_7_)
  );
  SDFFR_X1 _893_ (
    .CK(CK),
    .D(_094_),
    .Q(DATA_OUT_1_),
    .RN(_030_),
    .SE(test_se),
    .SI(DATA_OUT_0_)
  );
  SDFFR_X1 _894_ (
    .CK(CK),
    .D(_095_),
    .Q(DATA_OUT_2_),
    .RN(_031_),
    .SE(test_se),
    .SI(DATA_OUT_1_)
  );
  SDFFR_X1 _895_ (
    .CK(CK),
    .D(_096_),
    .Q(DATA_OUT_3_),
    .RN(_032_),
    .SE(test_se),
    .SI(DATA_OUT_2_)
  );
  SDFFR_X1 _896_ (
    .CK(CK),
    .D(_097_),
    .Q(DATA_OUT_4_),
    .RN(_033_),
    .SE(test_se),
    .SI(DATA_OUT_3_)
  );
  SDFFR_X1 _897_ (
    .CK(CK),
    .D(_098_),
    .Q(DATA_OUT_5_),
    .RN(_034_),
    .SE(test_se),
    .SI(DATA_OUT_4_)
  );
  SDFFR_X1 _898_ (
    .CK(CK),
    .D(_099_),
    .Q(DATA_OUT_6_),
    .RN(_035_),
    .SE(test_se),
    .SI(DATA_OUT_5_)
  );
  SDFFR_X1 _899_ (
    .CK(CK),
    .D(_100_),
    .Q(DATA_OUT_7_),
    .RN(_036_),
    .SE(test_se),
    .SI(DATA_OUT_6_)
  );
  SDFFR_X1 _900_ (
    .CK(CK),
    .D(_101_),
    .Q(RMAX_0_),
    .RN(_037_),
    .SE(test_se),
    .SI(DATA_OUT_7_)
  );
  SDFFR_X1 _901_ (
    .CK(CK),
    .D(_102_),
    .Q(RMAX_1_),
    .RN(_038_),
    .SE(test_se),
    .SI(RMAX_0_)
  );
  SDFFR_X1 _902_ (
    .CK(CK),
    .D(_103_),
    .Q(RMAX_2_),
    .RN(_039_),
    .SE(test_se),
    .SI(RMAX_1_)
  );
  SDFFR_X1 _903_ (
    .CK(CK),
    .D(_104_),
    .Q(RMAX_3_),
    .RN(_040_),
    .SE(test_se),
    .SI(RMAX_2_)
  );
  SDFFR_X1 _904_ (
    .CK(CK),
    .D(_105_),
    .Q(RMAX_4_),
    .RN(_041_),
    .SE(test_se),
    .SI(RMAX_3_)
  );
  SDFFR_X1 _905_ (
    .CK(CK),
    .D(_106_),
    .Q(RMAX_5_),
    .RN(_042_),
    .SE(test_se),
    .SI(RMAX_4_)
  );
  SDFFR_X1 _906_ (
    .CK(CK),
    .D(_107_),
    .Q(RMAX_6_),
    .RN(_043_),
    .SE(test_se),
    .SI(RMAX_5_)
  );
  SDFFR_X1 _907_ (
    .CK(CK),
    .D(_108_),
    .Q(RMAX_30_),
    .RN(_044_),
    .SE(test_se),
    .SI(RMAX_6_)
  );
  SDFFR_X1 _908_ (
    .CK(CK),
    .D(_109_),
    .Q(RMIN_0_),
    .RN(_045_),
    .SE(test_se),
    .SI(RMAX_30_)
  );
  SDFFR_X1 _909_ (
    .CK(CK),
    .D(_110_),
    .Q(RMIN_1_),
    .RN(_046_),
    .SE(test_se),
    .SI(RMIN_0_)
  );
  SDFFR_X1 _910_ (
    .CK(CK),
    .D(_111_),
    .Q(RMIN_2_),
    .RN(_047_),
    .SE(test_se),
    .SI(RMIN_1_)
  );
  SDFFR_X1 _911_ (
    .CK(CK),
    .D(_112_),
    .Q(RMIN_3_),
    .RN(_048_),
    .SE(test_se),
    .SI(RMIN_2_)
  );
  SDFFR_X1 _912_ (
    .CK(CK),
    .D(_113_),
    .Q(RMIN_4_),
    .RN(_049_),
    .SE(test_se),
    .SI(RMIN_3_)
  );
  SDFFR_X1 _913_ (
    .CK(CK),
    .D(_114_),
    .Q(RMIN_5_),
    .RN(_050_),
    .SE(test_se),
    .SI(RMIN_4_)
  );
  SDFFR_X1 _914_ (
    .CK(CK),
    .D(_115_),
    .Q(RMIN_6_),
    .RN(_051_),
    .SE(test_se),
    .SI(RMIN_5_)
  );
  SDFFR_X1 _915_ (
    .CK(CK),
    .D(_116_),
    .Q(RMIN_30_),
    .RN(_052_),
    .SE(test_se),
    .SI(RMIN_6_)
  );
  SDFFR_X1 _916_ (
    .CK(CK),
    .D(_117_),
    .Q(REG1_0_),
    .RN(_053_),
    .SE(test_se),
    .SI(RMIN_30_)
  );
  SDFFR_X1 _917_ (
    .CK(CK),
    .D(_118_),
    .Q(REG1_1_),
    .RN(_054_),
    .SE(test_se),
    .SI(REG1_0_)
  );
  SDFFR_X1 _918_ (
    .CK(CK),
    .D(_119_),
    .Q(REG1_2_),
    .RN(_055_),
    .SE(test_se),
    .SI(REG1_1_)
  );
  SDFFR_X1 _919_ (
    .CK(CK),
    .D(_120_),
    .Q(REG1_3_),
    .RN(_056_),
    .SE(test_se),
    .SI(REG1_2_)
  );
  SDFFR_X1 _920_ (
    .CK(CK),
    .D(_121_),
    .Q(REG1_4_),
    .RN(_057_),
    .SE(test_se),
    .SI(REG1_3_)
  );
  SDFFR_X1 _921_ (
    .CK(CK),
    .D(_122_),
    .Q(REG1_5_),
    .RN(_058_),
    .SE(test_se),
    .SI(REG1_4_)
  );
  SDFFR_X1 _922_ (
    .CK(CK),
    .D(_123_),
    .Q(REG1_6_),
    .RN(_059_),
    .SE(test_se),
    .SI(REG1_5_)
  );
  SDFFR_X1 _923_ (
    .CK(CK),
    .D(_124_),
    .Q(REG1_30_),
    .RN(_060_),
    .SE(test_se),
    .SI(REG1_6_)
  );
  SDFFR_X1 _924_ (
    .CK(CK),
    .D(_125_),
    .Q(REG2_0_),
    .RN(_061_),
    .SE(test_se),
    .SI(REG1_30_)
  );
  SDFFR_X1 _925_ (
    .CK(CK),
    .D(_126_),
    .Q(REG2_1_),
    .RN(_062_),
    .SE(test_se),
    .SI(REG2_0_)
  );
  SDFFR_X1 _926_ (
    .CK(CK),
    .D(_127_),
    .Q(REG2_2_),
    .RN(_063_),
    .SE(test_se),
    .SI(REG2_1_)
  );
  SDFFR_X1 _927_ (
    .CK(CK),
    .D(_128_),
    .Q(REG2_3_),
    .RN(_064_),
    .SE(test_se),
    .SI(REG2_2_)
  );
  SDFFR_X1 _928_ (
    .CK(CK),
    .D(_129_),
    .Q(REG2_4_),
    .RN(_065_),
    .SE(test_se),
    .SI(REG2_3_)
  );
  SDFFR_X1 _929_ (
    .CK(CK),
    .D(_130_),
    .Q(REG2_5_),
    .RN(_066_),
    .SE(test_se),
    .SI(REG2_4_)
  );
  SDFFR_X1 _930_ (
    .CK(CK),
    .D(_131_),
    .Q(REG2_6_),
    .RN(_067_),
    .SE(test_se),
    .SI(REG2_5_)
  );
  SDFFR_X1 _931_ (
    .CK(CK),
    .D(_132_),
    .Q(REG2_30_),
    .RN(_068_),
    .SE(test_se),
    .SI(REG2_6_)
  );
  SDFFR_X1 _932_ (
    .CK(CK),
    .D(_133_),
    .Q(REG3_0_),
    .RN(_069_),
    .SE(test_se),
    .SI(REG2_30_)
  );
  SDFFR_X1 _933_ (
    .CK(CK),
    .D(_134_),
    .Q(REG3_1_),
    .RN(_070_),
    .SE(test_se),
    .SI(REG3_0_)
  );
  SDFFR_X1 _934_ (
    .CK(CK),
    .D(_135_),
    .Q(REG3_2_),
    .RN(_071_),
    .SE(test_se),
    .SI(REG3_1_)
  );
  SDFFR_X1 _935_ (
    .CK(CK),
    .D(_136_),
    .Q(REG3_3_),
    .RN(_072_),
    .SE(test_se),
    .SI(REG3_2_)
  );
  SDFFR_X1 _936_ (
    .CK(CK),
    .D(_137_),
    .Q(REG3_4_),
    .RN(_073_),
    .SE(test_se),
    .SI(REG3_3_)
  );
  SDFFR_X1 _937_ (
    .CK(CK),
    .D(_138_),
    .Q(REG3_5_),
    .RN(_074_),
    .SE(test_se),
    .SI(REG3_4_)
  );
  SDFFR_X1 _938_ (
    .CK(CK),
    .D(_139_),
    .Q(REG3_6_),
    .RN(_075_),
    .SE(test_se),
    .SI(REG3_5_)
  );
  SDFFR_X1 _939_ (
    .CK(CK),
    .D(_140_),
    .Q(REG3_30_),
    .RN(_076_),
    .SE(test_se),
    .SI(REG3_6_)
  );

  wire _const0_;
  wire _const1_;
  LOGIC0_X1 _tie__const0_ (.Z(_const0_));
  LOGIC1_X1 _tie__const1_ (.Z(_const1_));
  assign test_so = REG3_30_;
endmodule