/* Generated by Yosys 0.65 (git sha1 9d0cdb855, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module b04(RESTART, AVERAGE, ENABLE, DATA_IN_0_, DATA_IN_1_, DATA_IN_2_, DATA_IN_3_, DATA_IN_4_, DATA_IN_5_, DATA_IN_6_, DATA_IN_7_, DATA_OUT_0_, DATA_OUT_1_, DATA_OUT_2_, DATA_OUT_3_, DATA_OUT_4_, DATA_OUT_5_, DATA_OUT_6_, DATA_OUT_7_, RESET, CK, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  input RESTART;
  wire RESTART;
  input AVERAGE;
  wire AVERAGE;
  input ENABLE;
  wire ENABLE;
    input DATA_IN_0_;
  input DATA_IN_1_;
  input DATA_IN_2_;
  input DATA_IN_3_;
  input DATA_IN_4_;
  input DATA_IN_5_;
  input DATA_IN_6_;
  input DATA_IN_7_;
    wire DATA_IN_0_;
  wire DATA_IN_1_;
  wire DATA_IN_2_;
  wire DATA_IN_3_;
  wire DATA_IN_4_;
  wire DATA_IN_5_;
  wire DATA_IN_6_;
  wire DATA_IN_7_;
    output DATA_OUT_0_;
  output DATA_OUT_1_;
  output DATA_OUT_2_;
  output DATA_OUT_3_;
  output DATA_OUT_4_;
  output DATA_OUT_5_;
  output DATA_OUT_6_;
  output DATA_OUT_7_;
    wire DATA_OUT_0_;
  wire DATA_OUT_1_;
  wire DATA_OUT_2_;
  wire DATA_OUT_3_;
  wire DATA_OUT_4_;
  wire DATA_OUT_5_;
  wire DATA_OUT_6_;
  wire DATA_OUT_7_;
  input RESET;
  wire RESET;
  input CK;
  wire CK;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire REG1_0_;
  wire REG1_10_;
  wire REG1_1_;
  wire REG1_2_;
  wire REG1_3_;
  wire REG1_4_;
  wire REG1_5_;
  wire REG1_6_;
  wire REG2_0_;
  wire REG2_10_;
  wire REG2_1_;
  wire REG2_2_;
  wire REG2_3_;
  wire REG2_4_;
  wire REG2_5_;
  wire REG2_6_;
  wire REG3_0_;
  wire REG3_10_;
  wire REG3_1_;
  wire REG3_2_;
  wire REG3_3_;
  wire REG3_4_;
  wire REG3_5_;
  wire REG3_6_;
  wire REG4_0_;
  wire REG4_10_;
  wire REG4_1_;
  wire REG4_2_;
  wire REG4_3_;
  wire REG4_4_;
  wire REG4_5_;
  wire REG4_6_;
  wire RLAST_0_;
  wire RLAST_1_;
  wire RLAST_2_;
  wire RLAST_3_;
  wire RLAST_4_;
  wire RLAST_5_;
  wire RLAST_6_;
  wire RLAST_7_;
  wire RMAX_0_;
  wire RMAX_10_;
  wire RMAX_1_;
  wire RMAX_2_;
  wire RMAX_3_;
  wire RMAX_4_;
  wire RMAX_5_;
  wire RMAX_6_;
  wire RMIN_0_;
  wire RMIN_10_;
  wire RMIN_1_;
  wire RMIN_2_;
  wire RMIN_3_;
  wire RMIN_4_;
  wire RMIN_5_;
  wire RMIN_6_;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  INV_X1 _380_ (
    .A(RLAST_7_),
    .ZN(_132_)
  );
  INV_X1 _381_ (
    .A(DATA_OUT_0_),
    .ZN(_133_)
  );
  INV_X1 _382_ (
    .A(REG4_5_),
    .ZN(_134_)
  );
  INV_X1 _383_ (
    .A(RLAST_1_),
    .ZN(_135_)
  );
  INV_X1 _384_ (
    .A(RLAST_2_),
    .ZN(_136_)
  );
  INV_X1 _385_ (
    .A(RLAST_3_),
    .ZN(_137_)
  );
  INV_X1 _386_ (
    .A(RLAST_4_),
    .ZN(_138_)
  );
  INV_X1 _387_ (
    .A(RLAST_5_),
    .ZN(_139_)
  );
  INV_X1 _388_ (
    .A(DATA_IN_0_),
    .ZN(_140_)
  );
  INV_X1 _389_ (
    .A(DATA_IN_1_),
    .ZN(_141_)
  );
  INV_X1 _390_ (
    .A(DATA_IN_2_),
    .ZN(_142_)
  );
  INV_X1 _391_ (
    .A(DATA_IN_3_),
    .ZN(_143_)
  );
  INV_X1 _392_ (
    .A(DATA_IN_4_),
    .ZN(_144_)
  );
  INV_X1 _393_ (
    .A(RMIN_5_),
    .ZN(_145_)
  );
  INV_X1 _394_ (
    .A(RMIN_6_),
    .ZN(_146_)
  );
  INV_X1 _395_ (
    .A(DATA_IN_6_),
    .ZN(_147_)
  );
  INV_X1 _396_ (
    .A(RLAST_6_),
    .ZN(_148_)
  );
  INV_X1 _397_ (
    .A(RLAST_0_),
    .ZN(_149_)
  );
  INV_X1 _398_ (
    .A(RMAX_10_),
    .ZN(_150_)
  );
  INV_X1 _399_ (
    .A(RMAX_0_),
    .ZN(_151_)
  );
  INV_X1 _400_ (
    .A(RMAX_1_),
    .ZN(_152_)
  );
  INV_X1 _401_ (
    .A(RMAX_4_),
    .ZN(_153_)
  );
  INV_X1 _402_ (
    .A(RMAX_5_),
    .ZN(_154_)
  );
  INV_X1 _403_ (
    .A(RMIN_10_),
    .ZN(_155_)
  );
  INV_X1 _404_ (
    .A(ENABLE),
    .ZN(_156_)
  );
  INV_X1 _405_ (
    .A(AVERAGE),
    .ZN(_157_)
  );
  INV_X1 _406_ (
    .A(stato_1_),
    .ZN(_158_)
  );
  INV_X1 _407_ (
    .A(RESET),
    .ZN(_001_)
  );
  NOR2_X1 _408_ (
    .A1(stato_1_),
    .A2(stato_2_),
    .ZN(_159_)
  );
  INV_X1 _409_ (
    .A(_159_),
    .ZN(_000_)
  );
  NAND2_X1 _410_ (
    .A1(_158_),
    .A2(stato_2_),
    .ZN(_160_)
  );
  AOI21_X1 _411_ (
    .A(_159_),
    .B1(stato_1_),
    .B2(_156_),
    .ZN(_161_)
  );
  NAND2_X1 _412_ (
    .A1(DATA_IN_7_),
    .A2(stato_1_),
    .ZN(_162_)
  );
  OAI22_X1 _413_ (
    .A1(_132_),
    .A2(_161_),
    .B1(_162_),
    .B2(_156_),
    .ZN(_131_)
  );
  NAND2_X1 _414_ (
    .A1(DATA_IN_0_),
    .A2(REG4_0_),
    .ZN(_163_)
  );
  NAND2_X1 _415_ (
    .A1(DATA_IN_1_),
    .A2(REG4_1_),
    .ZN(_164_)
  );
  XNOR2_X1 _416_ (
    .A(DATA_IN_1_),
    .B(REG4_1_),
    .ZN(_165_)
  );
  NAND2_X1 _417_ (
    .A1(ENABLE),
    .A2(_157_),
    .ZN(_166_)
  );
  XNOR2_X1 _418_ (
    .A(_163_),
    .B(_165_),
    .ZN(_167_)
  );
  NOR2_X1 _419_ (
    .A1(_156_),
    .A2(_157_),
    .ZN(_168_)
  );
  AOI221_X1 _420_ (
    .A(RESTART),
    .B1(_168_),
    .B2(REG4_0_),
    .C1(_156_),
    .C2(RLAST_0_),
    .ZN(_169_)
  );
  OAI21_X1 _421_ (
    .A(_169_),
    .B1(_167_),
    .B2(_166_),
    .ZN(_170_)
  );
  NAND2_X1 _422_ (
    .A1(RMIN_0_),
    .A2(RMAX_0_),
    .ZN(_171_)
  );
  NAND2_X1 _423_ (
    .A1(RMIN_1_),
    .A2(RMAX_1_),
    .ZN(_172_)
  );
  XNOR2_X1 _424_ (
    .A(RMIN_1_),
    .B(RMAX_1_),
    .ZN(_173_)
  );
  XNOR2_X1 _425_ (
    .A(_171_),
    .B(_173_),
    .ZN(_174_)
  );
  AOI21_X1 _426_ (
    .A(_158_),
    .B1(RESTART),
    .B2(_174_),
    .ZN(_175_)
  );
  NAND2_X1 _427_ (
    .A1(_170_),
    .A2(_175_),
    .ZN(_176_)
  );
  OAI21_X1 _428_ (
    .A(_176_),
    .B1(_000_),
    .B2(_133_),
    .ZN(_130_)
  );
  OAI21_X1 _429_ (
    .A(_164_),
    .B1(_165_),
    .B2(_163_),
    .ZN(_177_)
  );
  AND2_X1 _430_ (
    .A1(DATA_IN_2_),
    .A2(REG4_2_),
    .ZN(_178_)
  );
  XOR2_X1 _431_ (
    .A(DATA_IN_2_),
    .B(REG4_2_),
    .Z(_179_)
  );
  AOI21_X1 _432_ (
    .A(_166_),
    .B1(_177_),
    .B2(_179_),
    .ZN(_180_)
  );
  OAI21_X1 _433_ (
    .A(_180_),
    .B1(_179_),
    .B2(_177_),
    .ZN(_181_)
  );
  AOI221_X1 _434_ (
    .A(RESTART),
    .B1(_168_),
    .B2(REG4_1_),
    .C1(_156_),
    .C2(RLAST_1_),
    .ZN(_182_)
  );
  OAI21_X1 _435_ (
    .A(_172_),
    .B1(_173_),
    .B2(_171_),
    .ZN(_183_)
  );
  AND2_X1 _436_ (
    .A1(RMIN_2_),
    .A2(RMAX_2_),
    .ZN(_184_)
  );
  XOR2_X1 _437_ (
    .A(RMIN_2_),
    .B(RMAX_2_),
    .Z(_185_)
  );
  XNOR2_X1 _438_ (
    .A(_183_),
    .B(_185_),
    .ZN(_186_)
  );
  AOI221_X1 _439_ (
    .A(_158_),
    .B1(_181_),
    .B2(_182_),
    .C1(_186_),
    .C2(RESTART),
    .ZN(_187_)
  );
  AOI21_X1 _440_ (
    .A(_187_),
    .B1(_159_),
    .B2(DATA_OUT_1_),
    .ZN(_188_)
  );
  INV_X1 _441_ (
    .A(_188_),
    .ZN(_129_)
  );
  OR2_X1 _442_ (
    .A1(_158_),
    .A2(RESTART),
    .ZN(_189_)
  );
  AOI21_X1 _443_ (
    .A(_184_),
    .B1(_185_),
    .B2(_183_),
    .ZN(_190_)
  );
  NAND2_X1 _444_ (
    .A1(RMIN_3_),
    .A2(RMAX_3_),
    .ZN(_191_)
  );
  NOR2_X1 _445_ (
    .A1(RMIN_3_),
    .A2(RMAX_3_),
    .ZN(_192_)
  );
  XNOR2_X1 _446_ (
    .A(RMIN_3_),
    .B(RMAX_3_),
    .ZN(_193_)
  );
  XNOR2_X1 _447_ (
    .A(_190_),
    .B(_193_),
    .ZN(_194_)
  );
  AOI21_X1 _448_ (
    .A(_158_),
    .B1(RESTART),
    .B2(_194_),
    .ZN(_195_)
  );
  AOI21_X1 _449_ (
    .A(_178_),
    .B1(_179_),
    .B2(_177_),
    .ZN(_196_)
  );
  NAND2_X1 _450_ (
    .A1(REG4_3_),
    .A2(DATA_IN_3_),
    .ZN(_197_)
  );
  NOR2_X1 _451_ (
    .A1(REG4_3_),
    .A2(DATA_IN_3_),
    .ZN(_198_)
  );
  XNOR2_X1 _452_ (
    .A(REG4_3_),
    .B(DATA_IN_3_),
    .ZN(_199_)
  );
  XNOR2_X1 _453_ (
    .A(_196_),
    .B(_199_),
    .ZN(_200_)
  );
  AOI221_X1 _454_ (
    .A(RESTART),
    .B1(_168_),
    .B2(REG4_2_),
    .C1(_156_),
    .C2(RLAST_2_),
    .ZN(_201_)
  );
  OAI21_X1 _455_ (
    .A(_201_),
    .B1(_200_),
    .B2(_166_),
    .ZN(_202_)
  );
  AOI22_X1 _456_ (
    .A1(DATA_OUT_2_),
    .A2(_159_),
    .B1(_195_),
    .B2(_202_),
    .ZN(_203_)
  );
  INV_X1 _457_ (
    .A(_203_),
    .ZN(_128_)
  );
  AND2_X1 _458_ (
    .A1(REG4_4_),
    .A2(DATA_IN_4_),
    .ZN(_204_)
  );
  XNOR2_X1 _459_ (
    .A(REG4_4_),
    .B(DATA_IN_4_),
    .ZN(_205_)
  );
  OR2_X1 _460_ (
    .A1(_196_),
    .A2(_198_),
    .ZN(_206_)
  );
  AOI211_X1 _461_ (
    .A(_198_),
    .B(_205_),
    .C1(_196_),
    .C2(_197_),
    .ZN(_207_)
  );
  NAND3_X1 _462_ (
    .A1(_197_),
    .A2(_205_),
    .A3(_206_),
    .ZN(_208_)
  );
  NOR2_X1 _463_ (
    .A1(_166_),
    .A2(_207_),
    .ZN(_209_)
  );
  AOI21_X1 _464_ (
    .A(RESTART),
    .B1(_168_),
    .B2(REG4_3_),
    .ZN(_210_)
  );
  OAI21_X1 _465_ (
    .A(_210_),
    .B1(ENABLE),
    .B2(_137_),
    .ZN(_211_)
  );
  AOI21_X1 _466_ (
    .A(_211_),
    .B1(_209_),
    .B2(_208_),
    .ZN(_212_)
  );
  XOR2_X1 _467_ (
    .A(RMIN_4_),
    .B(RMAX_4_),
    .Z(_213_)
  );
  INV_X1 _468_ (
    .A(_213_),
    .ZN(_214_)
  );
  AOI21_X1 _469_ (
    .A(_192_),
    .B1(_191_),
    .B2(_190_),
    .ZN(_215_)
  );
  AOI211_X1 _470_ (
    .A(_192_),
    .B(_214_),
    .C1(_190_),
    .C2(_191_),
    .ZN(_216_)
  );
  XNOR2_X1 _471_ (
    .A(_213_),
    .B(_215_),
    .ZN(_217_)
  );
  AOI211_X1 _472_ (
    .A(_158_),
    .B(_212_),
    .C1(_217_),
    .C2(RESTART),
    .ZN(_218_)
  );
  AOI21_X1 _473_ (
    .A(_218_),
    .B1(_159_),
    .B2(DATA_OUT_3_),
    .ZN(_219_)
  );
  INV_X1 _474_ (
    .A(_219_),
    .ZN(_127_)
  );
  AND2_X1 _475_ (
    .A1(DATA_OUT_4_),
    .A2(_159_),
    .ZN(_220_)
  );
  NOR2_X1 _476_ (
    .A1(_204_),
    .A2(_207_),
    .ZN(_221_)
  );
  NAND2_X1 _477_ (
    .A1(REG4_5_),
    .A2(DATA_IN_5_),
    .ZN(_222_)
  );
  OR2_X1 _478_ (
    .A1(REG4_5_),
    .A2(DATA_IN_5_),
    .ZN(_223_)
  );
  NAND2_X1 _479_ (
    .A1(_222_),
    .A2(_223_),
    .ZN(_224_)
  );
  AOI21_X1 _480_ (
    .A(_166_),
    .B1(_221_),
    .B2(_224_),
    .ZN(_225_)
  );
  OAI21_X1 _481_ (
    .A(_225_),
    .B1(_224_),
    .B2(_221_),
    .ZN(_226_)
  );
  AOI221_X1 _482_ (
    .A(RESTART),
    .B1(_168_),
    .B2(REG4_4_),
    .C1(RLAST_4_),
    .C2(_156_),
    .ZN(_227_)
  );
  AOI21_X1 _483_ (
    .A(_216_),
    .B1(RMAX_4_),
    .B2(RMIN_4_),
    .ZN(_228_)
  );
  NOR2_X1 _484_ (
    .A1(RMIN_5_),
    .A2(RMAX_5_),
    .ZN(_229_)
  );
  XNOR2_X1 _485_ (
    .A(RMIN_5_),
    .B(RMAX_5_),
    .ZN(_230_)
  );
  XNOR2_X1 _486_ (
    .A(_228_),
    .B(_230_),
    .ZN(_231_)
  );
  AOI221_X1 _487_ (
    .A(_158_),
    .B1(_226_),
    .B2(_227_),
    .C1(_231_),
    .C2(RESTART),
    .ZN(_232_)
  );
  OR2_X1 _488_ (
    .A1(_220_),
    .A2(_232_),
    .ZN(_126_)
  );
  NAND2_X1 _489_ (
    .A1(DATA_OUT_5_),
    .A2(_159_),
    .ZN(_233_)
  );
  OAI21_X1 _490_ (
    .A(_223_),
    .B1(_207_),
    .B2(_204_),
    .ZN(_234_)
  );
  XOR2_X1 _491_ (
    .A(REG4_6_),
    .B(DATA_IN_6_),
    .Z(_235_)
  );
  AOI21_X1 _492_ (
    .A(_235_),
    .B1(_234_),
    .B2(_222_),
    .ZN(_236_)
  );
  AND3_X1 _493_ (
    .A1(_222_),
    .A2(_234_),
    .A3(_235_),
    .ZN(_237_)
  );
  OR3_X1 _494_ (
    .A1(AVERAGE),
    .A2(_236_),
    .A3(_237_),
    .ZN(_238_)
  );
  AOI21_X1 _495_ (
    .A(_156_),
    .B1(AVERAGE),
    .B2(_134_),
    .ZN(_239_)
  );
  AOI221_X1 _496_ (
    .A(RESTART),
    .B1(_238_),
    .B2(_239_),
    .C1(_156_),
    .C2(RLAST_5_),
    .ZN(_240_)
  );
  AOI221_X1 _497_ (
    .A(_216_),
    .B1(RMAX_5_),
    .B2(RMIN_5_),
    .C1(RMIN_4_),
    .C2(RMAX_4_),
    .ZN(_241_)
  );
  XOR2_X1 _498_ (
    .A(RMIN_6_),
    .B(RMAX_6_),
    .Z(_242_)
  );
  NOR3_X1 _499_ (
    .A1(_229_),
    .A2(_241_),
    .A3(_242_),
    .ZN(_243_)
  );
  OAI21_X1 _500_ (
    .A(_242_),
    .B1(_241_),
    .B2(_229_),
    .ZN(_244_)
  );
  NAND2_X1 _501_ (
    .A1(RESTART),
    .A2(_244_),
    .ZN(_245_)
  );
  OAI21_X1 _502_ (
    .A(stato_1_),
    .B1(_243_),
    .B2(_245_),
    .ZN(_246_)
  );
  OAI21_X1 _503_ (
    .A(_233_),
    .B1(_240_),
    .B2(_246_),
    .ZN(_125_)
  );
  NAND2_X1 _504_ (
    .A1(DATA_OUT_6_),
    .A2(_159_),
    .ZN(_247_)
  );
  AOI22_X1 _505_ (
    .A1(RLAST_6_),
    .A2(_156_),
    .B1(_168_),
    .B2(REG4_6_),
    .ZN(_248_)
  );
  OAI21_X1 _506_ (
    .A(_247_),
    .B1(_248_),
    .B2(_189_),
    .ZN(_124_)
  );
  AOI22_X1 _507_ (
    .A1(REG2_0_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_0_),
    .ZN(_249_)
  );
  INV_X1 _508_ (
    .A(_249_),
    .ZN(_123_)
  );
  AOI22_X1 _509_ (
    .A1(REG2_1_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_1_),
    .ZN(_250_)
  );
  INV_X1 _510_ (
    .A(_250_),
    .ZN(_122_)
  );
  AOI22_X1 _511_ (
    .A1(REG2_2_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_2_),
    .ZN(_251_)
  );
  INV_X1 _512_ (
    .A(_251_),
    .ZN(_121_)
  );
  AOI22_X1 _513_ (
    .A1(REG2_3_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_3_),
    .ZN(_252_)
  );
  INV_X1 _514_ (
    .A(_252_),
    .ZN(_120_)
  );
  AOI22_X1 _515_ (
    .A1(REG2_4_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_4_),
    .ZN(_253_)
  );
  INV_X1 _516_ (
    .A(_253_),
    .ZN(_119_)
  );
  AOI22_X1 _517_ (
    .A1(REG2_5_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_5_),
    .ZN(_254_)
  );
  INV_X1 _518_ (
    .A(_254_),
    .ZN(_118_)
  );
  AOI22_X1 _519_ (
    .A1(REG2_6_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_6_),
    .ZN(_255_)
  );
  INV_X1 _520_ (
    .A(_255_),
    .ZN(_117_)
  );
  AOI22_X1 _521_ (
    .A1(REG3_3_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_3_),
    .ZN(_256_)
  );
  INV_X1 _522_ (
    .A(_256_),
    .ZN(_116_)
  );
  AOI22_X1 _523_ (
    .A1(REG3_4_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_4_),
    .ZN(_257_)
  );
  INV_X1 _524_ (
    .A(_257_),
    .ZN(_115_)
  );
  AOI22_X1 _525_ (
    .A1(REG3_5_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_5_),
    .ZN(_258_)
  );
  INV_X1 _526_ (
    .A(_258_),
    .ZN(_114_)
  );
  AOI22_X1 _527_ (
    .A1(REG3_6_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_6_),
    .ZN(_259_)
  );
  INV_X1 _528_ (
    .A(_259_),
    .ZN(_113_)
  );
  NAND3_X1 _529_ (
    .A1(DATA_IN_1_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_260_)
  );
  OAI21_X1 _530_ (
    .A(_260_),
    .B1(_161_),
    .B2(_135_),
    .ZN(_112_)
  );
  NAND3_X1 _531_ (
    .A1(DATA_IN_2_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_261_)
  );
  OAI21_X1 _532_ (
    .A(_261_),
    .B1(_161_),
    .B2(_136_),
    .ZN(_111_)
  );
  AOI22_X1 _533_ (
    .A1(REG1_10_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_10_),
    .ZN(_262_)
  );
  INV_X1 _534_ (
    .A(_262_),
    .ZN(_110_)
  );
  NAND3_X1 _535_ (
    .A1(DATA_IN_3_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_263_)
  );
  OAI21_X1 _536_ (
    .A(_263_),
    .B1(_161_),
    .B2(_137_),
    .ZN(_109_)
  );
  NAND3_X1 _537_ (
    .A1(DATA_IN_4_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_264_)
  );
  OAI21_X1 _538_ (
    .A(_264_),
    .B1(_161_),
    .B2(_138_),
    .ZN(_108_)
  );
  NAND3_X1 _539_ (
    .A1(DATA_IN_5_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_265_)
  );
  OAI21_X1 _540_ (
    .A(_265_),
    .B1(_161_),
    .B2(_139_),
    .ZN(_107_)
  );
  AOI22_X1 _541_ (
    .A1(REG3_10_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_10_),
    .ZN(_266_)
  );
  INV_X1 _542_ (
    .A(_266_),
    .ZN(_106_)
  );
  NAND2_X1 _543_ (
    .A1(DATA_OUT_7_),
    .A2(_159_),
    .ZN(_267_)
  );
  AOI22_X1 _544_ (
    .A1(RLAST_7_),
    .A2(_156_),
    .B1(_168_),
    .B2(REG4_10_),
    .ZN(_268_)
  );
  OAI21_X1 _545_ (
    .A(_267_),
    .B1(_268_),
    .B2(_189_),
    .ZN(_105_)
  );
  AOI22_X1 _546_ (
    .A1(DATA_IN_0_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_0_),
    .ZN(_269_)
  );
  INV_X1 _547_ (
    .A(_269_),
    .ZN(_104_)
  );
  AOI22_X1 _548_ (
    .A1(DATA_IN_0_),
    .A2(_151_),
    .B1(_152_),
    .B2(DATA_IN_1_),
    .ZN(_270_)
  );
  AOI221_X1 _549_ (
    .A(_270_),
    .B1(RMAX_2_),
    .B2(_142_),
    .C1(_141_),
    .C2(RMAX_1_),
    .ZN(_271_)
  );
  OAI22_X1 _550_ (
    .A1(_142_),
    .A2(RMAX_2_),
    .B1(RMAX_3_),
    .B2(_143_),
    .ZN(_272_)
  );
  AOI22_X1 _551_ (
    .A1(_143_),
    .A2(RMAX_3_),
    .B1(RMAX_4_),
    .B2(_144_),
    .ZN(_273_)
  );
  OAI21_X1 _552_ (
    .A(_273_),
    .B1(_272_),
    .B2(_271_),
    .ZN(_274_)
  );
  AOI22_X1 _553_ (
    .A1(DATA_IN_4_),
    .A2(_153_),
    .B1(_154_),
    .B2(DATA_IN_5_),
    .ZN(_275_)
  );
  NOR2_X1 _554_ (
    .A1(DATA_IN_5_),
    .A2(_154_),
    .ZN(_276_)
  );
  AOI221_X1 _555_ (
    .A(_276_),
    .B1(_275_),
    .B2(_274_),
    .C1(_147_),
    .C2(RMAX_6_),
    .ZN(_277_)
  );
  OAI221_X1 _556_ (
    .A(stato_1_),
    .B1(DATA_IN_7_),
    .B2(_150_),
    .C1(_147_),
    .C2(RMAX_6_),
    .ZN(_278_)
  );
  OAI22_X1 _557_ (
    .A1(RMAX_10_),
    .A2(_162_),
    .B1(_277_),
    .B2(_278_),
    .ZN(_279_)
  );
  NOR2_X1 _558_ (
    .A1(RMIN_2_),
    .A2(_142_),
    .ZN(_280_)
  );
  NAND2_X1 _559_ (
    .A1(RMIN_1_),
    .A2(_141_),
    .ZN(_281_)
  );
  OAI211_X1 _560_ (
    .A(RMIN_0_),
    .B(_140_),
    .C1(RMIN_1_),
    .C2(_141_),
    .ZN(_282_)
  );
  AOI21_X1 _561_ (
    .A(_280_),
    .B1(_281_),
    .B2(_282_),
    .ZN(_283_)
  );
  AOI221_X1 _562_ (
    .A(_283_),
    .B1(_143_),
    .B2(RMIN_3_),
    .C1(RMIN_2_),
    .C2(_142_),
    .ZN(_284_)
  );
  OAI22_X1 _563_ (
    .A1(RMIN_3_),
    .A2(_143_),
    .B1(RMIN_4_),
    .B2(_144_),
    .ZN(_285_)
  );
  NAND2_X1 _564_ (
    .A1(RMIN_4_),
    .A2(_144_),
    .ZN(_286_)
  );
  OAI221_X1 _565_ (
    .A(_286_),
    .B1(_285_),
    .B2(_284_),
    .C1(_145_),
    .C2(DATA_IN_5_),
    .ZN(_287_)
  );
  AOI22_X1 _566_ (
    .A1(_145_),
    .A2(DATA_IN_5_),
    .B1(_146_),
    .B2(DATA_IN_6_),
    .ZN(_288_)
  );
  AOI222_X1 _567_ (
    .A1(RMIN_6_),
    .A2(_147_),
    .B1(DATA_IN_7_),
    .B2(_155_),
    .C1(_287_),
    .C2(_288_),
    .ZN(_289_)
  );
  OAI21_X1 _568_ (
    .A(_279_),
    .B1(_155_),
    .B2(DATA_IN_7_),
    .ZN(_290_)
  );
  OAI21_X1 _569_ (
    .A(_160_),
    .B1(_289_),
    .B2(_290_),
    .ZN(_291_)
  );
  MUX2_X1 _570_ (
    .A(RMIN_0_),
    .B(DATA_IN_0_),
    .S(_291_),
    .Z(_103_)
  );
  MUX2_X1 _571_ (
    .A(RMIN_1_),
    .B(DATA_IN_1_),
    .S(_291_),
    .Z(_102_)
  );
  MUX2_X1 _572_ (
    .A(RMIN_2_),
    .B(DATA_IN_2_),
    .S(_291_),
    .Z(_101_)
  );
  MUX2_X1 _573_ (
    .A(RMIN_3_),
    .B(DATA_IN_3_),
    .S(_291_),
    .Z(_100_)
  );
  MUX2_X1 _574_ (
    .A(RMIN_4_),
    .B(DATA_IN_4_),
    .S(_291_),
    .Z(_099_)
  );
  MUX2_X1 _575_ (
    .A(RMIN_5_),
    .B(DATA_IN_5_),
    .S(_291_),
    .Z(_098_)
  );
  MUX2_X1 _576_ (
    .A(RMIN_6_),
    .B(DATA_IN_6_),
    .S(_291_),
    .Z(_097_)
  );
  AOI22_X1 _577_ (
    .A1(DATA_IN_1_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_1_),
    .ZN(_292_)
  );
  INV_X1 _578_ (
    .A(_292_),
    .ZN(_096_)
  );
  AOI22_X1 _579_ (
    .A1(DATA_IN_2_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_2_),
    .ZN(_293_)
  );
  INV_X1 _580_ (
    .A(_293_),
    .ZN(_095_)
  );
  AOI22_X1 _581_ (
    .A1(DATA_IN_3_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_3_),
    .ZN(_294_)
  );
  INV_X1 _582_ (
    .A(_294_),
    .ZN(_094_)
  );
  AOI22_X1 _583_ (
    .A1(DATA_IN_4_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_4_),
    .ZN(_295_)
  );
  INV_X1 _584_ (
    .A(_295_),
    .ZN(_093_)
  );
  AOI22_X1 _585_ (
    .A1(DATA_IN_5_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_5_),
    .ZN(_296_)
  );
  INV_X1 _586_ (
    .A(_296_),
    .ZN(_092_)
  );
  AOI22_X1 _587_ (
    .A1(DATA_IN_6_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_6_),
    .ZN(_297_)
  );
  INV_X1 _588_ (
    .A(_297_),
    .ZN(_091_)
  );
  NAND3_X1 _589_ (
    .A1(DATA_IN_6_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_298_)
  );
  OAI21_X1 _590_ (
    .A(_298_),
    .B1(_161_),
    .B2(_148_),
    .ZN(_090_)
  );
  AOI22_X1 _591_ (
    .A1(DATA_IN_7_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG1_10_),
    .ZN(_299_)
  );
  INV_X1 _592_ (
    .A(_299_),
    .ZN(_089_)
  );
  NAND3_X1 _593_ (
    .A1(DATA_IN_0_),
    .A2(ENABLE),
    .A3(stato_1_),
    .ZN(_300_)
  );
  OAI21_X1 _594_ (
    .A(_300_),
    .B1(_161_),
    .B2(_149_),
    .ZN(_088_)
  );
  NOR2_X1 _595_ (
    .A1(_159_),
    .A2(_279_),
    .ZN(_301_)
  );
  MUX2_X1 _596_ (
    .A(RMAX_10_),
    .B(DATA_IN_7_),
    .S(_301_),
    .Z(_087_)
  );
  AOI22_X1 _597_ (
    .A1(REG2_10_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG3_10_),
    .ZN(_302_)
  );
  INV_X1 _598_ (
    .A(_302_),
    .ZN(_086_)
  );
  AOI22_X1 _599_ (
    .A1(REG3_0_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_0_),
    .ZN(_303_)
  );
  INV_X1 _600_ (
    .A(_303_),
    .ZN(_085_)
  );
  AOI22_X1 _601_ (
    .A1(REG3_1_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_1_),
    .ZN(_304_)
  );
  INV_X1 _602_ (
    .A(_304_),
    .ZN(_084_)
  );
  MUX2_X1 _603_ (
    .A(RMAX_0_),
    .B(DATA_IN_0_),
    .S(_301_),
    .Z(_083_)
  );
  MUX2_X1 _604_ (
    .A(RMAX_1_),
    .B(DATA_IN_1_),
    .S(_301_),
    .Z(_082_)
  );
  MUX2_X1 _605_ (
    .A(RMAX_2_),
    .B(DATA_IN_2_),
    .S(_301_),
    .Z(_081_)
  );
  MUX2_X1 _606_ (
    .A(RMAX_3_),
    .B(DATA_IN_3_),
    .S(_301_),
    .Z(_080_)
  );
  MUX2_X1 _607_ (
    .A(RMAX_4_),
    .B(DATA_IN_4_),
    .S(_301_),
    .Z(_079_)
  );
  MUX2_X1 _608_ (
    .A(RMAX_5_),
    .B(DATA_IN_5_),
    .S(_301_),
    .Z(_078_)
  );
  AOI22_X1 _609_ (
    .A1(REG1_0_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_0_),
    .ZN(_305_)
  );
  INV_X1 _610_ (
    .A(_305_),
    .ZN(_077_)
  );
  AOI22_X1 _611_ (
    .A1(REG1_1_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_1_),
    .ZN(_306_)
  );
  INV_X1 _612_ (
    .A(_306_),
    .ZN(_076_)
  );
  AOI22_X1 _613_ (
    .A1(REG1_2_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_2_),
    .ZN(_307_)
  );
  INV_X1 _614_ (
    .A(_307_),
    .ZN(_075_)
  );
  AOI22_X1 _615_ (
    .A1(REG1_3_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_3_),
    .ZN(_308_)
  );
  INV_X1 _616_ (
    .A(_308_),
    .ZN(_074_)
  );
  AOI22_X1 _617_ (
    .A1(REG1_4_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_4_),
    .ZN(_309_)
  );
  INV_X1 _618_ (
    .A(_309_),
    .ZN(_073_)
  );
  AOI22_X1 _619_ (
    .A1(REG1_5_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_5_),
    .ZN(_310_)
  );
  INV_X1 _620_ (
    .A(_310_),
    .ZN(_072_)
  );
  AOI22_X1 _621_ (
    .A1(REG1_6_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG2_6_),
    .ZN(_311_)
  );
  INV_X1 _622_ (
    .A(_311_),
    .ZN(_071_)
  );
  MUX2_X1 _623_ (
    .A(RMAX_6_),
    .B(DATA_IN_6_),
    .S(_301_),
    .Z(_070_)
  );
  AOI22_X1 _624_ (
    .A1(REG3_2_),
    .A2(stato_1_),
    .B1(_159_),
    .B2(REG4_2_),
    .ZN(_312_)
  );
  INV_X1 _625_ (
    .A(_312_),
    .ZN(_069_)
  );
  MUX2_X1 _626_ (
    .A(RMIN_10_),
    .B(DATA_IN_7_),
    .S(_291_),
    .Z(_068_)
  );
  INV_X1 _627_ (
    .A(RESET),
    .ZN(_002_)
  );
  INV_X1 _628_ (
    .A(RESET),
    .ZN(_003_)
  );
  INV_X1 _629_ (
    .A(RESET),
    .ZN(_004_)
  );
  INV_X1 _630_ (
    .A(RESET),
    .ZN(_005_)
  );
  INV_X1 _631_ (
    .A(RESET),
    .ZN(_006_)
  );
  INV_X1 _632_ (
    .A(RESET),
    .ZN(_007_)
  );
  INV_X1 _633_ (
    .A(RESET),
    .ZN(_008_)
  );
  INV_X1 _634_ (
    .A(RESET),
    .ZN(_009_)
  );
  INV_X1 _635_ (
    .A(RESET),
    .ZN(_010_)
  );
  INV_X1 _636_ (
    .A(RESET),
    .ZN(_011_)
  );
  INV_X1 _637_ (
    .A(RESET),
    .ZN(_012_)
  );
  INV_X1 _638_ (
    .A(RESET),
    .ZN(_013_)
  );
  INV_X1 _639_ (
    .A(RESET),
    .ZN(_014_)
  );
  INV_X1 _640_ (
    .A(RESET),
    .ZN(_015_)
  );
  INV_X1 _641_ (
    .A(RESET),
    .ZN(_016_)
  );
  INV_X1 _642_ (
    .A(RESET),
    .ZN(_017_)
  );
  INV_X1 _643_ (
    .A(RESET),
    .ZN(_018_)
  );
  INV_X1 _644_ (
    .A(RESET),
    .ZN(_019_)
  );
  INV_X1 _645_ (
    .A(RESET),
    .ZN(_020_)
  );
  INV_X1 _646_ (
    .A(RESET),
    .ZN(_021_)
  );
  INV_X1 _647_ (
    .A(RESET),
    .ZN(_022_)
  );
  INV_X1 _648_ (
    .A(RESET),
    .ZN(_023_)
  );
  INV_X1 _649_ (
    .A(RESET),
    .ZN(_024_)
  );
  INV_X1 _650_ (
    .A(RESET),
    .ZN(_025_)
  );
  INV_X1 _651_ (
    .A(RESET),
    .ZN(_026_)
  );
  INV_X1 _652_ (
    .A(RESET),
    .ZN(_027_)
  );
  INV_X1 _653_ (
    .A(RESET),
    .ZN(_028_)
  );
  INV_X1 _654_ (
    .A(RESET),
    .ZN(_029_)
  );
  INV_X1 _655_ (
    .A(RESET),
    .ZN(_030_)
  );
  INV_X1 _656_ (
    .A(RESET),
    .ZN(_031_)
  );
  INV_X1 _657_ (
    .A(RESET),
    .ZN(_032_)
  );
  INV_X1 _658_ (
    .A(RESET),
    .ZN(_033_)
  );
  INV_X1 _659_ (
    .A(RESET),
    .ZN(_034_)
  );
  INV_X1 _660_ (
    .A(RESET),
    .ZN(_035_)
  );
  INV_X1 _661_ (
    .A(RESET),
    .ZN(_036_)
  );
  INV_X1 _662_ (
    .A(RESET),
    .ZN(_037_)
  );
  INV_X1 _663_ (
    .A(RESET),
    .ZN(_038_)
  );
  INV_X1 _664_ (
    .A(RESET),
    .ZN(_039_)
  );
  INV_X1 _665_ (
    .A(RESET),
    .ZN(_040_)
  );
  INV_X1 _666_ (
    .A(RESET),
    .ZN(_041_)
  );
  INV_X1 _667_ (
    .A(RESET),
    .ZN(_042_)
  );
  INV_X1 _668_ (
    .A(RESET),
    .ZN(_043_)
  );
  INV_X1 _669_ (
    .A(RESET),
    .ZN(_044_)
  );
  INV_X1 _670_ (
    .A(RESET),
    .ZN(_045_)
  );
  INV_X1 _671_ (
    .A(RESET),
    .ZN(_046_)
  );
  INV_X1 _672_ (
    .A(RESET),
    .ZN(_047_)
  );
  INV_X1 _673_ (
    .A(RESET),
    .ZN(_048_)
  );
  INV_X1 _674_ (
    .A(RESET),
    .ZN(_049_)
  );
  INV_X1 _675_ (
    .A(RESET),
    .ZN(_050_)
  );
  INV_X1 _676_ (
    .A(RESET),
    .ZN(_051_)
  );
  INV_X1 _677_ (
    .A(RESET),
    .ZN(_052_)
  );
  INV_X1 _678_ (
    .A(RESET),
    .ZN(_053_)
  );
  INV_X1 _679_ (
    .A(RESET),
    .ZN(_054_)
  );
  INV_X1 _680_ (
    .A(RESET),
    .ZN(_055_)
  );
  INV_X1 _681_ (
    .A(RESET),
    .ZN(_056_)
  );
  INV_X1 _682_ (
    .A(RESET),
    .ZN(_057_)
  );
  INV_X1 _683_ (
    .A(RESET),
    .ZN(_058_)
  );
  INV_X1 _684_ (
    .A(RESET),
    .ZN(_059_)
  );
  INV_X1 _685_ (
    .A(RESET),
    .ZN(_060_)
  );
  INV_X1 _686_ (
    .A(RESET),
    .ZN(_061_)
  );
  INV_X1 _687_ (
    .A(RESET),
    .ZN(_062_)
  );
  INV_X1 _688_ (
    .A(RESET),
    .ZN(_063_)
  );
  INV_X1 _689_ (
    .A(RESET),
    .ZN(_064_)
  );
  INV_X1 _690_ (
    .A(RESET),
    .ZN(_065_)
  );
  INV_X1 _691_ (
    .A(RESET),
    .ZN(_066_)
  );
  INV_X1 _692_ (
    .A(RESET),
    .ZN(_067_)
  );
  SDFFR_X1 _693_ (
    .CK(CK),
    .D(_077_),
    .Q(REG2_0_),
    .RN(_010_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _694_ (
    .CK(CK),
    .D(_076_),
    .Q(REG2_1_),
    .RN(_009_),
    .SE(test_se),
    .SI(REG2_0_)
  );
  SDFFR_X1 _695_ (
    .CK(CK),
    .D(_075_),
    .Q(REG2_2_),
    .RN(_008_),
    .SE(test_se),
    .SI(REG2_1_)
  );
  SDFFR_X1 _696_ (
    .CK(CK),
    .D(_074_),
    .Q(REG2_3_),
    .RN(_007_),
    .SE(test_se),
    .SI(REG2_2_)
  );
  SDFFR_X1 _697_ (
    .CK(CK),
    .D(_073_),
    .Q(REG2_4_),
    .RN(_006_),
    .SE(test_se),
    .SI(REG2_3_)
  );
  SDFFR_X1 _698_ (
    .CK(CK),
    .D(_072_),
    .Q(REG2_5_),
    .RN(_005_),
    .SE(test_se),
    .SI(REG2_4_)
  );
  SDFFR_X1 _699_ (
    .CK(CK),
    .D(_071_),
    .Q(REG2_6_),
    .RN(_004_),
    .SE(test_se),
    .SI(REG2_5_)
  );
  SDFFR_X1 _700_ (
    .CK(CK),
    .D(_110_),
    .Q(REG2_10_),
    .RN(_046_),
    .SE(test_se),
    .SI(REG2_6_)
  );
  SDFFR_X1 _701_ (
    .CK(CK),
    .D(_103_),
    .Q(RMIN_0_),
    .RN(_039_),
    .SE(test_se),
    .SI(REG2_10_)
  );
  SDFFR_X1 _702_ (
    .CK(CK),
    .D(_102_),
    .Q(RMIN_1_),
    .RN(_038_),
    .SE(test_se),
    .SI(RMIN_0_)
  );
  SDFFR_X1 _703_ (
    .CK(CK),
    .D(_101_),
    .Q(RMIN_2_),
    .RN(_037_),
    .SE(test_se),
    .SI(RMIN_1_)
  );
  SDFFR_X1 _704_ (
    .CK(CK),
    .D(_100_),
    .Q(RMIN_3_),
    .RN(_036_),
    .SE(test_se),
    .SI(RMIN_2_)
  );
  SDFFR_X1 _705_ (
    .CK(CK),
    .D(_099_),
    .Q(RMIN_4_),
    .RN(_035_),
    .SE(test_se),
    .SI(RMIN_3_)
  );
  SDFFR_X1 _706_ (
    .CK(CK),
    .D(_098_),
    .Q(RMIN_5_),
    .RN(_034_),
    .SE(test_se),
    .SI(RMIN_4_)
  );
  SDFFR_X1 _707_ (
    .CK(CK),
    .D(_097_),
    .Q(RMIN_6_),
    .RN(_033_),
    .SE(test_se),
    .SI(RMIN_5_)
  );
  SDFFR_X1 _708_ (
    .CK(CK),
    .D(_068_),
    .Q(RMIN_10_),
    .RN(_001_),
    .SE(test_se),
    .SI(RMIN_6_)
  );
  SDFFR_X1 _709_ (
    .CK(CK),
    .D(_130_),
    .Q(DATA_OUT_0_),
    .RN(_066_),
    .SE(test_se),
    .SI(RMIN_10_)
  );
  SDFFR_X1 _710_ (
    .CK(CK),
    .D(_129_),
    .Q(DATA_OUT_1_),
    .RN(_065_),
    .SE(test_se),
    .SI(DATA_OUT_0_)
  );
  SDFFR_X1 _711_ (
    .CK(CK),
    .D(_128_),
    .Q(DATA_OUT_2_),
    .RN(_064_),
    .SE(test_se),
    .SI(DATA_OUT_1_)
  );
  SDFFR_X1 _712_ (
    .CK(CK),
    .D(_127_),
    .Q(DATA_OUT_3_),
    .RN(_063_),
    .SE(test_se),
    .SI(DATA_OUT_2_)
  );
  SDFFR_X1 _713_ (
    .CK(CK),
    .D(_126_),
    .Q(DATA_OUT_4_),
    .RN(_062_),
    .SE(test_se),
    .SI(DATA_OUT_3_)
  );
  SDFFR_X1 _714_ (
    .CK(CK),
    .D(_125_),
    .Q(DATA_OUT_5_),
    .RN(_061_),
    .SE(test_se),
    .SI(DATA_OUT_4_)
  );
  SDFFR_X1 _715_ (
    .CK(CK),
    .D(_124_),
    .Q(DATA_OUT_6_),
    .RN(_060_),
    .SE(test_se),
    .SI(DATA_OUT_5_)
  );
  SDFFR_X1 _716_ (
    .CK(CK),
    .D(_105_),
    .Q(DATA_OUT_7_),
    .RN(_041_),
    .SE(test_se),
    .SI(DATA_OUT_6_)
  );
  SDFFR_X1 _717_ (
    .CK(CK),
    .D(_123_),
    .Q(REG3_0_),
    .RN(_059_),
    .SE(test_se),
    .SI(DATA_OUT_7_)
  );
  SDFFR_X1 _718_ (
    .CK(CK),
    .D(_122_),
    .Q(REG3_1_),
    .RN(_058_),
    .SE(test_se),
    .SI(REG3_0_)
  );
  SDFFR_X1 _719_ (
    .CK(CK),
    .D(_121_),
    .Q(REG3_2_),
    .RN(_057_),
    .SE(test_se),
    .SI(REG3_1_)
  );
  SDFFR_X1 _720_ (
    .CK(CK),
    .D(_120_),
    .Q(REG3_3_),
    .RN(_056_),
    .SE(test_se),
    .SI(REG3_2_)
  );
  SDFFR_X1 _721_ (
    .CK(CK),
    .D(_119_),
    .Q(REG3_4_),
    .RN(_055_),
    .SE(test_se),
    .SI(REG3_3_)
  );
  SDFFR_X1 _722_ (
    .CK(CK),
    .D(_118_),
    .Q(REG3_5_),
    .RN(_054_),
    .SE(test_se),
    .SI(REG3_4_)
  );
  SDFFR_X1 _723_ (
    .CK(CK),
    .D(_117_),
    .Q(REG3_6_),
    .RN(_053_),
    .SE(test_se),
    .SI(REG3_5_)
  );
  SDFFR_X1 _724_ (
    .CK(CK),
    .D(_086_),
    .Q(REG3_10_),
    .RN(_019_),
    .SE(test_se),
    .SI(REG3_6_)
  );
  SDFFR_X1 _725_ (
    .CK(CK),
    .D(_083_),
    .Q(RMAX_0_),
    .RN(_016_),
    .SE(test_se),
    .SI(REG3_10_)
  );
  SDFFR_X1 _726_ (
    .CK(CK),
    .D(_082_),
    .Q(RMAX_1_),
    .RN(_015_),
    .SE(test_se),
    .SI(RMAX_0_)
  );
  SDFFR_X1 _727_ (
    .CK(CK),
    .D(_081_),
    .Q(RMAX_2_),
    .RN(_014_),
    .SE(test_se),
    .SI(RMAX_1_)
  );
  SDFFR_X1 _728_ (
    .CK(CK),
    .D(_080_),
    .Q(RMAX_3_),
    .RN(_013_),
    .SE(test_se),
    .SI(RMAX_2_)
  );
  SDFFR_X1 _729_ (
    .CK(CK),
    .D(_079_),
    .Q(RMAX_4_),
    .RN(_012_),
    .SE(test_se),
    .SI(RMAX_3_)
  );
  SDFFR_X1 _730_ (
    .CK(CK),
    .D(_078_),
    .Q(RMAX_5_),
    .RN(_011_),
    .SE(test_se),
    .SI(RMAX_4_)
  );
  SDFFR_X1 _731_ (
    .CK(CK),
    .D(_070_),
    .Q(RMAX_6_),
    .RN(_003_),
    .SE(test_se),
    .SI(RMAX_5_)
  );
  SDFFR_X1 _732_ (
    .CK(CK),
    .D(_087_),
    .Q(RMAX_10_),
    .RN(_020_),
    .SE(test_se),
    .SI(RMAX_6_)
  );
  SDFFR_X1 _733_ (
    .CK(CK),
    .D(_085_),
    .Q(REG4_0_),
    .RN(_018_),
    .SE(test_se),
    .SI(RMAX_10_)
  );
  SDFFR_X1 _734_ (
    .CK(CK),
    .D(_084_),
    .Q(REG4_1_),
    .RN(_017_),
    .SE(test_se),
    .SI(REG4_0_)
  );
  SDFFR_X1 _735_ (
    .CK(CK),
    .D(_069_),
    .Q(REG4_2_),
    .RN(_002_),
    .SE(test_se),
    .SI(REG4_1_)
  );
  SDFFR_X1 _736_ (
    .CK(CK),
    .D(_116_),
    .Q(REG4_3_),
    .RN(_052_),
    .SE(test_se),
    .SI(REG4_2_)
  );
  SDFFR_X1 _737_ (
    .CK(CK),
    .D(_115_),
    .Q(REG4_4_),
    .RN(_051_),
    .SE(test_se),
    .SI(REG4_3_)
  );
  SDFFR_X1 _738_ (
    .CK(CK),
    .D(_114_),
    .Q(REG4_5_),
    .RN(_050_),
    .SE(test_se),
    .SI(REG4_4_)
  );
  SDFFR_X1 _739_ (
    .CK(CK),
    .D(_113_),
    .Q(REG4_6_),
    .RN(_049_),
    .SE(test_se),
    .SI(REG4_5_)
  );
  SDFFR_X1 _740_ (
    .CK(CK),
    .D(_106_),
    .Q(REG4_10_),
    .RN(_042_),
    .SE(test_se),
    .SI(REG4_6_)
  );
  SDFFR_X1 _741_ (
    .CK(CK),
    .D(_104_),
    .Q(REG1_0_),
    .RN(_040_),
    .SE(test_se),
    .SI(REG4_10_)
  );
  SDFFR_X1 _742_ (
    .CK(CK),
    .D(_096_),
    .Q(REG1_1_),
    .RN(_032_),
    .SE(test_se),
    .SI(REG1_0_)
  );
  SDFFR_X1 _743_ (
    .CK(CK),
    .D(_095_),
    .Q(REG1_2_),
    .RN(_031_),
    .SE(test_se),
    .SI(REG1_1_)
  );
  SDFFR_X1 _744_ (
    .CK(CK),
    .D(_094_),
    .Q(REG1_3_),
    .RN(_030_),
    .SE(test_se),
    .SI(REG1_2_)
  );
  SDFFR_X1 _745_ (
    .CK(CK),
    .D(_093_),
    .Q(REG1_4_),
    .RN(_029_),
    .SE(test_se),
    .SI(REG1_3_)
  );
  SDFFR_X1 _746_ (
    .CK(CK),
    .D(_092_),
    .Q(REG1_5_),
    .RN(_028_),
    .SE(test_se),
    .SI(REG1_4_)
  );
  SDFFR_X1 _747_ (
    .CK(CK),
    .D(_091_),
    .Q(REG1_6_),
    .RN(_026_),
    .SE(test_se),
    .SI(REG1_5_)
  );
  SDFFR_X1 _748_ (
    .CK(CK),
    .D(_089_),
    .Q(REG1_10_),
    .RN(_022_),
    .SE(test_se),
    .SI(REG1_6_)
  );
  SDFFR_X1 _749_ (
    .CK(CK),
    .D(_088_),
    .Q(RLAST_0_),
    .RN(_021_),
    .SE(test_se),
    .SI(REG1_10_)
  );
  SDFFR_X1 _750_ (
    .CK(CK),
    .D(_112_),
    .Q(RLAST_1_),
    .RN(_048_),
    .SE(test_se),
    .SI(RLAST_0_)
  );
  SDFFR_X1 _751_ (
    .CK(CK),
    .D(_111_),
    .Q(RLAST_2_),
    .RN(_047_),
    .SE(test_se),
    .SI(RLAST_1_)
  );
  SDFFR_X1 _752_ (
    .CK(CK),
    .D(_109_),
    .Q(RLAST_3_),
    .RN(_045_),
    .SE(test_se),
    .SI(RLAST_2_)
  );
  SDFFR_X1 _753_ (
    .CK(CK),
    .D(_108_),
    .Q(RLAST_4_),
    .RN(_044_),
    .SE(test_se),
    .SI(RLAST_3_)
  );
  SDFFR_X1 _754_ (
    .CK(CK),
    .D(_107_),
    .Q(RLAST_5_),
    .RN(_043_),
    .SE(test_se),
    .SI(RLAST_4_)
  );
  SDFFR_X1 _755_ (
    .CK(CK),
    .D(_090_),
    .Q(RLAST_6_),
    .RN(_025_),
    .SE(test_se),
    .SI(RLAST_5_)
  );
  SDFFR_X1 _756_ (
    .CK(CK),
    .D(_131_),
    .Q(RLAST_7_),
    .RN(_067_),
    .SE(test_se),
    .SI(RLAST_6_)
  );
  SDFFS_X1 _757_ (
    .CK(CK),
    .D(_const0_),
    .Q(stato_0_),
    .SN(_024_),
    .SE(test_se),
    .SI(RLAST_7_)
  );
  SDFFR_X1 _758_ (
    .CK(CK),
    .D(_000_),
    .Q(stato_1_),
    .RN(_023_),
    .SE(test_se),
    .SI(stato_0_)
  );
  SDFFR_X1 _759_ (
    .CK(CK),
    .D(stato_0_),
    .Q(stato_2_),
    .RN(_027_),
    .SE(test_se),
    .SI(stato_1_)
  );

  LOGIC0_X1 _tie__const0_ (.Z(_const0_));
  wire _const0_;
  assign test_so = stato_2_;
endmodule