/* Generated by Yosys 0.38 (git sha1 543faed9c, gcc 11.4.0-1ubuntu1~22.04.3 -fPIC -Os) */

module b07(punti_retta_0_, punti_retta_1_, punti_retta_2_, punti_retta_3_, punti_retta_4_, punti_retta_5_, punti_retta_6_, punti_retta_7_, start, reset, CK, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  input CK;
  wire CK;
  wire cont_0_;
  wire cont_1_;
  wire cont_2_;
  wire cont_3_;
  wire cont_4_;
  wire cont_5_;
  wire cont_6_;
  wire cont_7_;
  wire mar_0_;
  wire mar_1_;
  wire mar_2_;
  wire mar_3_;
    output punti_retta_0_;
  output punti_retta_1_;
  output punti_retta_2_;
  output punti_retta_3_;
  output punti_retta_4_;
  output punti_retta_5_;
  output punti_retta_6_;
  output punti_retta_7_;
    wire punti_retta_0_;
  wire punti_retta_1_;
  wire punti_retta_2_;
  wire punti_retta_3_;
  wire punti_retta_4_;
  wire punti_retta_5_;
  wire punti_retta_6_;
  wire punti_retta_7_;
  input reset;
  wire reset;
  input start;
  wire start;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  wire stato_3_;
  wire stato_4_;
  wire stato_5_;
  wire stato_6_;
  wire t_1_;
  wire t_2_;
  wire t_3_;
  wire t_4_;
  wire t_5_;
  wire t_6_;
  wire x_0_;
  wire x_1_;
  wire x_2_;
  wire x_3_;
  wire x_4_;
  wire x_5_;
  wire x_6_;
  wire x_7_;
  wire y_0_;
  wire y_1_;
  wire y_2_;
  wire y_5_;
  INV_X1 _305_ (
    .A(x_1_),
    .ZN(_099_)
  );
  INV_X1 _306_ (
    .A(mar_3_),
    .ZN(_100_)
  );
  INV_X1 _307_ (
    .A(mar_2_),
    .ZN(_101_)
  );
  INV_X1 _308_ (
    .A(mar_0_),
    .ZN(_102_)
  );
  INV_X1 _309_ (
    .A(stato_4_),
    .ZN(_103_)
  );
  INV_X1 _310_ (
    .A(stato_3_),
    .ZN(_104_)
  );
  INV_X1 _311_ (
    .A(stato_5_),
    .ZN(_105_)
  );
  INV_X1 _312_ (
    .A(_004_),
    .ZN(_106_)
  );
  INV_X1 _313_ (
    .A(_003_),
    .ZN(_107_)
  );
  INV_X1 _314_ (
    .A(reset),
    .ZN(_016_)
  );
  MUX2_X1 _315_ (
    .A(t_6_),
    .B(x_5_),
    .S(stato_6_),
    .Z(_098_)
  );
  MUX2_X1 _316_ (
    .A(t_5_),
    .B(x_4_),
    .S(stato_6_),
    .Z(_097_)
  );
  MUX2_X1 _317_ (
    .A(t_4_),
    .B(x_3_),
    .S(stato_6_),
    .Z(_096_)
  );
  MUX2_X1 _318_ (
    .A(t_3_),
    .B(x_2_),
    .S(stato_6_),
    .Z(_095_)
  );
  MUX2_X1 _319_ (
    .A(t_2_),
    .B(x_1_),
    .S(stato_6_),
    .Z(_094_)
  );
  MUX2_X1 _320_ (
    .A(t_1_),
    .B(x_0_),
    .S(stato_6_),
    .Z(_093_)
  );
  NOR3_X1 _321_ (
    .A1(mar_3_),
    .A2(mar_2_),
    .A3(mar_1_),
    .ZN(_108_)
  );
  INV_X1 _322_ (
    .A(_108_),
    .ZN(_109_)
  );
  OR3_X1 _323_ (
    .A1(mar_3_),
    .A2(mar_1_),
    .A3(_102_),
    .ZN(_110_)
  );
  NAND2_X1 _324_ (
    .A1(mar_0_),
    .A2(_108_),
    .ZN(_111_)
  );
  NAND4_X1 _325_ (
    .A1(mar_3_),
    .A2(mar_1_),
    .A3(_102_),
    .A4(_013_),
    .ZN(_112_)
  );
  NAND2_X1 _326_ (
    .A1(_111_),
    .A2(_112_),
    .ZN(_113_)
  );
  MUX2_X1 _327_ (
    .A(y_5_),
    .B(_113_),
    .S(stato_1_),
    .Z(_092_)
  );
  NOR2_X1 _328_ (
    .A1(_100_),
    .A2(mar_2_),
    .ZN(_114_)
  );
  NAND2_X1 _329_ (
    .A1(mar_1_),
    .A2(_114_),
    .ZN(_115_)
  );
  NAND2_X1 _330_ (
    .A1(_111_),
    .A2(_115_),
    .ZN(_116_)
  );
  MUX2_X1 _331_ (
    .A(y_2_),
    .B(_116_),
    .S(stato_1_),
    .Z(_091_)
  );
  XOR2_X1 _332_ (
    .A(mar_1_),
    .B(mar_0_),
    .Z(_117_)
  );
  NAND2_X1 _333_ (
    .A1(_114_),
    .A2(_117_),
    .ZN(_118_)
  );
  NAND3_X1 _334_ (
    .A1(mar_3_),
    .A2(mar_2_),
    .A3(mar_0_),
    .ZN(_119_)
  );
  NAND3_X1 _335_ (
    .A1(_110_),
    .A2(_118_),
    .A3(_119_),
    .ZN(_120_)
  );
  MUX2_X1 _336_ (
    .A(y_1_),
    .B(_120_),
    .S(stato_1_),
    .Z(_090_)
  );
  NAND2_X1 _337_ (
    .A1(_109_),
    .A2(_115_),
    .ZN(_121_)
  );
  MUX2_X1 _338_ (
    .A(y_0_),
    .B(_121_),
    .S(stato_1_),
    .Z(_089_)
  );
  NOR2_X1 _339_ (
    .A1(stato_1_),
    .A2(stato_5_),
    .ZN(_122_)
  );
  OR2_X1 _340_ (
    .A1(stato_1_),
    .A2(stato_5_),
    .ZN(_123_)
  );
  NOR2_X1 _341_ (
    .A1(stato_2_),
    .A2(_123_),
    .ZN(_124_)
  );
  NAND2_X1 _342_ (
    .A1(x_7_),
    .A2(_124_),
    .ZN(_125_)
  );
  MUX2_X1 _343_ (
    .A(t_6_),
    .B(y_5_),
    .S(stato_5_),
    .Z(_126_)
  );
  NAND2_X1 _344_ (
    .A1(_107_),
    .A2(_126_),
    .ZN(_127_)
  );
  MUX2_X1 _345_ (
    .A(t_5_),
    .B(y_5_),
    .S(stato_5_),
    .Z(_128_)
  );
  NAND2_X1 _346_ (
    .A1(x_5_),
    .A2(_128_),
    .ZN(_129_)
  );
  XNOR2_X1 _347_ (
    .A(x_5_),
    .B(_128_),
    .ZN(_130_)
  );
  MUX2_X1 _348_ (
    .A(t_4_),
    .B(y_5_),
    .S(stato_5_),
    .Z(_131_)
  );
  AND2_X1 _349_ (
    .A1(x_4_),
    .A2(_131_),
    .ZN(_132_)
  );
  XNOR2_X1 _350_ (
    .A(x_4_),
    .B(_131_),
    .ZN(_133_)
  );
  MUX2_X1 _351_ (
    .A(t_3_),
    .B(y_5_),
    .S(stato_5_),
    .Z(_134_)
  );
  AND2_X1 _352_ (
    .A1(x_3_),
    .A2(_134_),
    .ZN(_135_)
  );
  XNOR2_X1 _353_ (
    .A(x_3_),
    .B(_134_),
    .ZN(_136_)
  );
  MUX2_X1 _354_ (
    .A(t_2_),
    .B(y_2_),
    .S(stato_5_),
    .Z(_137_)
  );
  AND2_X1 _355_ (
    .A1(x_2_),
    .A2(_137_),
    .ZN(_138_)
  );
  MUX2_X1 _356_ (
    .A(t_1_),
    .B(y_1_),
    .S(stato_5_),
    .Z(_139_)
  );
  AND2_X1 _357_ (
    .A1(x_1_),
    .A2(_139_),
    .ZN(_140_)
  );
  NAND2_X1 _358_ (
    .A1(y_0_),
    .A2(stato_5_),
    .ZN(_141_)
  );
  NAND3_X1 _359_ (
    .A1(y_0_),
    .A2(stato_5_),
    .A3(_106_),
    .ZN(_142_)
  );
  XNOR2_X1 _360_ (
    .A(x_1_),
    .B(_139_),
    .ZN(_143_)
  );
  NOR2_X1 _361_ (
    .A1(_142_),
    .A2(_143_),
    .ZN(_144_)
  );
  NOR2_X1 _362_ (
    .A1(_140_),
    .A2(_144_),
    .ZN(_145_)
  );
  XNOR2_X1 _363_ (
    .A(x_2_),
    .B(_137_),
    .ZN(_146_)
  );
  NOR2_X1 _364_ (
    .A1(_145_),
    .A2(_146_),
    .ZN(_147_)
  );
  NOR2_X1 _365_ (
    .A1(_138_),
    .A2(_147_),
    .ZN(_148_)
  );
  NOR2_X1 _366_ (
    .A1(_136_),
    .A2(_148_),
    .ZN(_149_)
  );
  NOR2_X1 _367_ (
    .A1(_135_),
    .A2(_149_),
    .ZN(_150_)
  );
  NOR2_X1 _368_ (
    .A1(_133_),
    .A2(_150_),
    .ZN(_151_)
  );
  NOR2_X1 _369_ (
    .A1(_132_),
    .A2(_151_),
    .ZN(_152_)
  );
  OR2_X1 _370_ (
    .A1(_130_),
    .A2(_152_),
    .ZN(_153_)
  );
  NAND2_X1 _371_ (
    .A1(_129_),
    .A2(_153_),
    .ZN(_154_)
  );
  XNOR2_X1 _372_ (
    .A(_003_),
    .B(_126_),
    .ZN(_155_)
  );
  NAND2_X1 _373_ (
    .A1(_154_),
    .A2(_155_),
    .ZN(_156_)
  );
  NAND3_X1 _374_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_156_),
    .ZN(_157_)
  );
  NAND2_X1 _375_ (
    .A1(stato_2_),
    .A2(_113_),
    .ZN(_158_)
  );
  NAND2_X1 _376_ (
    .A1(_122_),
    .A2(_158_),
    .ZN(_159_)
  );
  NAND2_X1 _377_ (
    .A1(_157_),
    .A2(_159_),
    .ZN(_160_)
  );
  NAND2_X1 _378_ (
    .A1(_125_),
    .A2(_160_),
    .ZN(_088_)
  );
  OR2_X1 _379_ (
    .A1(_154_),
    .A2(_155_),
    .ZN(_161_)
  );
  NAND3_X1 _380_ (
    .A1(_123_),
    .A2(_156_),
    .A3(_161_),
    .ZN(_162_)
  );
  NAND2_X1 _381_ (
    .A1(_113_),
    .A2(_122_),
    .ZN(_163_)
  );
  NAND2_X1 _382_ (
    .A1(_162_),
    .A2(_163_),
    .ZN(_164_)
  );
  MUX2_X1 _383_ (
    .A(_164_),
    .B(x_6_),
    .S(_124_),
    .Z(_087_)
  );
  NAND2_X1 _384_ (
    .A1(x_5_),
    .A2(_124_),
    .ZN(_165_)
  );
  XNOR2_X1 _385_ (
    .A(_130_),
    .B(_152_),
    .ZN(_166_)
  );
  NAND2_X1 _386_ (
    .A1(_123_),
    .A2(_166_),
    .ZN(_167_)
  );
  NAND2_X1 _387_ (
    .A1(_159_),
    .A2(_167_),
    .ZN(_168_)
  );
  NAND2_X1 _388_ (
    .A1(_165_),
    .A2(_168_),
    .ZN(_086_)
  );
  NAND2_X1 _389_ (
    .A1(x_4_),
    .A2(_124_),
    .ZN(_169_)
  );
  XNOR2_X1 _390_ (
    .A(_133_),
    .B(_150_),
    .ZN(_170_)
  );
  NAND2_X1 _391_ (
    .A1(_123_),
    .A2(_170_),
    .ZN(_171_)
  );
  NAND2_X1 _392_ (
    .A1(_159_),
    .A2(_171_),
    .ZN(_172_)
  );
  NAND2_X1 _393_ (
    .A1(_169_),
    .A2(_172_),
    .ZN(_085_)
  );
  NAND2_X1 _394_ (
    .A1(x_3_),
    .A2(_124_),
    .ZN(_173_)
  );
  XNOR2_X1 _395_ (
    .A(_136_),
    .B(_148_),
    .ZN(_174_)
  );
  NAND2_X1 _396_ (
    .A1(_123_),
    .A2(_174_),
    .ZN(_175_)
  );
  NAND2_X1 _397_ (
    .A1(_159_),
    .A2(_175_),
    .ZN(_176_)
  );
  NAND2_X1 _398_ (
    .A1(_173_),
    .A2(_176_),
    .ZN(_084_)
  );
  XOR2_X1 _399_ (
    .A(_145_),
    .B(_146_),
    .Z(_177_)
  );
  MUX2_X1 _400_ (
    .A(_116_),
    .B(_177_),
    .S(_123_),
    .Z(_178_)
  );
  MUX2_X1 _401_ (
    .A(_178_),
    .B(x_2_),
    .S(_124_),
    .Z(_083_)
  );
  XOR2_X1 _402_ (
    .A(_142_),
    .B(_143_),
    .Z(_179_)
  );
  MUX2_X1 _403_ (
    .A(x_1_),
    .B(_120_),
    .S(stato_2_),
    .Z(_180_)
  );
  MUX2_X1 _404_ (
    .A(_179_),
    .B(_180_),
    .S(_122_),
    .Z(_082_)
  );
  NAND2_X1 _405_ (
    .A1(_106_),
    .A2(_123_),
    .ZN(_181_)
  );
  NAND2_X1 _406_ (
    .A1(_141_),
    .A2(_181_),
    .ZN(_182_)
  );
  NAND2_X1 _407_ (
    .A1(_142_),
    .A2(_182_),
    .ZN(_183_)
  );
  NAND2_X1 _408_ (
    .A1(_121_),
    .A2(_122_),
    .ZN(_184_)
  );
  NAND2_X1 _409_ (
    .A1(_183_),
    .A2(_184_),
    .ZN(_185_)
  );
  MUX2_X1 _410_ (
    .A(_185_),
    .B(x_0_),
    .S(_124_),
    .Z(_081_)
  );
  NAND2_X1 _411_ (
    .A1(_014_),
    .A2(_104_),
    .ZN(_186_)
  );
  NOR4_X1 _412_ (
    .A1(_099_),
    .A2(x_0_),
    .A3(x_7_),
    .A4(x_6_),
    .ZN(_187_)
  );
  NOR4_X1 _413_ (
    .A1(x_5_),
    .A2(x_4_),
    .A3(x_3_),
    .A4(x_2_),
    .ZN(_188_)
  );
  AND2_X1 _414_ (
    .A1(_187_),
    .A2(_188_),
    .ZN(_189_)
  );
  NAND2_X1 _415_ (
    .A1(_187_),
    .A2(_188_),
    .ZN(_190_)
  );
  NAND2_X1 _416_ (
    .A1(mar_1_),
    .A2(mar_0_),
    .ZN(_191_)
  );
  NOR3_X1 _417_ (
    .A1(_100_),
    .A2(_101_),
    .A3(_191_),
    .ZN(_192_)
  );
  NAND4_X1 _418_ (
    .A1(mar_3_),
    .A2(mar_2_),
    .A3(mar_1_),
    .A4(mar_0_),
    .ZN(_193_)
  );
  NAND2_X1 _419_ (
    .A1(stato_3_),
    .A2(_193_),
    .ZN(_194_)
  );
  NOR2_X1 _420_ (
    .A1(_189_),
    .A2(_194_),
    .ZN(_195_)
  );
  NOR2_X1 _421_ (
    .A1(_015_),
    .A2(_193_),
    .ZN(_196_)
  );
  NOR2_X1 _422_ (
    .A1(_103_),
    .A2(start),
    .ZN(_197_)
  );
  OR2_X1 _423_ (
    .A1(_196_),
    .A2(_197_),
    .ZN(_198_)
  );
  NOR2_X1 _424_ (
    .A1(_195_),
    .A2(_198_),
    .ZN(_199_)
  );
  NAND2_X1 _425_ (
    .A1(_186_),
    .A2(_199_),
    .ZN(_200_)
  );
  NAND2_X1 _426_ (
    .A1(cont_7_),
    .A2(_200_),
    .ZN(_201_)
  );
  NOR3_X1 _427_ (
    .A1(_104_),
    .A2(_195_),
    .A3(_198_),
    .ZN(_202_)
  );
  NAND2_X1 _428_ (
    .A1(cont_1_),
    .A2(cont_0_),
    .ZN(_203_)
  );
  AND3_X1 _429_ (
    .A1(cont_2_),
    .A2(cont_1_),
    .A3(cont_0_),
    .ZN(_204_)
  );
  NAND2_X1 _430_ (
    .A1(cont_3_),
    .A2(_204_),
    .ZN(_205_)
  );
  AND3_X1 _431_ (
    .A1(cont_4_),
    .A2(cont_3_),
    .A3(_204_),
    .ZN(_206_)
  );
  NAND2_X1 _432_ (
    .A1(cont_5_),
    .A2(_206_),
    .ZN(_207_)
  );
  NAND3_X1 _433_ (
    .A1(cont_6_),
    .A2(cont_5_),
    .A3(_206_),
    .ZN(_208_)
  );
  XOR2_X1 _434_ (
    .A(_005_),
    .B(_208_),
    .Z(_209_)
  );
  NAND2_X1 _435_ (
    .A1(_202_),
    .A2(_209_),
    .ZN(_210_)
  );
  NAND2_X1 _436_ (
    .A1(_201_),
    .A2(_210_),
    .ZN(_080_)
  );
  NAND2_X1 _437_ (
    .A1(cont_6_),
    .A2(_200_),
    .ZN(_211_)
  );
  XNOR2_X1 _438_ (
    .A(cont_6_),
    .B(_207_),
    .ZN(_212_)
  );
  NAND2_X1 _439_ (
    .A1(_202_),
    .A2(_212_),
    .ZN(_213_)
  );
  NAND2_X1 _440_ (
    .A1(_211_),
    .A2(_213_),
    .ZN(_079_)
  );
  NAND2_X1 _441_ (
    .A1(cont_5_),
    .A2(_200_),
    .ZN(_214_)
  );
  XNOR2_X1 _442_ (
    .A(_007_),
    .B(_206_),
    .ZN(_215_)
  );
  NAND2_X1 _443_ (
    .A1(_202_),
    .A2(_215_),
    .ZN(_216_)
  );
  NAND2_X1 _444_ (
    .A1(_214_),
    .A2(_216_),
    .ZN(_078_)
  );
  NAND2_X1 _445_ (
    .A1(cont_4_),
    .A2(_200_),
    .ZN(_217_)
  );
  XOR2_X1 _446_ (
    .A(cont_4_),
    .B(_205_),
    .Z(_218_)
  );
  INV_X1 _447_ (
    .A(_218_),
    .ZN(_219_)
  );
  NAND2_X1 _448_ (
    .A1(_202_),
    .A2(_219_),
    .ZN(_220_)
  );
  NAND2_X1 _449_ (
    .A1(_217_),
    .A2(_220_),
    .ZN(_077_)
  );
  NAND2_X1 _450_ (
    .A1(cont_3_),
    .A2(_200_),
    .ZN(_221_)
  );
  XNOR2_X1 _451_ (
    .A(_009_),
    .B(_204_),
    .ZN(_222_)
  );
  NAND2_X1 _452_ (
    .A1(_202_),
    .A2(_222_),
    .ZN(_223_)
  );
  NAND2_X1 _453_ (
    .A1(_221_),
    .A2(_223_),
    .ZN(_076_)
  );
  NAND2_X1 _454_ (
    .A1(cont_2_),
    .A2(_200_),
    .ZN(_224_)
  );
  XOR2_X1 _455_ (
    .A(cont_2_),
    .B(_203_),
    .Z(_225_)
  );
  INV_X1 _456_ (
    .A(_225_),
    .ZN(_226_)
  );
  NAND2_X1 _457_ (
    .A1(_202_),
    .A2(_226_),
    .ZN(_227_)
  );
  NAND2_X1 _458_ (
    .A1(_224_),
    .A2(_227_),
    .ZN(_075_)
  );
  NAND2_X1 _459_ (
    .A1(cont_1_),
    .A2(_200_),
    .ZN(_228_)
  );
  XOR2_X1 _460_ (
    .A(cont_1_),
    .B(cont_0_),
    .Z(_229_)
  );
  NAND2_X1 _461_ (
    .A1(_202_),
    .A2(_229_),
    .ZN(_230_)
  );
  NAND2_X1 _462_ (
    .A1(_228_),
    .A2(_230_),
    .ZN(_074_)
  );
  MUX2_X1 _463_ (
    .A(_202_),
    .B(_200_),
    .S(cont_0_),
    .Z(_073_)
  );
  NAND3_X1 _464_ (
    .A1(stato_3_),
    .A2(start),
    .A3(_192_),
    .ZN(_231_)
  );
  NAND2_X1 _465_ (
    .A1(stato_4_),
    .A2(start),
    .ZN(_232_)
  );
  AND4_X1 _466_ (
    .A1(_186_),
    .A2(_194_),
    .A3(_231_),
    .A4(_232_),
    .ZN(_233_)
  );
  NOR2_X1 _467_ (
    .A1(_190_),
    .A2(_209_),
    .ZN(_234_)
  );
  AND2_X1 _468_ (
    .A1(_005_),
    .A2(_190_),
    .ZN(_235_)
  );
  NOR3_X1 _469_ (
    .A1(_104_),
    .A2(_234_),
    .A3(_235_),
    .ZN(_236_)
  );
  MUX2_X1 _470_ (
    .A(punti_retta_7_),
    .B(_236_),
    .S(_233_),
    .Z(_072_)
  );
  NOR2_X1 _471_ (
    .A1(_190_),
    .A2(_212_),
    .ZN(_237_)
  );
  AND2_X1 _472_ (
    .A1(_006_),
    .A2(_190_),
    .ZN(_238_)
  );
  NOR3_X1 _473_ (
    .A1(_104_),
    .A2(_237_),
    .A3(_238_),
    .ZN(_239_)
  );
  MUX2_X1 _474_ (
    .A(punti_retta_6_),
    .B(_239_),
    .S(_233_),
    .Z(_071_)
  );
  NOR2_X1 _475_ (
    .A1(_190_),
    .A2(_215_),
    .ZN(_240_)
  );
  AND2_X1 _476_ (
    .A1(_007_),
    .A2(_190_),
    .ZN(_241_)
  );
  NOR3_X1 _477_ (
    .A1(_104_),
    .A2(_240_),
    .A3(_241_),
    .ZN(_242_)
  );
  MUX2_X1 _478_ (
    .A(punti_retta_5_),
    .B(_242_),
    .S(_233_),
    .Z(_070_)
  );
  NAND2_X1 _479_ (
    .A1(_189_),
    .A2(_218_),
    .ZN(_243_)
  );
  NAND2_X1 _480_ (
    .A1(_008_),
    .A2(_190_),
    .ZN(_244_)
  );
  AND3_X1 _481_ (
    .A1(stato_3_),
    .A2(_243_),
    .A3(_244_),
    .ZN(_245_)
  );
  MUX2_X1 _482_ (
    .A(punti_retta_4_),
    .B(_245_),
    .S(_233_),
    .Z(_069_)
  );
  NOR2_X1 _483_ (
    .A1(_190_),
    .A2(_222_),
    .ZN(_246_)
  );
  AND2_X1 _484_ (
    .A1(_009_),
    .A2(_190_),
    .ZN(_247_)
  );
  NOR3_X1 _485_ (
    .A1(_104_),
    .A2(_246_),
    .A3(_247_),
    .ZN(_248_)
  );
  MUX2_X1 _486_ (
    .A(punti_retta_3_),
    .B(_248_),
    .S(_233_),
    .Z(_068_)
  );
  NAND2_X1 _487_ (
    .A1(_189_),
    .A2(_225_),
    .ZN(_249_)
  );
  NAND2_X1 _488_ (
    .A1(_010_),
    .A2(_190_),
    .ZN(_250_)
  );
  AND3_X1 _489_ (
    .A1(stato_3_),
    .A2(_249_),
    .A3(_250_),
    .ZN(_251_)
  );
  MUX2_X1 _490_ (
    .A(punti_retta_2_),
    .B(_251_),
    .S(_233_),
    .Z(_067_)
  );
  NOR2_X1 _491_ (
    .A1(_190_),
    .A2(_229_),
    .ZN(_252_)
  );
  AND2_X1 _492_ (
    .A1(_011_),
    .A2(_190_),
    .ZN(_253_)
  );
  NOR3_X1 _493_ (
    .A1(_104_),
    .A2(_252_),
    .A3(_253_),
    .ZN(_254_)
  );
  MUX2_X1 _494_ (
    .A(punti_retta_1_),
    .B(_254_),
    .S(_233_),
    .Z(_066_)
  );
  AND2_X1 _495_ (
    .A1(cont_0_),
    .A2(_189_),
    .ZN(_255_)
  );
  NOR2_X1 _496_ (
    .A1(cont_0_),
    .A2(_189_),
    .ZN(_256_)
  );
  NOR3_X1 _497_ (
    .A1(_104_),
    .A2(_255_),
    .A3(_256_),
    .ZN(_257_)
  );
  MUX2_X1 _498_ (
    .A(punti_retta_0_),
    .B(_257_),
    .S(_233_),
    .Z(_065_)
  );
  NOR2_X1 _499_ (
    .A1(stato_6_),
    .A2(stato_3_),
    .ZN(_258_)
  );
  NOR2_X1 _500_ (
    .A1(_198_),
    .A2(_258_),
    .ZN(_259_)
  );
  NOR2_X1 _501_ (
    .A1(_103_),
    .A2(_198_),
    .ZN(_260_)
  );
  NOR2_X1 _502_ (
    .A1(_259_),
    .A2(_260_),
    .ZN(_261_)
  );
  NAND2_X1 _503_ (
    .A1(mar_3_),
    .A2(_261_),
    .ZN(_262_)
  );
  NOR2_X1 _504_ (
    .A1(_013_),
    .A2(_191_),
    .ZN(_263_)
  );
  XNOR2_X1 _505_ (
    .A(_012_),
    .B(_263_),
    .ZN(_264_)
  );
  NAND2_X1 _506_ (
    .A1(_259_),
    .A2(_264_),
    .ZN(_265_)
  );
  NAND2_X1 _507_ (
    .A1(_262_),
    .A2(_265_),
    .ZN(_064_)
  );
  NAND2_X1 _508_ (
    .A1(mar_2_),
    .A2(_261_),
    .ZN(_266_)
  );
  XOR2_X1 _509_ (
    .A(_013_),
    .B(_191_),
    .Z(_267_)
  );
  NAND2_X1 _510_ (
    .A1(_259_),
    .A2(_267_),
    .ZN(_268_)
  );
  NAND2_X1 _511_ (
    .A1(_266_),
    .A2(_268_),
    .ZN(_063_)
  );
  NAND2_X1 _512_ (
    .A1(mar_1_),
    .A2(_261_),
    .ZN(_269_)
  );
  NAND2_X1 _513_ (
    .A1(_117_),
    .A2(_259_),
    .ZN(_270_)
  );
  NAND2_X1 _514_ (
    .A1(_269_),
    .A2(_270_),
    .ZN(_062_)
  );
  MUX2_X1 _515_ (
    .A(_259_),
    .B(_261_),
    .S(mar_0_),
    .Z(_061_)
  );
  NOR3_X1 _516_ (
    .A1(_104_),
    .A2(start),
    .A3(_193_),
    .ZN(_271_)
  );
  OR3_X1 _517_ (
    .A1(stato_0_),
    .A2(_197_),
    .A3(_271_),
    .ZN(_002_)
  );
  NAND2_X1 _518_ (
    .A1(_105_),
    .A2(_231_),
    .ZN(_001_)
  );
  OR2_X1 _519_ (
    .A1(_015_),
    .A2(_192_),
    .ZN(_272_)
  );
  NAND2_X1 _520_ (
    .A1(_232_),
    .A2(_272_),
    .ZN(_000_)
  );
  INV_X1 _521_ (
    .A(reset),
    .ZN(_017_)
  );
  INV_X1 _522_ (
    .A(reset),
    .ZN(_018_)
  );
  INV_X1 _523_ (
    .A(reset),
    .ZN(_019_)
  );
  INV_X1 _524_ (
    .A(reset),
    .ZN(_020_)
  );
  INV_X1 _525_ (
    .A(reset),
    .ZN(_021_)
  );
  INV_X1 _526_ (
    .A(reset),
    .ZN(_022_)
  );
  INV_X1 _527_ (
    .A(reset),
    .ZN(_023_)
  );
  INV_X1 _528_ (
    .A(reset),
    .ZN(_024_)
  );
  INV_X1 _529_ (
    .A(reset),
    .ZN(_025_)
  );
  INV_X1 _530_ (
    .A(reset),
    .ZN(_026_)
  );
  INV_X1 _531_ (
    .A(reset),
    .ZN(_027_)
  );
  INV_X1 _532_ (
    .A(reset),
    .ZN(_028_)
  );
  INV_X1 _533_ (
    .A(reset),
    .ZN(_029_)
  );
  INV_X1 _534_ (
    .A(reset),
    .ZN(_030_)
  );
  INV_X1 _535_ (
    .A(reset),
    .ZN(_031_)
  );
  INV_X1 _536_ (
    .A(reset),
    .ZN(_032_)
  );
  INV_X1 _537_ (
    .A(reset),
    .ZN(_033_)
  );
  INV_X1 _538_ (
    .A(reset),
    .ZN(_034_)
  );
  INV_X1 _539_ (
    .A(reset),
    .ZN(_035_)
  );
  INV_X1 _540_ (
    .A(reset),
    .ZN(_036_)
  );
  INV_X1 _541_ (
    .A(reset),
    .ZN(_037_)
  );
  INV_X1 _542_ (
    .A(reset),
    .ZN(_038_)
  );
  INV_X1 _543_ (
    .A(reset),
    .ZN(_039_)
  );
  INV_X1 _544_ (
    .A(reset),
    .ZN(_040_)
  );
  INV_X1 _545_ (
    .A(reset),
    .ZN(_041_)
  );
  INV_X1 _546_ (
    .A(reset),
    .ZN(_042_)
  );
  INV_X1 _547_ (
    .A(reset),
    .ZN(_043_)
  );
  INV_X1 _548_ (
    .A(reset),
    .ZN(_044_)
  );
  INV_X1 _549_ (
    .A(reset),
    .ZN(_045_)
  );
  INV_X1 _550_ (
    .A(reset),
    .ZN(_046_)
  );
  INV_X1 _551_ (
    .A(reset),
    .ZN(_047_)
  );
  INV_X1 _552_ (
    .A(reset),
    .ZN(_048_)
  );
  INV_X1 _553_ (
    .A(reset),
    .ZN(_049_)
  );
  INV_X1 _554_ (
    .A(reset),
    .ZN(_050_)
  );
  INV_X1 _555_ (
    .A(reset),
    .ZN(_051_)
  );
  INV_X1 _556_ (
    .A(reset),
    .ZN(_052_)
  );
  INV_X1 _557_ (
    .A(reset),
    .ZN(_053_)
  );
  INV_X1 _558_ (
    .A(reset),
    .ZN(_054_)
  );
  INV_X1 _559_ (
    .A(reset),
    .ZN(_055_)
  );
  INV_X1 _560_ (
    .A(reset),
    .ZN(_056_)
  );
  INV_X1 _561_ (
    .A(reset),
    .ZN(_057_)
  );
  INV_X1 _562_ (
    .A(reset),
    .ZN(_058_)
  );
  INV_X1 _563_ (
    .A(reset),
    .ZN(_059_)
  );
  INV_X1 _564_ (
    .A(reset),
    .ZN(_060_)
  );
  SDFFRS_X1 _565_ (
    .CK(CK),
    .D(_const0_),
    .Q(stato_0_),
    .RN(_const1_),
    .SN(_016_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _566_ (
    .CK(CK),
    .D(stato_6_),
    .Q(stato_1_),
    .RN(_017_),
    .SE(test_se),
    .SI(stato_0_)
  );
  SDFFR_X1 _567_ (
    .CK(CK),
    .D(_000_),
    .Q(stato_2_),
    .RN(_018_),
    .SE(test_se),
    .SI(stato_1_)
  );
  SDFFR_X1 _568_ (
    .CK(CK),
    .D(_001_),
    .Q(stato_3_),
    .QN(_015_),
    .RN(_019_),
    .SE(test_se),
    .SI(stato_2_)
  );
  SDFFR_X1 _569_ (
    .CK(CK),
    .D(_002_),
    .Q(stato_4_),
    .QN(_014_),
    .RN(_020_),
    .SE(test_se),
    .SI(stato_3_)
  );
  SDFFR_X1 _570_ (
    .CK(CK),
    .D(stato_1_),
    .Q(stato_5_),
    .RN(_021_),
    .SE(test_se),
    .SI(stato_4_)
  );
  SDFFR_X1 _571_ (
    .CK(CK),
    .D(stato_2_),
    .Q(stato_6_),
    .RN(_022_),
    .SE(test_se),
    .SI(stato_5_)
  );
  SDFFR_X1 _572_ (
    .CK(CK),
    .D(_061_),
    .Q(mar_0_),
    .RN(_023_),
    .SE(test_se),
    .SI(stato_6_)
  );
  SDFFR_X1 _573_ (
    .CK(CK),
    .D(_062_),
    .Q(mar_1_),
    .RN(_024_),
    .SE(test_se),
    .SI(mar_0_)
  );
  SDFFR_X1 _574_ (
    .CK(CK),
    .D(_063_),
    .Q(mar_2_),
    .QN(_013_),
    .RN(_025_),
    .SE(test_se),
    .SI(mar_1_)
  );
  SDFFR_X1 _575_ (
    .CK(CK),
    .D(_064_),
    .Q(mar_3_),
    .QN(_012_),
    .RN(_026_),
    .SE(test_se),
    .SI(mar_2_)
  );
  SDFFR_X1 _576_ (
    .CK(CK),
    .D(_065_),
    .Q(punti_retta_0_),
    .RN(_027_),
    .SE(test_se),
    .SI(mar_3_)
  );
  SDFFR_X1 _577_ (
    .CK(CK),
    .D(_066_),
    .Q(punti_retta_1_),
    .RN(_028_),
    .SE(test_se),
    .SI(punti_retta_0_)
  );
  SDFFR_X1 _578_ (
    .CK(CK),
    .D(_067_),
    .Q(punti_retta_2_),
    .RN(_029_),
    .SE(test_se),
    .SI(punti_retta_1_)
  );
  SDFFR_X1 _579_ (
    .CK(CK),
    .D(_068_),
    .Q(punti_retta_3_),
    .RN(_030_),
    .SE(test_se),
    .SI(punti_retta_2_)
  );
  SDFFR_X1 _580_ (
    .CK(CK),
    .D(_069_),
    .Q(punti_retta_4_),
    .RN(_031_),
    .SE(test_se),
    .SI(punti_retta_3_)
  );
  SDFFR_X1 _581_ (
    .CK(CK),
    .D(_070_),
    .Q(punti_retta_5_),
    .RN(_032_),
    .SE(test_se),
    .SI(punti_retta_4_)
  );
  SDFFR_X1 _582_ (
    .CK(CK),
    .D(_071_),
    .Q(punti_retta_6_),
    .RN(_033_),
    .SE(test_se),
    .SI(punti_retta_5_)
  );
  SDFFR_X1 _583_ (
    .CK(CK),
    .D(_072_),
    .Q(punti_retta_7_),
    .RN(_034_),
    .SE(test_se),
    .SI(punti_retta_6_)
  );
  SDFFR_X1 _584_ (
    .CK(CK),
    .D(_073_),
    .Q(cont_0_),
    .RN(_035_),
    .SE(test_se),
    .SI(punti_retta_7_)
  );
  SDFFR_X1 _585_ (
    .CK(CK),
    .D(_074_),
    .Q(cont_1_),
    .QN(_011_),
    .RN(_036_),
    .SE(test_se),
    .SI(cont_0_)
  );
  SDFFR_X1 _586_ (
    .CK(CK),
    .D(_075_),
    .Q(cont_2_),
    .QN(_010_),
    .RN(_037_),
    .SE(test_se),
    .SI(cont_1_)
  );
  SDFFR_X1 _587_ (
    .CK(CK),
    .D(_076_),
    .Q(cont_3_),
    .QN(_009_),
    .RN(_038_),
    .SE(test_se),
    .SI(cont_2_)
  );
  SDFFR_X1 _588_ (
    .CK(CK),
    .D(_077_),
    .Q(cont_4_),
    .QN(_008_),
    .RN(_039_),
    .SE(test_se),
    .SI(cont_3_)
  );
  SDFFR_X1 _589_ (
    .CK(CK),
    .D(_078_),
    .Q(cont_5_),
    .QN(_007_),
    .RN(_040_),
    .SE(test_se),
    .SI(cont_4_)
  );
  SDFFR_X1 _590_ (
    .CK(CK),
    .D(_079_),
    .Q(cont_6_),
    .QN(_006_),
    .RN(_041_),
    .SE(test_se),
    .SI(cont_5_)
  );
  SDFFR_X1 _591_ (
    .CK(CK),
    .D(_080_),
    .Q(cont_7_),
    .QN(_005_),
    .RN(_042_),
    .SE(test_se),
    .SI(cont_6_)
  );
  SDFFR_X1 _592_ (
    .CK(CK),
    .D(_081_),
    .Q(x_0_),
    .QN(_004_),
    .RN(_043_),
    .SE(test_se),
    .SI(cont_7_)
  );
  SDFFR_X1 _593_ (
    .CK(CK),
    .D(_082_),
    .Q(x_1_),
    .RN(_044_),
    .SE(test_se),
    .SI(x_0_)
  );
  SDFFR_X1 _594_ (
    .CK(CK),
    .D(_083_),
    .Q(x_2_),
    .RN(_045_),
    .SE(test_se),
    .SI(x_1_)
  );
  SDFFR_X1 _595_ (
    .CK(CK),
    .D(_084_),
    .Q(x_3_),
    .RN(_046_),
    .SE(test_se),
    .SI(x_2_)
  );
  SDFFR_X1 _596_ (
    .CK(CK),
    .D(_085_),
    .Q(x_4_),
    .RN(_047_),
    .SE(test_se),
    .SI(x_3_)
  );
  SDFFR_X1 _597_ (
    .CK(CK),
    .D(_086_),
    .Q(x_5_),
    .RN(_048_),
    .SE(test_se),
    .SI(x_4_)
  );
  SDFFR_X1 _598_ (
    .CK(CK),
    .D(_087_),
    .Q(x_6_),
    .QN(_003_),
    .RN(_049_),
    .SE(test_se),
    .SI(x_5_)
  );
  SDFFR_X1 _599_ (
    .CK(CK),
    .D(_088_),
    .Q(x_7_),
    .RN(_050_),
    .SE(test_se),
    .SI(x_6_)
  );
  SDFFR_X1 _600_ (
    .CK(CK),
    .D(_089_),
    .Q(y_0_),
    .RN(_051_),
    .SE(test_se),
    .SI(x_7_)
  );
  SDFFR_X1 _601_ (
    .CK(CK),
    .D(_090_),
    .Q(y_1_),
    .RN(_052_),
    .SE(test_se),
    .SI(y_0_)
  );
  SDFFR_X1 _602_ (
    .CK(CK),
    .D(_091_),
    .Q(y_2_),
    .RN(_053_),
    .SE(test_se),
    .SI(y_1_)
  );
  SDFFR_X1 _603_ (
    .CK(CK),
    .D(_092_),
    .Q(y_5_),
    .RN(_054_),
    .SE(test_se),
    .SI(y_2_)
  );
  SDFFR_X1 _604_ (
    .CK(CK),
    .D(_093_),
    .Q(t_1_),
    .RN(_055_),
    .SE(test_se),
    .SI(y_5_)
  );
  SDFFR_X1 _605_ (
    .CK(CK),
    .D(_094_),
    .Q(t_2_),
    .RN(_056_),
    .SE(test_se),
    .SI(t_1_)
  );
  SDFFR_X1 _606_ (
    .CK(CK),
    .D(_095_),
    .Q(t_3_),
    .RN(_057_),
    .SE(test_se),
    .SI(t_2_)
  );
  SDFFR_X1 _607_ (
    .CK(CK),
    .D(_096_),
    .Q(t_4_),
    .RN(_058_),
    .SE(test_se),
    .SI(t_3_)
  );
  SDFFR_X1 _608_ (
    .CK(CK),
    .D(_097_),
    .Q(t_5_),
    .RN(_059_),
    .SE(test_se),
    .SI(t_4_)
  );
  SDFFR_X1 _609_ (
    .CK(CK),
    .D(_098_),
    .Q(t_6_),
    .RN(_060_),
    .SE(test_se),
    .SI(t_5_)
  );

  wire _const0_;
  wire _const1_;
  LOGIC0_X1 _tie__const0_ (.Z(_const0_));
  LOGIC1_X1 _tie__const1_ (.Z(_const1_));
  assign test_so = t_6_;
endmodule