/* Generated by Yosys 0.65 (git sha1 9d0cdb855, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module b07(punti_retta_0_, punti_retta_1_, punti_retta_2_, punti_retta_3_, punti_retta_4_, punti_retta_5_, punti_retta_6_, punti_retta_7_, start, reset, clock, _const0_);
    output punti_retta_0_;
  output punti_retta_1_;
  output punti_retta_2_;
  output punti_retta_3_;
  output punti_retta_4_;
  output punti_retta_5_;
  output punti_retta_6_;
  output punti_retta_7_;
    wire punti_retta_0_;
  wire punti_retta_1_;
  wire punti_retta_2_;
  wire punti_retta_3_;
  wire punti_retta_4_;
  wire punti_retta_5_;
  wire punti_retta_6_;
  wire punti_retta_7_;
  input start;
  wire start;
  input reset;
  wire reset;
  input clock;
  wire clock;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire cont_0_;
  wire cont_1_;
  wire cont_2_;
  wire cont_3_;
  wire cont_4_;
  wire cont_5_;
  wire cont_6_;
  wire cont_7_;
  wire mar_0_;
  wire mar_1_;
  wire mar_2_;
  wire mar_3_;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  wire stato_3_;
  wire stato_4_;
  wire stato_5_;
  wire stato_6_;
  wire t_1_;
  wire t_2_;
  wire t_3_;
  wire t_4_;
  wire t_5_;
  wire t_6_;
  wire x_0_;
  wire x_1_;
  wire x_2_;
  wire x_3_;
  wire x_4_;
  wire x_5_;
  wire x_6_;
  wire x_7_;
  wire y_0_;
  wire y_1_;
  wire y_2_;
  wire y_3_;
  input _const0_;
  INV_X1 _275_ (
    .A(punti_retta_2_),
    .ZN(_087_)
  );
  INV_X1 _276_ (
    .A(punti_retta_3_),
    .ZN(_088_)
  );
  INV_X1 _277_ (
    .A(punti_retta_4_),
    .ZN(_089_)
  );
  INV_X1 _278_ (
    .A(punti_retta_5_),
    .ZN(_090_)
  );
  INV_X1 _279_ (
    .A(punti_retta_7_),
    .ZN(_091_)
  );
  INV_X1 _280_ (
    .A(t_6_),
    .ZN(_092_)
  );
  INV_X1 _281_ (
    .A(x_5_),
    .ZN(_093_)
  );
  INV_X1 _282_ (
    .A(stato_6_),
    .ZN(_094_)
  );
  INV_X1 _283_ (
    .A(punti_retta_6_),
    .ZN(_095_)
  );
  INV_X1 _284_ (
    .A(mar_3_),
    .ZN(_096_)
  );
  INV_X1 _285_ (
    .A(mar_0_),
    .ZN(_097_)
  );
  INV_X1 _286_ (
    .A(mar_1_),
    .ZN(_098_)
  );
  INV_X1 _287_ (
    .A(x_0_),
    .ZN(_099_)
  );
  INV_X1 _288_ (
    .A(y_0_),
    .ZN(_100_)
  );
  INV_X1 _289_ (
    .A(y_2_),
    .ZN(_101_)
  );
  INV_X1 _290_ (
    .A(t_3_),
    .ZN(_102_)
  );
  INV_X1 _291_ (
    .A(t_4_),
    .ZN(_103_)
  );
  INV_X1 _292_ (
    .A(t_5_),
    .ZN(_104_)
  );
  INV_X1 _293_ (
    .A(punti_retta_0_),
    .ZN(_105_)
  );
  INV_X1 _294_ (
    .A(punti_retta_1_),
    .ZN(_106_)
  );
  INV_X1 _295_ (
    .A(start),
    .ZN(_107_)
  );
  INV_X1 _296_ (
    .A(_003_),
    .ZN(_108_)
  );
  INV_X1 _297_ (
    .A(stato_3_),
    .ZN(_109_)
  );
  INV_X1 _298_ (
    .A(stato_5_),
    .ZN(_110_)
  );
  INV_X1 _299_ (
    .A(stato_0_),
    .ZN(_111_)
  );
  INV_X1 _300_ (
    .A(reset),
    .ZN(_004_)
  );
  NAND2_X1 _301_ (
    .A1(mar_0_),
    .A2(mar_1_),
    .ZN(_112_)
  );
  AND3_X1 _302_ (
    .A1(mar_0_),
    .A2(mar_1_),
    .A3(mar_2_),
    .ZN(_113_)
  );
  AOI21_X1 _303_ (
    .A(_109_),
    .B1(_113_),
    .B2(mar_3_),
    .ZN(_114_)
  );
  NOR2_X1 _304_ (
    .A1(stato_3_),
    .A2(stato_4_),
    .ZN(_115_)
  );
  NOR3_X1 _305_ (
    .A1(start),
    .A2(_114_),
    .A3(_115_),
    .ZN(_116_)
  );
  OR4_X1 _306_ (
    .A1(x_2_),
    .A2(x_3_),
    .A3(x_4_),
    .A4(x_6_),
    .ZN(_117_)
  );
  NAND3_X1 _307_ (
    .A1(_093_),
    .A2(_099_),
    .A3(x_1_),
    .ZN(_118_)
  );
  NOR3_X1 _308_ (
    .A1(x_7_),
    .A2(_117_),
    .A3(_118_),
    .ZN(_119_)
  );
  NOR2_X1 _309_ (
    .A1(_109_),
    .A2(_119_),
    .ZN(_120_)
  );
  AND3_X1 _310_ (
    .A1(cont_0_),
    .A2(cont_1_),
    .A3(cont_2_),
    .ZN(_121_)
  );
  AOI21_X1 _311_ (
    .A(cont_2_),
    .B1(cont_1_),
    .B2(cont_0_),
    .ZN(_122_)
  );
  NOR3_X1 _312_ (
    .A1(_109_),
    .A2(_121_),
    .A3(_122_),
    .ZN(_123_)
  );
  OAI221_X1 _313_ (
    .A(_116_),
    .B1(_120_),
    .B2(_123_),
    .C1(_119_),
    .C2(cont_2_),
    .ZN(_124_)
  );
  OAI21_X1 _314_ (
    .A(_124_),
    .B1(_116_),
    .B2(_087_),
    .ZN(_086_)
  );
  AND2_X1 _315_ (
    .A1(cont_3_),
    .A2(_121_),
    .ZN(_125_)
  );
  OAI21_X1 _316_ (
    .A(stato_3_),
    .B1(_121_),
    .B2(cont_3_),
    .ZN(_126_)
  );
  NOR2_X1 _317_ (
    .A1(_125_),
    .A2(_126_),
    .ZN(_127_)
  );
  OAI221_X1 _318_ (
    .A(_116_),
    .B1(_120_),
    .B2(_127_),
    .C1(_119_),
    .C2(cont_3_),
    .ZN(_128_)
  );
  OAI21_X1 _319_ (
    .A(_128_),
    .B1(_116_),
    .B2(_088_),
    .ZN(_085_)
  );
  AND2_X1 _320_ (
    .A1(cont_4_),
    .A2(_125_),
    .ZN(_129_)
  );
  OAI21_X1 _321_ (
    .A(stato_3_),
    .B1(_125_),
    .B2(cont_4_),
    .ZN(_130_)
  );
  NOR2_X1 _322_ (
    .A1(_129_),
    .A2(_130_),
    .ZN(_131_)
  );
  OAI221_X1 _323_ (
    .A(_116_),
    .B1(_120_),
    .B2(_131_),
    .C1(_119_),
    .C2(cont_4_),
    .ZN(_132_)
  );
  OAI21_X1 _324_ (
    .A(_132_),
    .B1(_116_),
    .B2(_089_),
    .ZN(_084_)
  );
  OAI21_X1 _325_ (
    .A(stato_3_),
    .B1(_129_),
    .B2(cont_5_),
    .ZN(_133_)
  );
  AOI21_X1 _326_ (
    .A(_133_),
    .B1(_129_),
    .B2(cont_5_),
    .ZN(_134_)
  );
  OAI221_X1 _327_ (
    .A(_116_),
    .B1(_120_),
    .B2(_134_),
    .C1(_119_),
    .C2(cont_5_),
    .ZN(_135_)
  );
  OAI21_X1 _328_ (
    .A(_135_),
    .B1(_116_),
    .B2(_090_),
    .ZN(_083_)
  );
  NOR2_X1 _329_ (
    .A1(stato_1_),
    .A2(stato_5_),
    .ZN(_136_)
  );
  OR2_X1 _330_ (
    .A1(stato_1_),
    .A2(stato_5_),
    .ZN(_137_)
  );
  NOR2_X1 _331_ (
    .A1(stato_2_),
    .A2(_137_),
    .ZN(_138_)
  );
  NAND2_X1 _332_ (
    .A1(x_7_),
    .A2(_138_),
    .ZN(_139_)
  );
  NOR2_X1 _333_ (
    .A1(_098_),
    .A2(mar_2_),
    .ZN(_140_)
  );
  NAND2_X1 _334_ (
    .A1(mar_3_),
    .A2(_140_),
    .ZN(_141_)
  );
  AOI21_X1 _335_ (
    .A(mar_0_),
    .B1(_140_),
    .B2(mar_3_),
    .ZN(_142_)
  );
  OR3_X1 _336_ (
    .A1(mar_3_),
    .A2(mar_1_),
    .A3(mar_2_),
    .ZN(_143_)
  );
  AOI21_X1 _337_ (
    .A(_142_),
    .B1(_143_),
    .B2(mar_0_),
    .ZN(_144_)
  );
  NAND2_X1 _338_ (
    .A1(stato_2_),
    .A2(_144_),
    .ZN(_145_)
  );
  NAND2_X1 _339_ (
    .A1(_136_),
    .A2(_145_),
    .ZN(_146_)
  );
  INV_X1 _340_ (
    .A(_146_),
    .ZN(_147_)
  );
  NAND2_X1 _341_ (
    .A1(y_3_),
    .A2(stato_5_),
    .ZN(_148_)
  );
  OAI21_X1 _342_ (
    .A(_148_),
    .B1(stato_5_),
    .B2(_104_),
    .ZN(_149_)
  );
  NAND2_X1 _343_ (
    .A1(x_5_),
    .A2(_149_),
    .ZN(_150_)
  );
  OAI21_X1 _344_ (
    .A(_148_),
    .B1(stato_5_),
    .B2(_103_),
    .ZN(_151_)
  );
  AND2_X1 _345_ (
    .A1(x_4_),
    .A2(_151_),
    .ZN(_152_)
  );
  OAI21_X1 _346_ (
    .A(_148_),
    .B1(stato_5_),
    .B2(_102_),
    .ZN(_153_)
  );
  NAND2_X1 _347_ (
    .A1(x_3_),
    .A2(_153_),
    .ZN(_154_)
  );
  MUX2_X1 _348_ (
    .A(t_2_),
    .B(y_2_),
    .S(stato_5_),
    .Z(_155_)
  );
  AND2_X1 _349_ (
    .A1(x_2_),
    .A2(_155_),
    .ZN(_156_)
  );
  MUX2_X1 _350_ (
    .A(t_1_),
    .B(y_1_),
    .S(stato_5_),
    .Z(_157_)
  );
  NAND2_X1 _351_ (
    .A1(x_1_),
    .A2(_157_),
    .ZN(_158_)
  );
  NAND3_X1 _352_ (
    .A1(x_0_),
    .A2(y_0_),
    .A3(stato_5_),
    .ZN(_159_)
  );
  XNOR2_X1 _353_ (
    .A(x_1_),
    .B(_157_),
    .ZN(_160_)
  );
  OAI21_X1 _354_ (
    .A(_158_),
    .B1(_159_),
    .B2(_160_),
    .ZN(_161_)
  );
  XOR2_X1 _355_ (
    .A(x_2_),
    .B(_155_),
    .Z(_162_)
  );
  AOI21_X1 _356_ (
    .A(_156_),
    .B1(_161_),
    .B2(_162_),
    .ZN(_163_)
  );
  NOR2_X1 _357_ (
    .A1(x_3_),
    .A2(_153_),
    .ZN(_164_)
  );
  XOR2_X1 _358_ (
    .A(x_3_),
    .B(_153_),
    .Z(_165_)
  );
  OAI21_X1 _359_ (
    .A(_154_),
    .B1(_163_),
    .B2(_164_),
    .ZN(_166_)
  );
  XNOR2_X1 _360_ (
    .A(x_4_),
    .B(_151_),
    .ZN(_167_)
  );
  INV_X1 _361_ (
    .A(_167_),
    .ZN(_168_)
  );
  AOI21_X1 _362_ (
    .A(_152_),
    .B1(_166_),
    .B2(_168_),
    .ZN(_169_)
  );
  XNOR2_X1 _363_ (
    .A(_093_),
    .B(_149_),
    .ZN(_170_)
  );
  INV_X1 _364_ (
    .A(_170_),
    .ZN(_171_)
  );
  OAI21_X1 _365_ (
    .A(_150_),
    .B1(_169_),
    .B2(_171_),
    .ZN(_172_)
  );
  OAI21_X1 _366_ (
    .A(_148_),
    .B1(stato_5_),
    .B2(_092_),
    .ZN(_173_)
  );
  AND2_X1 _367_ (
    .A1(x_6_),
    .A2(_173_),
    .ZN(_174_)
  );
  OR2_X1 _368_ (
    .A1(x_6_),
    .A2(_173_),
    .ZN(_175_)
  );
  XNOR2_X1 _369_ (
    .A(x_6_),
    .B(_173_),
    .ZN(_176_)
  );
  AOI211_X1 _370_ (
    .A(_136_),
    .B(_174_),
    .C1(_175_),
    .C2(_172_),
    .ZN(_177_)
  );
  OAI21_X1 _371_ (
    .A(_139_),
    .B1(_147_),
    .B2(_177_),
    .ZN(_082_)
  );
  NAND3_X1 _372_ (
    .A1(cont_5_),
    .A2(cont_6_),
    .A3(_129_),
    .ZN(_178_)
  );
  XOR2_X1 _373_ (
    .A(cont_7_),
    .B(_178_),
    .Z(_179_)
  );
  NOR2_X1 _374_ (
    .A1(_109_),
    .A2(_179_),
    .ZN(_180_)
  );
  OAI221_X1 _375_ (
    .A(_116_),
    .B1(_120_),
    .B2(_180_),
    .C1(_119_),
    .C2(cont_7_),
    .ZN(_181_)
  );
  OAI21_X1 _376_ (
    .A(_181_),
    .B1(_116_),
    .B2(_091_),
    .ZN(_081_)
  );
  MUX2_X1 _377_ (
    .A(t_6_),
    .B(x_5_),
    .S(stato_6_),
    .Z(_080_)
  );
  AOI21_X1 _378_ (
    .A(cont_6_),
    .B1(_129_),
    .B2(cont_5_),
    .ZN(_182_)
  );
  NAND2_X1 _379_ (
    .A1(stato_3_),
    .A2(_178_),
    .ZN(_183_)
  );
  NOR2_X1 _380_ (
    .A1(_182_),
    .A2(_183_),
    .ZN(_184_)
  );
  OAI221_X1 _381_ (
    .A(_116_),
    .B1(_120_),
    .B2(_184_),
    .C1(_119_),
    .C2(cont_6_),
    .ZN(_185_)
  );
  OAI21_X1 _382_ (
    .A(_185_),
    .B1(_116_),
    .B2(_095_),
    .ZN(_079_)
  );
  NAND3_X1 _383_ (
    .A1(mar_3_),
    .A2(stato_3_),
    .A3(_113_),
    .ZN(_186_)
  );
  NAND2_X1 _384_ (
    .A1(_107_),
    .A2(stato_4_),
    .ZN(_187_)
  );
  NAND2_X1 _385_ (
    .A1(_186_),
    .A2(_187_),
    .ZN(_188_)
  );
  NOR2_X1 _386_ (
    .A1(stato_6_),
    .A2(stato_3_),
    .ZN(_189_)
  );
  NOR2_X1 _387_ (
    .A1(_188_),
    .A2(_189_),
    .ZN(_190_)
  );
  AOI21_X1 _388_ (
    .A(mar_3_),
    .B1(_113_),
    .B2(_190_),
    .ZN(_191_)
  );
  AOI21_X1 _389_ (
    .A(_188_),
    .B1(_115_),
    .B2(_094_),
    .ZN(_192_)
  );
  OAI21_X1 _390_ (
    .A(_192_),
    .B1(_189_),
    .B2(_113_),
    .ZN(_193_)
  );
  NOR2_X1 _391_ (
    .A1(_096_),
    .A2(_193_),
    .ZN(_194_)
  );
  NOR2_X1 _392_ (
    .A1(_191_),
    .A2(_194_),
    .ZN(_078_)
  );
  OR3_X1 _393_ (
    .A1(_108_),
    .A2(_188_),
    .A3(_189_),
    .ZN(_195_)
  );
  OAI21_X1 _394_ (
    .A(_195_),
    .B1(_192_),
    .B2(_097_),
    .ZN(_077_)
  );
  NOR3_X1 _395_ (
    .A1(_115_),
    .A2(_120_),
    .A3(_188_),
    .ZN(_196_)
  );
  MUX2_X1 _396_ (
    .A(cont_7_),
    .B(_180_),
    .S(_196_),
    .Z(_076_)
  );
  AOI21_X1 _397_ (
    .A(mar_1_),
    .B1(_192_),
    .B2(mar_0_),
    .ZN(_197_)
  );
  OAI21_X1 _398_ (
    .A(_112_),
    .B1(stato_3_),
    .B2(stato_6_),
    .ZN(_198_)
  );
  AOI21_X1 _399_ (
    .A(_197_),
    .B1(_198_),
    .B2(_192_),
    .ZN(_075_)
  );
  AOI211_X1 _400_ (
    .A(_112_),
    .B(_188_),
    .C1(_115_),
    .C2(_094_),
    .ZN(_199_)
  );
  OAI21_X1 _401_ (
    .A(_193_),
    .B1(_199_),
    .B2(mar_2_),
    .ZN(_200_)
  );
  INV_X1 _402_ (
    .A(_200_),
    .ZN(_074_)
  );
  NAND2_X1 _403_ (
    .A1(_141_),
    .A2(_143_),
    .ZN(_201_)
  );
  NAND2_X1 _404_ (
    .A1(_136_),
    .A2(_201_),
    .ZN(_202_)
  );
  AOI22_X1 _405_ (
    .A1(y_0_),
    .A2(stato_5_),
    .B1(_137_),
    .B2(x_0_),
    .ZN(_203_)
  );
  INV_X1 _406_ (
    .A(_203_),
    .ZN(_204_)
  );
  AOI21_X1 _407_ (
    .A(_138_),
    .B1(_159_),
    .B2(_204_),
    .ZN(_205_)
  );
  AOI22_X1 _408_ (
    .A1(_099_),
    .A2(_138_),
    .B1(_202_),
    .B2(_205_),
    .ZN(_073_)
  );
  NOR2_X1 _409_ (
    .A1(cont_0_),
    .A2(_109_),
    .ZN(_206_)
  );
  MUX2_X1 _410_ (
    .A(cont_0_),
    .B(_206_),
    .S(_196_),
    .Z(_072_)
  );
  OAI21_X1 _411_ (
    .A(stato_3_),
    .B1(cont_1_),
    .B2(cont_0_),
    .ZN(_207_)
  );
  AOI21_X1 _412_ (
    .A(_207_),
    .B1(cont_1_),
    .B2(cont_0_),
    .ZN(_208_)
  );
  MUX2_X1 _413_ (
    .A(cont_1_),
    .B(_208_),
    .S(_196_),
    .Z(_071_)
  );
  MUX2_X1 _414_ (
    .A(cont_2_),
    .B(_123_),
    .S(_196_),
    .Z(_070_)
  );
  MUX2_X1 _415_ (
    .A(cont_3_),
    .B(_127_),
    .S(_196_),
    .Z(_069_)
  );
  MUX2_X1 _416_ (
    .A(cont_4_),
    .B(_131_),
    .S(_196_),
    .Z(_068_)
  );
  MUX2_X1 _417_ (
    .A(cont_5_),
    .B(_134_),
    .S(_196_),
    .Z(_067_)
  );
  MUX2_X1 _418_ (
    .A(cont_6_),
    .B(_184_),
    .S(_196_),
    .Z(_066_)
  );
  NAND2_X1 _419_ (
    .A1(stato_1_),
    .A2(_201_),
    .ZN(_209_)
  );
  OAI21_X1 _420_ (
    .A(_209_),
    .B1(stato_1_),
    .B2(_100_),
    .ZN(_065_)
  );
  OAI22_X1 _421_ (
    .A1(mar_3_),
    .A2(_098_),
    .B1(_108_),
    .B2(_140_),
    .ZN(_210_)
  );
  AOI21_X1 _422_ (
    .A(_210_),
    .B1(_140_),
    .B2(_108_),
    .ZN(_211_)
  );
  MUX2_X1 _423_ (
    .A(y_1_),
    .B(_211_),
    .S(stato_1_),
    .Z(_064_)
  );
  OAI22_X1 _424_ (
    .A1(stato_1_),
    .A2(_101_),
    .B1(_142_),
    .B2(_209_),
    .ZN(_063_)
  );
  XOR2_X1 _425_ (
    .A(_159_),
    .B(_160_),
    .Z(_212_)
  );
  MUX2_X1 _426_ (
    .A(_211_),
    .B(_212_),
    .S(_137_),
    .Z(_213_)
  );
  MUX2_X1 _427_ (
    .A(_213_),
    .B(x_1_),
    .S(_138_),
    .Z(_062_)
  );
  XNOR2_X1 _428_ (
    .A(_161_),
    .B(_162_),
    .ZN(_214_)
  );
  OAI22_X1 _429_ (
    .A1(_142_),
    .A2(_202_),
    .B1(_214_),
    .B2(_136_),
    .ZN(_215_)
  );
  MUX2_X1 _430_ (
    .A(_215_),
    .B(x_2_),
    .S(_138_),
    .Z(_061_)
  );
  MUX2_X1 _431_ (
    .A(y_3_),
    .B(_144_),
    .S(stato_1_),
    .Z(_060_)
  );
  NAND2_X1 _432_ (
    .A1(x_3_),
    .A2(_138_),
    .ZN(_216_)
  );
  XNOR2_X1 _433_ (
    .A(_163_),
    .B(_165_),
    .ZN(_217_)
  );
  OAI21_X1 _434_ (
    .A(_146_),
    .B1(_217_),
    .B2(_136_),
    .ZN(_218_)
  );
  NAND2_X1 _435_ (
    .A1(_216_),
    .A2(_218_),
    .ZN(_059_)
  );
  MUX2_X1 _436_ (
    .A(t_1_),
    .B(x_0_),
    .S(stato_6_),
    .Z(_058_)
  );
  MUX2_X1 _437_ (
    .A(t_2_),
    .B(x_1_),
    .S(stato_6_),
    .Z(_057_)
  );
  MUX2_X1 _438_ (
    .A(t_3_),
    .B(x_2_),
    .S(stato_6_),
    .Z(_056_)
  );
  MUX2_X1 _439_ (
    .A(t_4_),
    .B(x_3_),
    .S(stato_6_),
    .Z(_055_)
  );
  MUX2_X1 _440_ (
    .A(t_5_),
    .B(x_4_),
    .S(stato_6_),
    .Z(_054_)
  );
  NAND2_X1 _441_ (
    .A1(x_4_),
    .A2(_138_),
    .ZN(_219_)
  );
  XNOR2_X1 _442_ (
    .A(_166_),
    .B(_167_),
    .ZN(_220_)
  );
  OAI21_X1 _443_ (
    .A(_146_),
    .B1(_220_),
    .B2(_136_),
    .ZN(_221_)
  );
  NAND2_X1 _444_ (
    .A1(_219_),
    .A2(_221_),
    .ZN(_053_)
  );
  NAND2_X1 _445_ (
    .A1(x_5_),
    .A2(_138_),
    .ZN(_222_)
  );
  XNOR2_X1 _446_ (
    .A(_169_),
    .B(_170_),
    .ZN(_223_)
  );
  OAI21_X1 _447_ (
    .A(_146_),
    .B1(_223_),
    .B2(_136_),
    .ZN(_224_)
  );
  NAND2_X1 _448_ (
    .A1(_222_),
    .A2(_224_),
    .ZN(_052_)
  );
  NAND2_X1 _449_ (
    .A1(x_6_),
    .A2(_138_),
    .ZN(_225_)
  );
  XNOR2_X1 _450_ (
    .A(_172_),
    .B(_176_),
    .ZN(_226_)
  );
  OAI21_X1 _451_ (
    .A(_146_),
    .B1(_226_),
    .B2(_136_),
    .ZN(_227_)
  );
  NAND2_X1 _452_ (
    .A1(_225_),
    .A2(_227_),
    .ZN(_051_)
  );
  OAI221_X1 _453_ (
    .A(_116_),
    .B1(_120_),
    .B2(_206_),
    .C1(_119_),
    .C2(cont_0_),
    .ZN(_228_)
  );
  OAI21_X1 _454_ (
    .A(_228_),
    .B1(_116_),
    .B2(_105_),
    .ZN(_050_)
  );
  OAI221_X1 _455_ (
    .A(_116_),
    .B1(_120_),
    .B2(_208_),
    .C1(_119_),
    .C2(cont_1_),
    .ZN(_229_)
  );
  OAI21_X1 _456_ (
    .A(_229_),
    .B1(_116_),
    .B2(_106_),
    .ZN(_049_)
  );
  AOI21_X1 _457_ (
    .A(_114_),
    .B1(stato_4_),
    .B2(start),
    .ZN(_230_)
  );
  INV_X1 _458_ (
    .A(_230_),
    .ZN(_000_)
  );
  OAI21_X1 _459_ (
    .A(_110_),
    .B1(_186_),
    .B2(_107_),
    .ZN(_001_)
  );
  OAI211_X1 _460_ (
    .A(_111_),
    .B(_187_),
    .C1(_186_),
    .C2(start),
    .ZN(_002_)
  );
  INV_X1 _461_ (
    .A(reset),
    .ZN(_005_)
  );
  INV_X1 _462_ (
    .A(reset),
    .ZN(_006_)
  );
  INV_X1 _463_ (
    .A(reset),
    .ZN(_007_)
  );
  INV_X1 _464_ (
    .A(reset),
    .ZN(_008_)
  );
  INV_X1 _465_ (
    .A(reset),
    .ZN(_009_)
  );
  INV_X1 _466_ (
    .A(reset),
    .ZN(_010_)
  );
  INV_X1 _467_ (
    .A(reset),
    .ZN(_011_)
  );
  INV_X1 _468_ (
    .A(reset),
    .ZN(_012_)
  );
  INV_X1 _469_ (
    .A(reset),
    .ZN(_013_)
  );
  INV_X1 _470_ (
    .A(reset),
    .ZN(_014_)
  );
  INV_X1 _471_ (
    .A(reset),
    .ZN(_015_)
  );
  INV_X1 _472_ (
    .A(reset),
    .ZN(_016_)
  );
  INV_X1 _473_ (
    .A(reset),
    .ZN(_017_)
  );
  INV_X1 _474_ (
    .A(reset),
    .ZN(_018_)
  );
  INV_X1 _475_ (
    .A(reset),
    .ZN(_019_)
  );
  INV_X1 _476_ (
    .A(reset),
    .ZN(_020_)
  );
  INV_X1 _477_ (
    .A(reset),
    .ZN(_021_)
  );
  INV_X1 _478_ (
    .A(reset),
    .ZN(_022_)
  );
  INV_X1 _479_ (
    .A(reset),
    .ZN(_023_)
  );
  INV_X1 _480_ (
    .A(reset),
    .ZN(_024_)
  );
  INV_X1 _481_ (
    .A(reset),
    .ZN(_025_)
  );
  INV_X1 _482_ (
    .A(reset),
    .ZN(_026_)
  );
  INV_X1 _483_ (
    .A(reset),
    .ZN(_027_)
  );
  INV_X1 _484_ (
    .A(reset),
    .ZN(_028_)
  );
  INV_X1 _485_ (
    .A(reset),
    .ZN(_029_)
  );
  INV_X1 _486_ (
    .A(reset),
    .ZN(_030_)
  );
  INV_X1 _487_ (
    .A(reset),
    .ZN(_031_)
  );
  INV_X1 _488_ (
    .A(reset),
    .ZN(_032_)
  );
  INV_X1 _489_ (
    .A(reset),
    .ZN(_033_)
  );
  INV_X1 _490_ (
    .A(reset),
    .ZN(_034_)
  );
  INV_X1 _491_ (
    .A(reset),
    .ZN(_035_)
  );
  INV_X1 _492_ (
    .A(reset),
    .ZN(_036_)
  );
  INV_X1 _493_ (
    .A(reset),
    .ZN(_037_)
  );
  INV_X1 _494_ (
    .A(reset),
    .ZN(_038_)
  );
  INV_X1 _495_ (
    .A(reset),
    .ZN(_039_)
  );
  INV_X1 _496_ (
    .A(reset),
    .ZN(_040_)
  );
  INV_X1 _497_ (
    .A(reset),
    .ZN(_041_)
  );
  INV_X1 _498_ (
    .A(reset),
    .ZN(_042_)
  );
  INV_X1 _499_ (
    .A(reset),
    .ZN(_043_)
  );
  INV_X1 _500_ (
    .A(reset),
    .ZN(_044_)
  );
  INV_X1 _501_ (
    .A(reset),
    .ZN(_045_)
  );
  INV_X1 _502_ (
    .A(reset),
    .ZN(_046_)
  );
  INV_X1 _503_ (
    .A(reset),
    .ZN(_047_)
  );
  INV_X1 _504_ (
    .A(reset),
    .ZN(_048_)
  );
  DFFR_X1 _505_ (
    .CK(clock),
    .D(_077_),
    .Q(mar_0_),
    .QN(_003_),
    .RN(_039_)
  );
  DFFR_X1 _506_ (
    .CK(clock),
    .D(_075_),
    .Q(mar_1_),
    .QN(_241_),
    .RN(_037_)
  );
  DFFR_X1 _507_ (
    .CK(clock),
    .D(_074_),
    .Q(mar_2_),
    .QN(_242_),
    .RN(_036_)
  );
  DFFR_X1 _508_ (
    .CK(clock),
    .D(_078_),
    .Q(mar_3_),
    .QN(_239_),
    .RN(_040_)
  );
  DFFR_X1 _509_ (
    .CK(clock),
    .D(_072_),
    .Q(cont_0_),
    .QN(_245_),
    .RN(_033_)
  );
  DFFR_X1 _510_ (
    .CK(clock),
    .D(_071_),
    .Q(cont_1_),
    .QN(_246_),
    .RN(_032_)
  );
  DFFR_X1 _511_ (
    .CK(clock),
    .D(_070_),
    .Q(cont_2_),
    .QN(_247_),
    .RN(_031_)
  );
  DFFR_X1 _512_ (
    .CK(clock),
    .D(_069_),
    .Q(cont_3_),
    .QN(_249_),
    .RN(_029_)
  );
  DFFR_X1 _513_ (
    .CK(clock),
    .D(_068_),
    .Q(cont_4_),
    .QN(_250_),
    .RN(_028_)
  );
  DFFR_X1 _514_ (
    .CK(clock),
    .D(_067_),
    .Q(cont_5_),
    .QN(_251_),
    .RN(_027_)
  );
  DFFR_X1 _515_ (
    .CK(clock),
    .D(_066_),
    .Q(cont_6_),
    .QN(_252_),
    .RN(_026_)
  );
  DFFR_X1 _516_ (
    .CK(clock),
    .D(_076_),
    .Q(cont_7_),
    .QN(_240_),
    .RN(_038_)
  );
  DFFR_X1 _517_ (
    .CK(clock),
    .D(_065_),
    .Q(y_0_),
    .QN(_253_),
    .RN(_025_)
  );
  DFFR_X1 _518_ (
    .CK(clock),
    .D(_064_),
    .Q(y_1_),
    .QN(_254_),
    .RN(_024_)
  );
  DFFR_X1 _519_ (
    .CK(clock),
    .D(_063_),
    .Q(y_2_),
    .QN(_255_),
    .RN(_023_)
  );
  DFFR_X1 _520_ (
    .CK(clock),
    .D(_060_),
    .Q(y_3_),
    .QN(_258_),
    .RN(_020_)
  );
  DFFR_X1 _521_ (
    .CK(clock),
    .D(_058_),
    .Q(t_1_),
    .QN(_260_),
    .RN(_018_)
  );
  DFFR_X1 _522_ (
    .CK(clock),
    .D(_057_),
    .Q(t_2_),
    .QN(_261_),
    .RN(_017_)
  );
  DFFR_X1 _523_ (
    .CK(clock),
    .D(_056_),
    .Q(t_3_),
    .QN(_262_),
    .RN(_016_)
  );
  DFFR_X1 _524_ (
    .CK(clock),
    .D(_055_),
    .Q(t_4_),
    .QN(_263_),
    .RN(_015_)
  );
  DFFR_X1 _525_ (
    .CK(clock),
    .D(_054_),
    .Q(t_5_),
    .QN(_264_),
    .RN(_014_)
  );
  DFFR_X1 _526_ (
    .CK(clock),
    .D(_080_),
    .Q(t_6_),
    .QN(_237_),
    .RN(_042_)
  );
  DFFR_X1 _527_ (
    .CK(clock),
    .D(_050_),
    .Q(punti_retta_0_),
    .QN(_273_),
    .RN(_005_)
  );
  DFFR_X1 _528_ (
    .CK(clock),
    .D(_049_),
    .Q(punti_retta_1_),
    .QN(_274_),
    .RN(_004_)
  );
  DFFR_X1 _529_ (
    .CK(clock),
    .D(_086_),
    .Q(punti_retta_2_),
    .QN(_231_),
    .RN(_048_)
  );
  DFFR_X1 _530_ (
    .CK(clock),
    .D(_085_),
    .Q(punti_retta_3_),
    .QN(_232_),
    .RN(_047_)
  );
  DFFR_X1 _531_ (
    .CK(clock),
    .D(_084_),
    .Q(punti_retta_4_),
    .QN(_233_),
    .RN(_046_)
  );
  DFFR_X1 _532_ (
    .CK(clock),
    .D(_083_),
    .Q(punti_retta_5_),
    .QN(_234_),
    .RN(_045_)
  );
  DFFR_X1 _533_ (
    .CK(clock),
    .D(_079_),
    .Q(punti_retta_6_),
    .QN(_238_),
    .RN(_041_)
  );
  DFFR_X1 _534_ (
    .CK(clock),
    .D(_081_),
    .Q(punti_retta_7_),
    .QN(_236_),
    .RN(_043_)
  );
  DFFR_X1 _535_ (
    .CK(clock),
    .D(_073_),
    .Q(x_0_),
    .QN(_244_),
    .RN(_034_)
  );
  DFFR_X1 _536_ (
    .CK(clock),
    .D(_062_),
    .Q(x_1_),
    .QN(_256_),
    .RN(_022_)
  );
  DFFR_X1 _537_ (
    .CK(clock),
    .D(_061_),
    .Q(x_2_),
    .QN(_257_),
    .RN(_021_)
  );
  DFFR_X1 _538_ (
    .CK(clock),
    .D(_059_),
    .Q(x_3_),
    .QN(_259_),
    .RN(_019_)
  );
  DFFR_X1 _539_ (
    .CK(clock),
    .D(_053_),
    .Q(x_4_),
    .QN(_265_),
    .RN(_013_)
  );
  DFFR_X1 _540_ (
    .CK(clock),
    .D(_052_),
    .Q(x_5_),
    .QN(_266_),
    .RN(_012_)
  );
  DFFR_X1 _541_ (
    .CK(clock),
    .D(_051_),
    .Q(x_6_),
    .QN(_267_),
    .RN(_011_)
  );
  DFFR_X1 _542_ (
    .CK(clock),
    .D(_082_),
    .Q(x_7_),
    .QN(_235_),
    .RN(_044_)
  );
  DFFS_X1 _543_ (
    .CK(clock),
    .D(_const0_),
    .Q(stato_0_),
    .QN(_269_),
    .SN(_009_)
  );
  DFFR_X1 _544_ (
    .CK(clock),
    .D(stato_6_),
    .Q(stato_1_),
    .QN(_270_),
    .RN(_008_)
  );
  DFFR_X1 _545_ (
    .CK(clock),
    .D(_000_),
    .Q(stato_2_),
    .QN(_271_),
    .RN(_007_)
  );
  DFFR_X1 _546_ (
    .CK(clock),
    .D(_001_),
    .Q(stato_3_),
    .QN(_272_),
    .RN(_006_)
  );
  DFFR_X1 _547_ (
    .CK(clock),
    .D(_002_),
    .Q(stato_4_),
    .QN(_243_),
    .RN(_035_)
  );
  DFFR_X1 _548_ (
    .CK(clock),
    .D(stato_1_),
    .Q(stato_5_),
    .QN(_268_),
    .RN(_010_)
  );
  DFFR_X1 _549_ (
    .CK(clock),
    .D(stato_2_),
    .Q(stato_6_),
    .QN(_248_),
    .RN(_030_)
  );
endmodule
