/* Generated by Yosys 0.65 (git sha1 9d0cdb855, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module b08(CK, RESET, START, I_0_, I_1_, I_2_, I_3_, I_4_, I_5_, I_6_, I_7_, O_0_, O_1_, O_2_, O_3_, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  input CK;
  wire CK;
  input RESET;
  wire RESET;
  input START;
  wire START;
    input I_0_;
  input I_1_;
  input I_2_;
  input I_3_;
  input I_4_;
  input I_5_;
  input I_6_;
  input I_7_;
    wire I_0_;
  wire I_1_;
  wire I_2_;
  wire I_3_;
  wire I_4_;
  wire I_5_;
  wire I_6_;
  wire I_7_;
    output O_0_;
  output O_1_;
  output O_2_;
  output O_3_;
    wire O_0_;
  wire O_1_;
  wire O_2_;
  wire O_3_;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire IN_R_0_;
  wire IN_R_1_;
  wire IN_R_2_;
  wire IN_R_3_;
  wire IN_R_4_;
  wire IN_R_5_;
  wire IN_R_6_;
  wire IN_R_7_;
  wire MAR_0_;
  wire MAR_1_;
  wire MAR_2_;
  wire MAR_3_;
  wire MAR_4_;
  wire MAR_5_;
  wire MAR_6_;
  wire MAR_7_;
  wire OUT_R_0_;
  wire OUT_R_1_;
  wire OUT_R_2_;
  wire OUT_R_3_;
  wire STATO_0_;
  wire STATO_1_;
  wire STATO_2_;
  wire STATO_3_;
  NAND2_X1 _164_ (
    .A1(_057_),
    .A2(_072_),
    .ZN(_093_)
  );
  NOR2_X1 _165_ (
    .A1(_064_),
    .A2(_073_),
    .ZN(_094_)
  );
  AOI22_X1 _166_ (
    .A1(MAR_5_),
    .A2(_081_),
    .B1(_093_),
    .B2(_094_),
    .ZN(_095_)
  );
  INV_X1 _167_ (
    .A(_095_),
    .ZN(_049_)
  );
  MUX2_X1 _168_ (
    .A(O_0_),
    .B(OUT_R_0_),
    .S(_087_),
    .Z(_048_)
  );
  MUX2_X1 _169_ (
    .A(O_1_),
    .B(OUT_R_1_),
    .S(_087_),
    .Z(_047_)
  );
  MUX2_X1 _170_ (
    .A(O_2_),
    .B(OUT_R_2_),
    .S(_087_),
    .Z(_046_)
  );
  MUX2_X1 _171_ (
    .A(IN_R_0_),
    .B(I_0_),
    .S(STATO_2_),
    .Z(_045_)
  );
  MUX2_X1 _172_ (
    .A(IN_R_1_),
    .B(I_1_),
    .S(STATO_2_),
    .Z(_044_)
  );
  MUX2_X1 _173_ (
    .A(IN_R_2_),
    .B(I_2_),
    .S(STATO_2_),
    .Z(_043_)
  );
  NOR2_X1 _174_ (
    .A1(_133_),
    .A2(STATO_1_),
    .ZN(_096_)
  );
  AOI21_X1 _175_ (
    .A(_004_),
    .B1(MAR_0_),
    .B2(MAR_1_),
    .ZN(_097_)
  );
  OAI21_X1 _176_ (
    .A(IN_R_7_),
    .B1(_134_),
    .B2(MAR_2_),
    .ZN(_098_)
  );
  NOR2_X1 _177_ (
    .A1(_134_),
    .A2(MAR_0_),
    .ZN(_099_)
  );
  NOR2_X1 _178_ (
    .A1(MAR_1_),
    .A2(_062_),
    .ZN(_100_)
  );
  NOR2_X1 _179_ (
    .A1(_066_),
    .A2(_100_),
    .ZN(_101_)
  );
  OAI21_X1 _180_ (
    .A(_004_),
    .B1(_062_),
    .B2(MAR_1_),
    .ZN(_102_)
  );
  OAI21_X1 _181_ (
    .A(IN_R_6_),
    .B1(_099_),
    .B2(_102_),
    .ZN(_103_)
  );
  AOI21_X1 _182_ (
    .A(_097_),
    .B1(_098_),
    .B2(_103_),
    .ZN(_104_)
  );
  NOR3_X1 _183_ (
    .A1(IN_R_7_),
    .A2(_070_),
    .A3(_088_),
    .ZN(_105_)
  );
  OAI21_X1 _184_ (
    .A(_105_),
    .B1(_136_),
    .B2(MAR_1_),
    .ZN(_106_)
  );
  NAND3_X1 _185_ (
    .A1(MAR_1_),
    .A2(MAR_0_),
    .A3(_004_),
    .ZN(_107_)
  );
  OAI21_X1 _186_ (
    .A(STATO_1_),
    .B1(_107_),
    .B2(IN_R_4_),
    .ZN(_108_)
  );
  INV_X1 _187_ (
    .A(_108_),
    .ZN(_109_)
  );
  NOR2_X1 _188_ (
    .A1(_136_),
    .A2(IN_R_1_),
    .ZN(_110_)
  );
  OAI21_X1 _189_ (
    .A(_099_),
    .B1(_110_),
    .B2(IN_R_0_),
    .ZN(_111_)
  );
  NOR3_X1 _190_ (
    .A1(_134_),
    .A2(_136_),
    .A3(MAR_0_),
    .ZN(_112_)
  );
  NOR2_X1 _191_ (
    .A1(MAR_1_),
    .A2(IN_R_5_),
    .ZN(_113_)
  );
  OAI22_X1 _192_ (
    .A1(_136_),
    .A2(IN_R_5_),
    .B1(_112_),
    .B2(_113_),
    .ZN(_114_)
  );
  AOI21_X1 _193_ (
    .A(_136_),
    .B1(IN_R_2_),
    .B2(_062_),
    .ZN(_115_)
  );
  OAI21_X1 _194_ (
    .A(_084_),
    .B1(IN_R_2_),
    .B2(IN_R_1_),
    .ZN(_116_)
  );
  NOR2_X1 _195_ (
    .A1(IN_R_2_),
    .A2(_088_),
    .ZN(_117_)
  );
  AOI21_X1 _196_ (
    .A(IN_R_6_),
    .B1(_004_),
    .B2(_083_),
    .ZN(_118_)
  );
  OAI22_X1 _197_ (
    .A1(_136_),
    .A2(_100_),
    .B1(_117_),
    .B2(_118_),
    .ZN(_119_)
  );
  OAI211_X1 _198_ (
    .A(MAR_1_),
    .B(IN_R_4_),
    .C1(_062_),
    .C2(MAR_2_),
    .ZN(_120_)
  );
  OAI21_X1 _199_ (
    .A(_134_),
    .B1(MAR_2_),
    .B2(MAR_0_),
    .ZN(_121_)
  );
  OAI21_X1 _200_ (
    .A(_061_),
    .B1(MAR_2_),
    .B2(_134_),
    .ZN(_122_)
  );
  NAND4_X1 _201_ (
    .A1(_106_),
    .A2(_109_),
    .A3(_114_),
    .A4(_120_),
    .ZN(_123_)
  );
  OAI221_X1 _202_ (
    .A(_111_),
    .B1(_115_),
    .B2(_116_),
    .C1(_121_),
    .C2(IN_R_0_),
    .ZN(_124_)
  );
  OAI21_X1 _203_ (
    .A(_119_),
    .B1(_122_),
    .B2(_070_),
    .ZN(_125_)
  );
  NOR4_X1 _204_ (
    .A1(_104_),
    .A2(_123_),
    .A3(_124_),
    .A4(_125_),
    .ZN(_126_)
  );
  OAI22_X1 _205_ (
    .A1(_097_),
    .A2(_101_),
    .B1(_126_),
    .B2(_096_),
    .ZN(_127_)
  );
  AOI21_X1 _206_ (
    .A(_096_),
    .B1(_127_),
    .B2(_135_),
    .ZN(_042_)
  );
  MUX2_X1 _207_ (
    .A(IN_R_3_),
    .B(I_3_),
    .S(STATO_2_),
    .Z(_041_)
  );
  MUX2_X1 _208_ (
    .A(IN_R_4_),
    .B(I_4_),
    .S(STATO_2_),
    .Z(_040_)
  );
  MUX2_X1 _209_ (
    .A(IN_R_5_),
    .B(I_5_),
    .S(STATO_2_),
    .Z(_039_)
  );
  MUX2_X1 _210_ (
    .A(IN_R_6_),
    .B(I_6_),
    .S(STATO_2_),
    .Z(_038_)
  );
  AOI21_X1 _211_ (
    .A(MAR_6_),
    .B1(STATO_3_),
    .B2(_073_),
    .ZN(_128_)
  );
  NOR2_X1 _212_ (
    .A1(_079_),
    .A2(_128_),
    .ZN(_037_)
  );
  OAI21_X1 _213_ (
    .A(_099_),
    .B1(_126_),
    .B2(_096_),
    .ZN(_129_)
  );
  AOI21_X1 _214_ (
    .A(_096_),
    .B1(_129_),
    .B2(_058_),
    .ZN(_036_)
  );
  OAI22_X1 _215_ (
    .A1(_136_),
    .A2(_062_),
    .B1(_096_),
    .B2(_126_),
    .ZN(_130_)
  );
  AOI21_X1 _216_ (
    .A(_096_),
    .B1(_130_),
    .B2(_059_),
    .ZN(_035_)
  );
  NOR2_X1 _217_ (
    .A1(_100_),
    .A2(_112_),
    .ZN(_131_)
  );
  OAI221_X1 _218_ (
    .A(_131_),
    .B1(_126_),
    .B2(_096_),
    .C1(MAR_2_),
    .C2(_099_),
    .ZN(_132_)
  );
  AOI21_X1 _219_ (
    .A(_096_),
    .B1(_132_),
    .B2(_060_),
    .ZN(_034_)
  );
  MUX2_X1 _220_ (
    .A(STATO_3_),
    .B(_081_),
    .S(MAR_0_),
    .Z(_033_)
  );
  OAI21_X1 _221_ (
    .A(_063_),
    .B1(_065_),
    .B2(_086_),
    .ZN(_003_)
  );
  OR2_X1 _222_ (
    .A1(STATO_2_),
    .A2(_078_),
    .ZN(_002_)
  );
  NOR2_X1 _223_ (
    .A1(_065_),
    .A2(_067_),
    .ZN(_000_)
  );
  AOI21_X1 _224_ (
    .A(START),
    .B1(_067_),
    .B2(_086_),
    .ZN(_001_)
  );
  INV_X1 _225_ (
    .A(RESET),
    .ZN(_006_)
  );
  INV_X1 _226_ (
    .A(RESET),
    .ZN(_007_)
  );
  INV_X1 _227_ (
    .A(RESET),
    .ZN(_008_)
  );
  INV_X1 _228_ (
    .A(RESET),
    .ZN(_009_)
  );
  INV_X1 _229_ (
    .A(RESET),
    .ZN(_010_)
  );
  INV_X1 _230_ (
    .A(RESET),
    .ZN(_011_)
  );
  INV_X1 _231_ (
    .A(RESET),
    .ZN(_012_)
  );
  INV_X1 _232_ (
    .A(RESET),
    .ZN(_013_)
  );
  INV_X1 _233_ (
    .A(RESET),
    .ZN(_014_)
  );
  INV_X1 _234_ (
    .A(RESET),
    .ZN(_015_)
  );
  INV_X1 _235_ (
    .A(RESET),
    .ZN(_016_)
  );
  INV_X1 _236_ (
    .A(RESET),
    .ZN(_017_)
  );
  INV_X1 _237_ (
    .A(RESET),
    .ZN(_018_)
  );
  INV_X1 _238_ (
    .A(RESET),
    .ZN(_019_)
  );
  INV_X1 _239_ (
    .A(RESET),
    .ZN(_020_)
  );
  INV_X1 _240_ (
    .A(RESET),
    .ZN(_021_)
  );
  INV_X1 _241_ (
    .A(RESET),
    .ZN(_022_)
  );
  INV_X1 _242_ (
    .A(RESET),
    .ZN(_023_)
  );
  INV_X1 _243_ (
    .A(RESET),
    .ZN(_024_)
  );
  INV_X1 _244_ (
    .A(RESET),
    .ZN(_025_)
  );
  INV_X1 _245_ (
    .A(RESET),
    .ZN(_026_)
  );
  INV_X1 _246_ (
    .A(RESET),
    .ZN(_027_)
  );
  INV_X1 _247_ (
    .A(RESET),
    .ZN(_028_)
  );
  INV_X1 _248_ (
    .A(RESET),
    .ZN(_029_)
  );
  INV_X1 _249_ (
    .A(RESET),
    .ZN(_030_)
  );
  INV_X1 _250_ (
    .A(RESET),
    .ZN(_031_)
  );
  INV_X1 _251_ (
    .A(RESET),
    .ZN(_032_)
  );
  INV_X1 _252_ (
    .A(STATO_2_),
    .ZN(_133_)
  );
  INV_X1 _253_ (
    .A(MAR_1_),
    .ZN(_134_)
  );
  INV_X1 _254_ (
    .A(OUT_R_3_),
    .ZN(_135_)
  );
  INV_X1 _255_ (
    .A(MAR_2_),
    .ZN(_136_)
  );
  INV_X1 _256_ (
    .A(MAR_5_),
    .ZN(_057_)
  );
  INV_X1 _257_ (
    .A(OUT_R_0_),
    .ZN(_058_)
  );
  INV_X1 _258_ (
    .A(OUT_R_1_),
    .ZN(_059_)
  );
  INV_X1 _259_ (
    .A(OUT_R_2_),
    .ZN(_060_)
  );
  INV_X1 _260_ (
    .A(IN_R_3_),
    .ZN(_061_)
  );
  INV_X1 _261_ (
    .A(MAR_0_),
    .ZN(_062_)
  );
  INV_X1 _262_ (
    .A(STATO_1_),
    .ZN(_063_)
  );
  INV_X1 _263_ (
    .A(STATO_3_),
    .ZN(_064_)
  );
  INV_X1 _264_ (
    .A(START),
    .ZN(_065_)
  );
  INV_X1 _265_ (
    .A(_004_),
    .ZN(_066_)
  );
  INV_X1 _266_ (
    .A(STATO_0_),
    .ZN(_067_)
  );
  INV_X1 _267_ (
    .A(RESET),
    .ZN(_005_)
  );
  NOR2_X1 _268_ (
    .A1(_133_),
    .A2(STATO_3_),
    .ZN(_068_)
  );
  NAND2_X1 _269_ (
    .A1(STATO_2_),
    .A2(_064_),
    .ZN(_069_)
  );
  AND2_X1 _270_ (
    .A1(MAR_2_),
    .A2(MAR_0_),
    .ZN(_070_)
  );
  AND2_X1 _271_ (
    .A1(MAR_1_),
    .A2(_070_),
    .ZN(_071_)
  );
  NAND3_X1 _272_ (
    .A1(MAR_3_),
    .A2(MAR_4_),
    .A3(_071_),
    .ZN(_072_)
  );
  NOR2_X1 _273_ (
    .A1(_057_),
    .A2(_072_),
    .ZN(_073_)
  );
  NAND3_X1 _274_ (
    .A1(MAR_6_),
    .A2(STATO_3_),
    .A3(_073_),
    .ZN(_074_)
  );
  NOR2_X1 _275_ (
    .A1(MAR_4_),
    .A2(MAR_6_),
    .ZN(_075_)
  );
  NOR3_X1 _276_ (
    .A1(MAR_7_),
    .A2(MAR_3_),
    .A3(MAR_5_),
    .ZN(_076_)
  );
  NAND3_X1 _277_ (
    .A1(_071_),
    .A2(_075_),
    .A3(_076_),
    .ZN(_077_)
  );
  AND2_X1 _278_ (
    .A1(STATO_3_),
    .A2(_077_),
    .ZN(_078_)
  );
  NAND2_X1 _279_ (
    .A1(_069_),
    .A2(_074_),
    .ZN(_079_)
  );
  NAND3_X1 _280_ (
    .A1(MAR_7_),
    .A2(_069_),
    .A3(_074_),
    .ZN(_080_)
  );
  OAI21_X1 _281_ (
    .A(_080_),
    .B1(_074_),
    .B2(MAR_7_),
    .ZN(_056_)
  );
  MUX2_X1 _282_ (
    .A(IN_R_7_),
    .B(I_7_),
    .S(STATO_2_),
    .Z(_055_)
  );
  NOR2_X1 _283_ (
    .A1(_068_),
    .A2(_078_),
    .ZN(_081_)
  );
  OR2_X1 _284_ (
    .A1(_068_),
    .A2(_078_),
    .ZN(_082_)
  );
  OR2_X1 _285_ (
    .A1(MAR_1_),
    .A2(MAR_0_),
    .ZN(_083_)
  );
  XOR2_X1 _286_ (
    .A(MAR_1_),
    .B(MAR_0_),
    .Z(_084_)
  );
  AOI22_X1 _287_ (
    .A1(MAR_1_),
    .A2(_081_),
    .B1(_084_),
    .B2(STATO_3_),
    .ZN(_085_)
  );
  INV_X1 _288_ (
    .A(_085_),
    .ZN(_054_)
  );
  OR2_X1 _289_ (
    .A1(_064_),
    .A2(_077_),
    .ZN(_086_)
  );
  NOR2_X1 _290_ (
    .A1(START),
    .A2(_086_),
    .ZN(_087_)
  );
  MUX2_X1 _291_ (
    .A(O_3_),
    .B(OUT_R_3_),
    .S(_087_),
    .Z(_053_)
  );
  AOI21_X1 _292_ (
    .A(MAR_2_),
    .B1(MAR_0_),
    .B2(MAR_1_),
    .ZN(_088_)
  );
  OAI33_X1 _293_ (
    .A1(_136_),
    .A2(_068_),
    .A3(_078_),
    .B1(_088_),
    .B2(_071_),
    .B3(_064_),
    .ZN(_052_)
  );
  AOI21_X1 _294_ (
    .A(MAR_3_),
    .B1(_071_),
    .B2(_082_),
    .ZN(_089_)
  );
  NAND3_X1 _295_ (
    .A1(MAR_3_),
    .A2(STATO_3_),
    .A3(_071_),
    .ZN(_090_)
  );
  NAND2_X1 _296_ (
    .A1(_069_),
    .A2(_090_),
    .ZN(_091_)
  );
  NOR2_X1 _297_ (
    .A1(_089_),
    .A2(_091_),
    .ZN(_051_)
  );
  NAND3_X1 _298_ (
    .A1(MAR_4_),
    .A2(_069_),
    .A3(_090_),
    .ZN(_092_)
  );
  OAI21_X1 _299_ (
    .A(_092_),
    .B1(_090_),
    .B2(MAR_4_),
    .ZN(_050_)
  );
  SDFFR_X1 _300_ (
    .CK(CK),
    .D(_048_),
    .Q(O_0_),
    .RN(_023_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _301_ (
    .CK(CK),
    .D(_047_),
    .Q(O_1_),
    .RN(_022_),
    .SE(test_se),
    .SI(O_0_)
  );
  SDFFR_X1 _302_ (
    .CK(CK),
    .D(_046_),
    .Q(O_2_),
    .RN(_021_),
    .SE(test_se),
    .SI(O_1_)
  );
  SDFFR_X1 _303_ (
    .CK(CK),
    .D(_053_),
    .Q(O_3_),
    .RN(_029_),
    .SE(test_se),
    .SI(O_2_)
  );
  SDFFR_X1 _304_ (
    .CK(CK),
    .D(_045_),
    .Q(IN_R_0_),
    .RN(_020_),
    .SE(test_se),
    .SI(O_3_)
  );
  SDFFR_X1 _305_ (
    .CK(CK),
    .D(_044_),
    .Q(IN_R_1_),
    .RN(_019_),
    .SE(test_se),
    .SI(IN_R_0_)
  );
  SDFFR_X1 _306_ (
    .CK(CK),
    .D(_043_),
    .Q(IN_R_2_),
    .RN(_018_),
    .SE(test_se),
    .SI(IN_R_1_)
  );
  SDFFR_X1 _307_ (
    .CK(CK),
    .D(_041_),
    .Q(IN_R_3_),
    .RN(_016_),
    .SE(test_se),
    .SI(IN_R_2_)
  );
  SDFFR_X1 _308_ (
    .CK(CK),
    .D(_040_),
    .Q(IN_R_4_),
    .RN(_015_),
    .SE(test_se),
    .SI(IN_R_3_)
  );
  SDFFR_X1 _309_ (
    .CK(CK),
    .D(_039_),
    .Q(IN_R_5_),
    .RN(_014_),
    .SE(test_se),
    .SI(IN_R_4_)
  );
  SDFFR_X1 _310_ (
    .CK(CK),
    .D(_038_),
    .Q(IN_R_6_),
    .RN(_013_),
    .SE(test_se),
    .SI(IN_R_5_)
  );
  SDFFR_X1 _311_ (
    .CK(CK),
    .D(_055_),
    .Q(IN_R_7_),
    .RN(_031_),
    .SE(test_se),
    .SI(IN_R_6_)
  );
  SDFFR_X1 _312_ (
    .CK(CK),
    .D(_036_),
    .Q(OUT_R_0_),
    .RN(_010_),
    .SE(test_se),
    .SI(IN_R_7_)
  );
  SDFFR_X1 _313_ (
    .CK(CK),
    .D(_035_),
    .Q(OUT_R_1_),
    .RN(_009_),
    .SE(test_se),
    .SI(OUT_R_0_)
  );
  SDFFR_X1 _314_ (
    .CK(CK),
    .D(_034_),
    .Q(OUT_R_2_),
    .RN(_008_),
    .SE(test_se),
    .SI(OUT_R_1_)
  );
  SDFFR_X1 _315_ (
    .CK(CK),
    .D(_042_),
    .Q(OUT_R_3_),
    .RN(_017_),
    .SE(test_se),
    .SI(OUT_R_2_)
  );
  SDFFR_X1 _316_ (
    .CK(CK),
    .D(_033_),
    .Q(MAR_0_),
    .RN(_005_),
    .SE(test_se),
    .SI(OUT_R_3_)
  );
  SDFFR_X1 _317_ (
    .CK(CK),
    .D(_054_),
    .Q(MAR_1_),
    .RN(_030_),
    .SE(test_se),
    .SI(MAR_0_)
  );
  SDFFR_X1 _318_ (
    .CK(CK),
    .D(_052_),
    .Q(MAR_2_),
    .RN(_028_),
    .SE(test_se),
    .SI(MAR_1_)
  );
  SDFFR_X1 _319_ (
    .CK(CK),
    .D(_051_),
    .Q(MAR_3_),
    .RN(_026_),
    .SE(test_se),
    .SI(MAR_2_)
  );
  SDFFR_X1 _320_ (
    .CK(CK),
    .D(_050_),
    .Q(MAR_4_),
    .RN(_025_),
    .SE(test_se),
    .SI(MAR_3_)
  );
  SDFFR_X1 _321_ (
    .CK(CK),
    .D(_049_),
    .Q(MAR_5_),
    .RN(_024_),
    .SE(test_se),
    .SI(MAR_4_)
  );
  SDFFR_X1 _322_ (
    .CK(CK),
    .D(_037_),
    .Q(MAR_6_),
    .RN(_012_),
    .SE(test_se),
    .SI(MAR_5_)
  );
  SDFFR_X1 _323_ (
    .CK(CK),
    .D(_056_),
    .Q(MAR_7_),
    .RN(_032_),
    .SE(test_se),
    .SI(MAR_6_)
  );
  SDFFS_X1 _324_ (
    .CK(CK),
    .D(_001_),
    .Q(STATO_0_),
    .SN(_007_),
    .SE(test_se),
    .SI(MAR_7_)
  );
  SDFFR_X1 _325_ (
    .CK(CK),
    .D(_002_),
    .Q(STATO_1_),
    .RN(_006_),
    .SE(test_se),
    .SI(STATO_0_)
  );
  SDFFR_X1 _326_ (
    .CK(CK),
    .D(_000_),
    .Q(STATO_2_),
    .RN(_011_),
    .SE(test_se),
    .SI(STATO_1_)
  );
  SDFFR_X1 _327_ (
    .CK(CK),
    .D(_003_),
    .Q(STATO_3_),
    .RN(_027_),
    .SE(test_se),
    .SI(STATO_2_)
  );
  assign test_so = STATO_3_;
endmodule
