/* Generated by Yosys 0.38 (git sha1 543faed9c, gcc 11.4.0-1ubuntu1~22.04.3 -fPIC -Os) */

module b09(reset, CK, x, y, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  input CK;
  wire CK;
  wire d_in_0_;
  wire d_in_1_;
  wire d_in_2_;
  wire d_in_3_;
  wire d_in_4_;
  wire d_in_5_;
  wire d_in_6_;
  wire d_in_7_;
  wire d_in_8_;
  wire d_out_0_;
  wire d_out_1_;
  wire d_out_2_;
  wire d_out_3_;
  wire d_out_4_;
  wire d_out_5_;
  wire d_out_6_;
  wire d_out_7_;
  wire old_0_;
  wire old_1_;
  wire old_2_;
  wire old_3_;
  wire old_4_;
  wire old_5_;
  wire old_6_;
  wire old_7_;
  input reset;
  wire reset;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  wire stato_3_;
  input x;
  wire x;
  output y;
  wire y;
  NAND2_X1 _183_ (
    .A1(_141_),
    .A2(_142_),
    .ZN(_038_)
  );
  NAND2_X1 _184_ (
    .A1(old_2_),
    .A2(_132_),
    .ZN(_143_)
  );
  NAND3_X1 _185_ (
    .A1(d_in_3_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_144_)
  );
  NAND2_X1 _186_ (
    .A1(_143_),
    .A2(_144_),
    .ZN(_037_)
  );
  NAND2_X1 _187_ (
    .A1(old_1_),
    .A2(_132_),
    .ZN(_145_)
  );
  NAND3_X1 _188_ (
    .A1(d_in_2_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_146_)
  );
  NAND2_X1 _189_ (
    .A1(_145_),
    .A2(_146_),
    .ZN(_036_)
  );
  NAND2_X1 _190_ (
    .A1(old_0_),
    .A2(_132_),
    .ZN(_147_)
  );
  NAND3_X1 _191_ (
    .A1(d_in_1_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_148_)
  );
  NAND2_X1 _192_ (
    .A1(_147_),
    .A2(_148_),
    .ZN(_035_)
  );
  MUX2_X1 _193_ (
    .A(stato_1_),
    .B(stato_2_),
    .S(d_in_0_),
    .Z(_149_)
  );
  OR2_X1 _194_ (
    .A1(_129_),
    .A2(_149_),
    .ZN(_000_)
  );
  OR2_X1 _195_ (
    .A1(stato_0_),
    .A2(_153_),
    .ZN(_001_)
  );
  INV_X1 _196_ (
    .A(reset),
    .ZN(_006_)
  );
  INV_X1 _197_ (
    .A(reset),
    .ZN(_007_)
  );
  INV_X1 _198_ (
    .A(reset),
    .ZN(_008_)
  );
  INV_X1 _199_ (
    .A(reset),
    .ZN(_009_)
  );
  INV_X1 _200_ (
    .A(reset),
    .ZN(_010_)
  );
  INV_X1 _201_ (
    .A(reset),
    .ZN(_011_)
  );
  INV_X1 _202_ (
    .A(reset),
    .ZN(_012_)
  );
  INV_X1 _203_ (
    .A(reset),
    .ZN(_013_)
  );
  INV_X1 _204_ (
    .A(reset),
    .ZN(_014_)
  );
  INV_X1 _205_ (
    .A(reset),
    .ZN(_015_)
  );
  INV_X1 _206_ (
    .A(reset),
    .ZN(_016_)
  );
  INV_X1 _207_ (
    .A(reset),
    .ZN(_017_)
  );
  INV_X1 _208_ (
    .A(reset),
    .ZN(_018_)
  );
  INV_X1 _209_ (
    .A(reset),
    .ZN(_019_)
  );
  INV_X1 _210_ (
    .A(reset),
    .ZN(_020_)
  );
  INV_X1 _211_ (
    .A(reset),
    .ZN(_021_)
  );
  INV_X1 _212_ (
    .A(reset),
    .ZN(_022_)
  );
  INV_X1 _213_ (
    .A(reset),
    .ZN(_023_)
  );
  INV_X1 _214_ (
    .A(reset),
    .ZN(_024_)
  );
  INV_X1 _215_ (
    .A(reset),
    .ZN(_025_)
  );
  INV_X1 _216_ (
    .A(reset),
    .ZN(_026_)
  );
  INV_X1 _217_ (
    .A(reset),
    .ZN(_027_)
  );
  INV_X1 _218_ (
    .A(reset),
    .ZN(_028_)
  );
  INV_X1 _219_ (
    .A(reset),
    .ZN(_029_)
  );
  INV_X1 _220_ (
    .A(reset),
    .ZN(_030_)
  );
  INV_X1 _221_ (
    .A(reset),
    .ZN(_031_)
  );
  INV_X1 _222_ (
    .A(reset),
    .ZN(_032_)
  );
  INV_X1 _223_ (
    .A(reset),
    .ZN(_033_)
  );
  INV_X1 _224_ (
    .A(reset),
    .ZN(_034_)
  );
  INV_X1 _225_ (
    .A(d_in_0_),
    .ZN(_150_)
  );
  INV_X1 _226_ (
    .A(stato_2_),
    .ZN(_151_)
  );
  INV_X1 _227_ (
    .A(stato_3_),
    .ZN(_152_)
  );
  INV_X1 _228_ (
    .A(reset),
    .ZN(_005_)
  );
  NOR2_X1 _229_ (
    .A1(d_in_0_),
    .A2(_151_),
    .ZN(_153_)
  );
  NAND2_X1 _230_ (
    .A1(_151_),
    .A2(_152_),
    .ZN(_154_)
  );
  OR2_X1 _231_ (
    .A1(stato_1_),
    .A2(_154_),
    .ZN(_061_)
  );
  NOR2_X1 _232_ (
    .A1(stato_0_),
    .A2(_154_),
    .ZN(_062_)
  );
  NOR2_X1 _233_ (
    .A1(stato_0_),
    .A2(_061_),
    .ZN(_063_)
  );
  NOR2_X1 _234_ (
    .A1(_153_),
    .A2(_063_),
    .ZN(_064_)
  );
  NAND2_X1 _235_ (
    .A1(d_in_0_),
    .A2(stato_1_),
    .ZN(_065_)
  );
  XNOR2_X1 _236_ (
    .A(d_in_5_),
    .B(old_4_),
    .ZN(_066_)
  );
  XNOR2_X1 _237_ (
    .A(d_in_8_),
    .B(old_7_),
    .ZN(_067_)
  );
  XNOR2_X1 _238_ (
    .A(d_in_2_),
    .B(old_1_),
    .ZN(_068_)
  );
  XNOR2_X1 _239_ (
    .A(d_in_6_),
    .B(old_5_),
    .ZN(_069_)
  );
  XNOR2_X1 _240_ (
    .A(d_in_1_),
    .B(old_0_),
    .ZN(_070_)
  );
  XNOR2_X1 _241_ (
    .A(d_in_3_),
    .B(old_2_),
    .ZN(_071_)
  );
  XNOR2_X1 _242_ (
    .A(d_in_4_),
    .B(old_3_),
    .ZN(_072_)
  );
  XNOR2_X1 _243_ (
    .A(d_in_7_),
    .B(old_6_),
    .ZN(_073_)
  );
  NAND4_X1 _244_ (
    .A1(_066_),
    .A2(_067_),
    .A3(_070_),
    .A4(_071_),
    .ZN(_074_)
  );
  NAND4_X1 _245_ (
    .A1(_068_),
    .A2(_069_),
    .A3(_072_),
    .A4(_073_),
    .ZN(_075_)
  );
  NOR2_X1 _246_ (
    .A1(_074_),
    .A2(_075_),
    .ZN(_076_)
  );
  NAND2_X1 _247_ (
    .A1(stato_3_),
    .A2(_076_),
    .ZN(_077_)
  );
  NAND2_X1 _248_ (
    .A1(_150_),
    .A2(stato_3_),
    .ZN(_078_)
  );
  NAND3_X1 _249_ (
    .A1(_065_),
    .A2(_077_),
    .A3(_078_),
    .ZN(_002_)
  );
  NOR3_X1 _250_ (
    .A1(_153_),
    .A2(_063_),
    .A3(_002_),
    .ZN(_079_)
  );
  AND2_X1 _251_ (
    .A1(d_in_8_),
    .A2(_154_),
    .ZN(_080_)
  );
  MUX2_X1 _252_ (
    .A(d_out_7_),
    .B(_080_),
    .S(_079_),
    .Z(_060_)
  );
  NAND2_X1 _253_ (
    .A1(d_out_7_),
    .A2(stato_1_),
    .ZN(_081_)
  );
  NAND2_X1 _254_ (
    .A1(d_in_7_),
    .A2(_154_),
    .ZN(_082_)
  );
  NAND2_X1 _255_ (
    .A1(_081_),
    .A2(_082_),
    .ZN(_083_)
  );
  MUX2_X1 _256_ (
    .A(d_out_6_),
    .B(_083_),
    .S(_079_),
    .Z(_059_)
  );
  NAND2_X1 _257_ (
    .A1(d_out_6_),
    .A2(stato_1_),
    .ZN(_084_)
  );
  NAND2_X1 _258_ (
    .A1(d_in_6_),
    .A2(_154_),
    .ZN(_085_)
  );
  NAND2_X1 _259_ (
    .A1(_084_),
    .A2(_085_),
    .ZN(_086_)
  );
  MUX2_X1 _260_ (
    .A(d_out_5_),
    .B(_086_),
    .S(_079_),
    .Z(_058_)
  );
  NAND2_X1 _261_ (
    .A1(d_out_5_),
    .A2(stato_1_),
    .ZN(_087_)
  );
  NAND2_X1 _262_ (
    .A1(d_in_5_),
    .A2(_154_),
    .ZN(_088_)
  );
  NAND2_X1 _263_ (
    .A1(_087_),
    .A2(_088_),
    .ZN(_089_)
  );
  MUX2_X1 _264_ (
    .A(d_out_4_),
    .B(_089_),
    .S(_079_),
    .Z(_057_)
  );
  NAND2_X1 _265_ (
    .A1(d_out_4_),
    .A2(stato_1_),
    .ZN(_090_)
  );
  NAND2_X1 _266_ (
    .A1(d_in_4_),
    .A2(_154_),
    .ZN(_091_)
  );
  NAND2_X1 _267_ (
    .A1(_090_),
    .A2(_091_),
    .ZN(_092_)
  );
  MUX2_X1 _268_ (
    .A(d_out_3_),
    .B(_092_),
    .S(_079_),
    .Z(_056_)
  );
  NAND2_X1 _269_ (
    .A1(d_out_3_),
    .A2(stato_1_),
    .ZN(_093_)
  );
  NAND2_X1 _270_ (
    .A1(d_in_3_),
    .A2(_154_),
    .ZN(_094_)
  );
  NAND2_X1 _271_ (
    .A1(_093_),
    .A2(_094_),
    .ZN(_095_)
  );
  MUX2_X1 _272_ (
    .A(d_out_2_),
    .B(_095_),
    .S(_079_),
    .Z(_055_)
  );
  NAND2_X1 _273_ (
    .A1(d_out_2_),
    .A2(stato_1_),
    .ZN(_096_)
  );
  NAND2_X1 _274_ (
    .A1(d_in_2_),
    .A2(_154_),
    .ZN(_097_)
  );
  NAND2_X1 _275_ (
    .A1(_096_),
    .A2(_097_),
    .ZN(_098_)
  );
  MUX2_X1 _276_ (
    .A(d_out_1_),
    .B(_098_),
    .S(_079_),
    .Z(_054_)
  );
  NAND2_X1 _277_ (
    .A1(d_out_1_),
    .A2(stato_1_),
    .ZN(_099_)
  );
  NAND2_X1 _278_ (
    .A1(d_in_1_),
    .A2(_154_),
    .ZN(_100_)
  );
  NAND2_X1 _279_ (
    .A1(_099_),
    .A2(_100_),
    .ZN(_101_)
  );
  MUX2_X1 _280_ (
    .A(d_out_0_),
    .B(_101_),
    .S(_079_),
    .Z(_053_)
  );
  NAND2_X1 _281_ (
    .A1(d_in_8_),
    .A2(_063_),
    .ZN(_102_)
  );
  NOR2_X1 _282_ (
    .A1(_003_),
    .A2(_076_),
    .ZN(_103_)
  );
  AND2_X1 _283_ (
    .A1(stato_1_),
    .A2(x),
    .ZN(_104_)
  );
  NOR2_X1 _284_ (
    .A1(d_in_0_),
    .A2(_003_),
    .ZN(_105_)
  );
  OR4_X1 _285_ (
    .A1(stato_2_),
    .A2(_103_),
    .A3(_104_),
    .A4(_105_),
    .ZN(_106_)
  );
  OR2_X1 _286_ (
    .A1(d_in_0_),
    .A2(x),
    .ZN(_107_)
  );
  NAND3_X1 _287_ (
    .A1(_061_),
    .A2(_106_),
    .A3(_107_),
    .ZN(_108_)
  );
  NAND2_X1 _288_ (
    .A1(_102_),
    .A2(_108_),
    .ZN(_052_)
  );
  NAND2_X1 _289_ (
    .A1(d_in_7_),
    .A2(_063_),
    .ZN(_109_)
  );
  OR3_X1 _290_ (
    .A1(stato_1_),
    .A2(_153_),
    .A3(_105_),
    .ZN(_110_)
  );
  NAND3_X1 _291_ (
    .A1(d_in_8_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_111_)
  );
  NAND2_X1 _292_ (
    .A1(_109_),
    .A2(_111_),
    .ZN(_051_)
  );
  NAND2_X1 _293_ (
    .A1(d_in_6_),
    .A2(_063_),
    .ZN(_112_)
  );
  NAND3_X1 _294_ (
    .A1(d_in_7_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_113_)
  );
  NAND2_X1 _295_ (
    .A1(_112_),
    .A2(_113_),
    .ZN(_050_)
  );
  NAND2_X1 _296_ (
    .A1(d_in_5_),
    .A2(_063_),
    .ZN(_114_)
  );
  NAND3_X1 _297_ (
    .A1(d_in_6_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_115_)
  );
  NAND2_X1 _298_ (
    .A1(_114_),
    .A2(_115_),
    .ZN(_049_)
  );
  NAND2_X1 _299_ (
    .A1(d_in_4_),
    .A2(_063_),
    .ZN(_116_)
  );
  NAND3_X1 _300_ (
    .A1(d_in_5_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_117_)
  );
  NAND2_X1 _301_ (
    .A1(_116_),
    .A2(_117_),
    .ZN(_048_)
  );
  NAND2_X1 _302_ (
    .A1(d_in_3_),
    .A2(_063_),
    .ZN(_118_)
  );
  NAND3_X1 _303_ (
    .A1(d_in_4_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_119_)
  );
  NAND2_X1 _304_ (
    .A1(_118_),
    .A2(_119_),
    .ZN(_047_)
  );
  NAND2_X1 _305_ (
    .A1(d_in_2_),
    .A2(_063_),
    .ZN(_120_)
  );
  NAND3_X1 _306_ (
    .A1(d_in_3_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_121_)
  );
  NAND2_X1 _307_ (
    .A1(_120_),
    .A2(_121_),
    .ZN(_046_)
  );
  NAND2_X1 _308_ (
    .A1(d_in_1_),
    .A2(_063_),
    .ZN(_122_)
  );
  NAND3_X1 _309_ (
    .A1(d_in_2_),
    .A2(_061_),
    .A3(_110_),
    .ZN(_123_)
  );
  NAND2_X1 _310_ (
    .A1(_122_),
    .A2(_123_),
    .ZN(_045_)
  );
  NAND2_X1 _311_ (
    .A1(d_in_0_),
    .A2(_063_),
    .ZN(_124_)
  );
  AND2_X1 _312_ (
    .A1(_150_),
    .A2(_154_),
    .ZN(_125_)
  );
  OR2_X1 _313_ (
    .A1(stato_1_),
    .A2(_125_),
    .ZN(_126_)
  );
  NAND2_X1 _314_ (
    .A1(d_in_1_),
    .A2(_126_),
    .ZN(_127_)
  );
  NAND2_X1 _315_ (
    .A1(_124_),
    .A2(_127_),
    .ZN(_044_)
  );
  NOR2_X1 _316_ (
    .A1(y),
    .A2(_064_),
    .ZN(_128_)
  );
  NOR3_X1 _317_ (
    .A1(_004_),
    .A2(_152_),
    .A3(_076_),
    .ZN(_129_)
  );
  AND3_X1 _318_ (
    .A1(d_out_0_),
    .A2(_150_),
    .A3(stato_1_),
    .ZN(_130_)
  );
  NOR4_X1 _319_ (
    .A1(stato_2_),
    .A2(_063_),
    .A3(_129_),
    .A4(_130_),
    .ZN(_131_)
  );
  NOR2_X1 _320_ (
    .A1(_128_),
    .A2(_131_),
    .ZN(_043_)
  );
  OR2_X1 _321_ (
    .A1(_062_),
    .A2(_125_),
    .ZN(_132_)
  );
  NAND2_X1 _322_ (
    .A1(old_7_),
    .A2(_132_),
    .ZN(_133_)
  );
  NAND2_X1 _323_ (
    .A1(d_in_0_),
    .A2(_080_),
    .ZN(_134_)
  );
  NAND2_X1 _324_ (
    .A1(_133_),
    .A2(_134_),
    .ZN(_042_)
  );
  NAND2_X1 _325_ (
    .A1(old_6_),
    .A2(_132_),
    .ZN(_135_)
  );
  NAND3_X1 _326_ (
    .A1(d_in_7_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_136_)
  );
  NAND2_X1 _327_ (
    .A1(_135_),
    .A2(_136_),
    .ZN(_041_)
  );
  NAND2_X1 _328_ (
    .A1(old_5_),
    .A2(_132_),
    .ZN(_137_)
  );
  NAND3_X1 _329_ (
    .A1(d_in_6_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_138_)
  );
  NAND2_X1 _330_ (
    .A1(_137_),
    .A2(_138_),
    .ZN(_040_)
  );
  NAND2_X1 _331_ (
    .A1(old_4_),
    .A2(_132_),
    .ZN(_139_)
  );
  NAND3_X1 _332_ (
    .A1(d_in_5_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_140_)
  );
  NAND2_X1 _333_ (
    .A1(_139_),
    .A2(_140_),
    .ZN(_039_)
  );
  NAND2_X1 _334_ (
    .A1(old_3_),
    .A2(_132_),
    .ZN(_141_)
  );
  NAND3_X1 _335_ (
    .A1(d_in_4_),
    .A2(d_in_0_),
    .A3(_154_),
    .ZN(_142_)
  );
  SDFFR_X1 _336_ (
    .CK(CK),
    .D(_035_),
    .Q(old_0_),
    .RN(_005_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _337_ (
    .CK(CK),
    .D(_036_),
    .Q(old_1_),
    .RN(_006_),
    .SE(test_se),
    .SI(old_0_)
  );
  SDFFR_X1 _338_ (
    .CK(CK),
    .D(_037_),
    .Q(old_2_),
    .RN(_007_),
    .SE(test_se),
    .SI(old_1_)
  );
  SDFFR_X1 _339_ (
    .CK(CK),
    .D(_038_),
    .Q(old_3_),
    .RN(_008_),
    .SE(test_se),
    .SI(old_2_)
  );
  SDFFR_X1 _340_ (
    .CK(CK),
    .D(_039_),
    .Q(old_4_),
    .RN(_009_),
    .SE(test_se),
    .SI(old_3_)
  );
  SDFFR_X1 _341_ (
    .CK(CK),
    .D(_040_),
    .Q(old_5_),
    .RN(_010_),
    .SE(test_se),
    .SI(old_4_)
  );
  SDFFR_X1 _342_ (
    .CK(CK),
    .D(_041_),
    .Q(old_6_),
    .RN(_011_),
    .SE(test_se),
    .SI(old_5_)
  );
  SDFFR_X1 _343_ (
    .CK(CK),
    .D(_042_),
    .Q(old_7_),
    .RN(_012_),
    .SE(test_se),
    .SI(old_6_)
  );
  SDFFRS_X1 _344_ (
    .CK(CK),
    .D(_const0_),
    .Q(stato_0_),
    .RN(_const1_),
    .SN(_013_),
    .SE(test_se),
    .SI(old_7_)
  );
  SDFFR_X1 _345_ (
    .CK(CK),
    .D(_000_),
    .Q(stato_1_),
    .RN(_014_),
    .SE(test_se),
    .SI(stato_0_)
  );
  SDFFR_X1 _346_ (
    .CK(CK),
    .D(_001_),
    .Q(stato_2_),
    .RN(_015_),
    .SE(test_se),
    .SI(stato_1_)
  );
  SDFFR_X1 _347_ (
    .CK(CK),
    .D(_002_),
    .Q(stato_3_),
    .QN(_003_),
    .RN(_016_),
    .SE(test_se),
    .SI(stato_2_)
  );
  SDFFR_X1 _348_ (
    .CK(CK),
    .D(_043_),
    .Q(y),
    .RN(_017_),
    .SE(test_se),
    .SI(stato_3_)
  );
  SDFFR_X1 _349_ (
    .CK(CK),
    .D(_044_),
    .Q(d_in_0_),
    .QN(_004_),
    .RN(_018_),
    .SE(test_se),
    .SI(y)
  );
  SDFFR_X1 _350_ (
    .CK(CK),
    .D(_045_),
    .Q(d_in_1_),
    .RN(_019_),
    .SE(test_se),
    .SI(d_in_0_)
  );
  SDFFR_X1 _351_ (
    .CK(CK),
    .D(_046_),
    .Q(d_in_2_),
    .RN(_020_),
    .SE(test_se),
    .SI(d_in_1_)
  );
  SDFFR_X1 _352_ (
    .CK(CK),
    .D(_047_),
    .Q(d_in_3_),
    .RN(_021_),
    .SE(test_se),
    .SI(d_in_2_)
  );
  SDFFR_X1 _353_ (
    .CK(CK),
    .D(_048_),
    .Q(d_in_4_),
    .RN(_022_),
    .SE(test_se),
    .SI(d_in_3_)
  );
  SDFFR_X1 _354_ (
    .CK(CK),
    .D(_049_),
    .Q(d_in_5_),
    .RN(_023_),
    .SE(test_se),
    .SI(d_in_4_)
  );
  SDFFR_X1 _355_ (
    .CK(CK),
    .D(_050_),
    .Q(d_in_6_),
    .RN(_024_),
    .SE(test_se),
    .SI(d_in_5_)
  );
  SDFFR_X1 _356_ (
    .CK(CK),
    .D(_051_),
    .Q(d_in_7_),
    .RN(_025_),
    .SE(test_se),
    .SI(d_in_6_)
  );
  SDFFR_X1 _357_ (
    .CK(CK),
    .D(_052_),
    .Q(d_in_8_),
    .RN(_026_),
    .SE(test_se),
    .SI(d_in_7_)
  );
  SDFFR_X1 _358_ (
    .CK(CK),
    .D(_053_),
    .Q(d_out_0_),
    .RN(_027_),
    .SE(test_se),
    .SI(d_in_8_)
  );
  SDFFR_X1 _359_ (
    .CK(CK),
    .D(_054_),
    .Q(d_out_1_),
    .RN(_028_),
    .SE(test_se),
    .SI(d_out_0_)
  );
  SDFFR_X1 _360_ (
    .CK(CK),
    .D(_055_),
    .Q(d_out_2_),
    .RN(_029_),
    .SE(test_se),
    .SI(d_out_1_)
  );
  SDFFR_X1 _361_ (
    .CK(CK),
    .D(_056_),
    .Q(d_out_3_),
    .RN(_030_),
    .SE(test_se),
    .SI(d_out_2_)
  );
  SDFFR_X1 _362_ (
    .CK(CK),
    .D(_057_),
    .Q(d_out_4_),
    .RN(_031_),
    .SE(test_se),
    .SI(d_out_3_)
  );
  SDFFR_X1 _363_ (
    .CK(CK),
    .D(_058_),
    .Q(d_out_5_),
    .RN(_032_),
    .SE(test_se),
    .SI(d_out_4_)
  );
  SDFFR_X1 _364_ (
    .CK(CK),
    .D(_059_),
    .Q(d_out_6_),
    .RN(_033_),
    .SE(test_se),
    .SI(d_out_5_)
  );
  SDFFR_X1 _365_ (
    .CK(CK),
    .D(_060_),
    .Q(d_out_7_),
    .RN(_034_),
    .SE(test_se),
    .SI(d_out_6_)
  );

  wire _const0_;
  wire _const1_;
  LOGIC0_X1 _tie__const0_ (.Z(_const0_));
  LOGIC1_X1 _tie__const1_ (.Z(_const1_));
  assign test_so = d_out_7_;
endmodule