/* Generated by Yosys 0.65 (git sha1 9d0cdb855, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module b09(reset, CK, x, y, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  input reset;
  wire reset;
  input CK;
  wire CK;
  input x;
  wire x;
  output y;
  wire y;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire d_in_0_;
  wire d_in_1_;
  wire d_in_2_;
  wire d_in_3_;
  wire d_in_4_;
  wire d_in_5_;
  wire d_in_6_;
  wire d_in_7_;
  wire d_in_8_;
  wire d_out_0_;
  wire d_out_1_;
  wire d_out_2_;
  wire d_out_3_;
  wire d_out_4_;
  wire d_out_5_;
  wire d_out_6_;
  wire d_out_7_;
  wire old_0_;
  wire old_1_;
  wire old_2_;
  wire old_3_;
  wire old_4_;
  wire old_5_;
  wire old_6_;
  wire old_7_;
  wire stato_0_;
  wire stato_1_;
  wire stato_2_;
  wire stato_3_;
  INV_X1 _164_ (
    .A(old_7_),
    .ZN(_128_)
  );
  INV_X1 _165_ (
    .A(d_in_0_),
    .ZN(_129_)
  );
  INV_X1 _166_ (
    .A(d_in_1_),
    .ZN(_130_)
  );
  INV_X1 _167_ (
    .A(d_in_3_),
    .ZN(_131_)
  );
  INV_X1 _168_ (
    .A(old_0_),
    .ZN(_132_)
  );
  INV_X1 _169_ (
    .A(old_1_),
    .ZN(_133_)
  );
  INV_X1 _170_ (
    .A(old_2_),
    .ZN(_134_)
  );
  INV_X1 _171_ (
    .A(old_3_),
    .ZN(_060_)
  );
  INV_X1 _172_ (
    .A(old_4_),
    .ZN(_061_)
  );
  INV_X1 _173_ (
    .A(old_5_),
    .ZN(_062_)
  );
  INV_X1 _174_ (
    .A(old_6_),
    .ZN(_063_)
  );
  INV_X1 _175_ (
    .A(stato_2_),
    .ZN(_064_)
  );
  INV_X1 _176_ (
    .A(stato_3_),
    .ZN(_065_)
  );
  INV_X1 _177_ (
    .A(stato_0_),
    .ZN(_066_)
  );
  INV_X1 _178_ (
    .A(x),
    .ZN(_067_)
  );
  INV_X1 _179_ (
    .A(reset),
    .ZN(_004_)
  );
  OR2_X1 _180_ (
    .A1(stato_2_),
    .A2(stato_3_),
    .ZN(_068_)
  );
  MUX2_X1 _181_ (
    .A(stato_0_),
    .B(d_in_0_),
    .S(_068_),
    .Z(_069_)
  );
  AND2_X1 _182_ (
    .A1(d_in_8_),
    .A2(_068_),
    .ZN(_070_)
  );
  NAND2_X1 _183_ (
    .A1(d_in_8_),
    .A2(_068_),
    .ZN(_071_)
  );
  NAND2_X1 _184_ (
    .A1(d_in_0_),
    .A2(_066_),
    .ZN(_072_)
  );
  OAI22_X1 _185_ (
    .A1(_128_),
    .A2(_069_),
    .B1(_071_),
    .B2(_072_),
    .ZN(_059_)
  );
  XOR2_X1 _186_ (
    .A(d_in_7_),
    .B(old_6_),
    .Z(_073_)
  );
  AOI221_X1 _187_ (
    .A(_073_),
    .B1(_134_),
    .B2(d_in_3_),
    .C1(d_in_1_),
    .C2(_132_),
    .ZN(_074_)
  );
  XOR2_X1 _188_ (
    .A(old_7_),
    .B(d_in_8_),
    .Z(_075_)
  );
  XOR2_X1 _189_ (
    .A(d_in_5_),
    .B(old_4_),
    .Z(_076_)
  );
  XOR2_X1 _190_ (
    .A(d_in_2_),
    .B(old_1_),
    .Z(_077_)
  );
  XOR2_X1 _191_ (
    .A(d_in_4_),
    .B(old_3_),
    .Z(_078_)
  );
  XOR2_X1 _192_ (
    .A(d_in_6_),
    .B(old_5_),
    .Z(_079_)
  );
  NOR4_X1 _193_ (
    .A1(_075_),
    .A2(_076_),
    .A3(_077_),
    .A4(_078_),
    .ZN(_080_)
  );
  AOI221_X1 _194_ (
    .A(_079_),
    .B1(old_2_),
    .B2(_131_),
    .C1(_130_),
    .C2(old_0_),
    .ZN(_081_)
  );
  NAND3_X1 _195_ (
    .A1(_074_),
    .A2(_080_),
    .A3(_081_),
    .ZN(_082_)
  );
  NOR2_X1 _196_ (
    .A1(_129_),
    .A2(_065_),
    .ZN(_083_)
  );
  AOI21_X1 _197_ (
    .A(stato_2_),
    .B1(_082_),
    .B2(_083_),
    .ZN(_084_)
  );
  NOR2_X1 _198_ (
    .A1(d_in_0_),
    .A2(_065_),
    .ZN(_085_)
  );
  OR2_X1 _199_ (
    .A1(stato_1_),
    .A2(_085_),
    .ZN(_086_)
  );
  AOI211_X1 _200_ (
    .A(stato_2_),
    .B(_086_),
    .C1(_083_),
    .C2(_082_),
    .ZN(_087_)
  );
  NOR3_X1 _201_ (
    .A1(stato_1_),
    .A2(stato_0_),
    .A3(_068_),
    .ZN(_088_)
  );
  NAND2_X1 _202_ (
    .A1(d_in_8_),
    .A2(_088_),
    .ZN(_089_)
  );
  OAI221_X1 _203_ (
    .A(_089_),
    .B1(_087_),
    .B2(_067_),
    .C1(_129_),
    .C2(_084_),
    .ZN(_058_)
  );
  NOR2_X1 _204_ (
    .A1(d_in_0_),
    .A2(_064_),
    .ZN(_090_)
  );
  NOR2_X1 _205_ (
    .A1(_088_),
    .A2(_090_),
    .ZN(_091_)
  );
  AOI21_X1 _206_ (
    .A(_085_),
    .B1(stato_1_),
    .B2(d_in_0_),
    .ZN(_092_)
  );
  OAI21_X1 _207_ (
    .A(_092_),
    .B1(_082_),
    .B2(_065_),
    .ZN(_002_)
  );
  OAI211_X1 _208_ (
    .A(_091_),
    .B(_092_),
    .C1(_065_),
    .C2(_082_),
    .ZN(_093_)
  );
  NAND2_X1 _209_ (
    .A1(d_in_4_),
    .A2(_068_),
    .ZN(_094_)
  );
  AOI22_X1 _210_ (
    .A1(d_out_4_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_4_),
    .ZN(_095_)
  );
  INV_X1 _211_ (
    .A(_095_),
    .ZN(_096_)
  );
  MUX2_X1 _212_ (
    .A(_096_),
    .B(d_out_3_),
    .S(_093_),
    .Z(_057_)
  );
  NAND2_X1 _213_ (
    .A1(_129_),
    .A2(stato_1_),
    .ZN(_097_)
  );
  NOR2_X1 _214_ (
    .A1(_003_),
    .A2(_097_),
    .ZN(_098_)
  );
  NOR3_X1 _215_ (
    .A1(_088_),
    .A2(_090_),
    .A3(_098_),
    .ZN(_099_)
  );
  NOR2_X1 _216_ (
    .A1(y),
    .A2(_091_),
    .ZN(_100_)
  );
  AOI21_X1 _217_ (
    .A(_100_),
    .B1(_099_),
    .B2(_084_),
    .ZN(_056_)
  );
  NAND2_X1 _218_ (
    .A1(d_in_5_),
    .A2(_068_),
    .ZN(_101_)
  );
  AOI22_X1 _219_ (
    .A1(d_out_5_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_5_),
    .ZN(_102_)
  );
  INV_X1 _220_ (
    .A(_102_),
    .ZN(_103_)
  );
  MUX2_X1 _221_ (
    .A(_103_),
    .B(d_out_4_),
    .S(_093_),
    .Z(_055_)
  );
  NAND2_X1 _222_ (
    .A1(d_in_6_),
    .A2(_068_),
    .ZN(_104_)
  );
  AOI22_X1 _223_ (
    .A1(d_out_6_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_6_),
    .ZN(_105_)
  );
  INV_X1 _224_ (
    .A(_105_),
    .ZN(_106_)
  );
  MUX2_X1 _225_ (
    .A(_106_),
    .B(d_out_5_),
    .S(_093_),
    .Z(_054_)
  );
  NAND2_X1 _226_ (
    .A1(d_in_7_),
    .A2(_068_),
    .ZN(_107_)
  );
  AOI22_X1 _227_ (
    .A1(d_out_7_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_7_),
    .ZN(_108_)
  );
  INV_X1 _228_ (
    .A(_108_),
    .ZN(_109_)
  );
  MUX2_X1 _229_ (
    .A(_109_),
    .B(d_out_6_),
    .S(_093_),
    .Z(_053_)
  );
  OR3_X1 _230_ (
    .A1(stato_1_),
    .A2(_085_),
    .A3(_090_),
    .ZN(_110_)
  );
  AOI22_X1 _231_ (
    .A1(d_in_0_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_1_),
    .ZN(_111_)
  );
  INV_X1 _232_ (
    .A(_111_),
    .ZN(_052_)
  );
  AOI22_X1 _233_ (
    .A1(d_in_1_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_2_),
    .ZN(_112_)
  );
  INV_X1 _234_ (
    .A(_112_),
    .ZN(_051_)
  );
  AOI22_X1 _235_ (
    .A1(d_in_2_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_3_),
    .ZN(_113_)
  );
  INV_X1 _236_ (
    .A(_113_),
    .ZN(_050_)
  );
  AOI22_X1 _237_ (
    .A1(d_in_3_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_4_),
    .ZN(_114_)
  );
  INV_X1 _238_ (
    .A(_114_),
    .ZN(_049_)
  );
  AOI22_X1 _239_ (
    .A1(d_in_4_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_5_),
    .ZN(_115_)
  );
  INV_X1 _240_ (
    .A(_115_),
    .ZN(_048_)
  );
  AOI22_X1 _241_ (
    .A1(d_in_5_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_6_),
    .ZN(_116_)
  );
  INV_X1 _242_ (
    .A(_116_),
    .ZN(_047_)
  );
  AOI22_X1 _243_ (
    .A1(d_in_6_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_7_),
    .ZN(_117_)
  );
  INV_X1 _244_ (
    .A(_117_),
    .ZN(_046_)
  );
  AOI22_X1 _245_ (
    .A1(d_in_7_),
    .A2(_088_),
    .B1(_110_),
    .B2(d_in_8_),
    .ZN(_118_)
  );
  INV_X1 _246_ (
    .A(_118_),
    .ZN(_045_)
  );
  MUX2_X1 _247_ (
    .A(_070_),
    .B(d_out_7_),
    .S(_093_),
    .Z(_044_)
  );
  NAND2_X1 _248_ (
    .A1(d_in_1_),
    .A2(_068_),
    .ZN(_119_)
  );
  OAI22_X1 _249_ (
    .A1(_132_),
    .A2(_069_),
    .B1(_072_),
    .B2(_119_),
    .ZN(_043_)
  );
  NAND2_X1 _250_ (
    .A1(d_in_2_),
    .A2(_068_),
    .ZN(_120_)
  );
  OAI22_X1 _251_ (
    .A1(_133_),
    .A2(_069_),
    .B1(_072_),
    .B2(_120_),
    .ZN(_042_)
  );
  NAND2_X1 _252_ (
    .A1(d_in_3_),
    .A2(_068_),
    .ZN(_121_)
  );
  OAI22_X1 _253_ (
    .A1(_134_),
    .A2(_069_),
    .B1(_072_),
    .B2(_121_),
    .ZN(_041_)
  );
  OAI22_X1 _254_ (
    .A1(_060_),
    .A2(_069_),
    .B1(_072_),
    .B2(_094_),
    .ZN(_040_)
  );
  OAI22_X1 _255_ (
    .A1(_061_),
    .A2(_069_),
    .B1(_072_),
    .B2(_101_),
    .ZN(_039_)
  );
  OAI22_X1 _256_ (
    .A1(_062_),
    .A2(_069_),
    .B1(_072_),
    .B2(_104_),
    .ZN(_038_)
  );
  OAI22_X1 _257_ (
    .A1(_063_),
    .A2(_069_),
    .B1(_072_),
    .B2(_107_),
    .ZN(_037_)
  );
  AOI22_X1 _258_ (
    .A1(d_out_1_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_1_),
    .ZN(_122_)
  );
  INV_X1 _259_ (
    .A(_122_),
    .ZN(_123_)
  );
  MUX2_X1 _260_ (
    .A(_123_),
    .B(d_out_0_),
    .S(_093_),
    .Z(_036_)
  );
  AOI22_X1 _261_ (
    .A1(d_out_2_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_2_),
    .ZN(_124_)
  );
  INV_X1 _262_ (
    .A(_124_),
    .ZN(_125_)
  );
  MUX2_X1 _263_ (
    .A(_125_),
    .B(d_out_1_),
    .S(_093_),
    .Z(_035_)
  );
  AOI22_X1 _264_ (
    .A1(d_out_3_),
    .A2(stato_1_),
    .B1(_068_),
    .B2(d_in_3_),
    .ZN(_126_)
  );
  INV_X1 _265_ (
    .A(_126_),
    .ZN(_127_)
  );
  MUX2_X1 _266_ (
    .A(_127_),
    .B(d_out_2_),
    .S(_093_),
    .Z(_034_)
  );
  OAI21_X1 _267_ (
    .A(_066_),
    .B1(_064_),
    .B2(d_in_0_),
    .ZN(_001_)
  );
  OAI21_X1 _268_ (
    .A(_097_),
    .B1(_084_),
    .B2(_129_),
    .ZN(_000_)
  );
  INV_X1 _269_ (
    .A(reset),
    .ZN(_005_)
  );
  INV_X1 _270_ (
    .A(reset),
    .ZN(_006_)
  );
  INV_X1 _271_ (
    .A(reset),
    .ZN(_007_)
  );
  INV_X1 _272_ (
    .A(reset),
    .ZN(_008_)
  );
  INV_X1 _273_ (
    .A(reset),
    .ZN(_009_)
  );
  INV_X1 _274_ (
    .A(reset),
    .ZN(_010_)
  );
  INV_X1 _275_ (
    .A(reset),
    .ZN(_011_)
  );
  INV_X1 _276_ (
    .A(reset),
    .ZN(_012_)
  );
  INV_X1 _277_ (
    .A(reset),
    .ZN(_013_)
  );
  INV_X1 _278_ (
    .A(reset),
    .ZN(_014_)
  );
  INV_X1 _279_ (
    .A(reset),
    .ZN(_015_)
  );
  INV_X1 _280_ (
    .A(reset),
    .ZN(_016_)
  );
  INV_X1 _281_ (
    .A(reset),
    .ZN(_017_)
  );
  INV_X1 _282_ (
    .A(reset),
    .ZN(_018_)
  );
  INV_X1 _283_ (
    .A(reset),
    .ZN(_019_)
  );
  INV_X1 _284_ (
    .A(reset),
    .ZN(_020_)
  );
  INV_X1 _285_ (
    .A(reset),
    .ZN(_021_)
  );
  INV_X1 _286_ (
    .A(reset),
    .ZN(_022_)
  );
  INV_X1 _287_ (
    .A(reset),
    .ZN(_023_)
  );
  INV_X1 _288_ (
    .A(reset),
    .ZN(_024_)
  );
  INV_X1 _289_ (
    .A(reset),
    .ZN(_025_)
  );
  INV_X1 _290_ (
    .A(reset),
    .ZN(_026_)
  );
  INV_X1 _291_ (
    .A(reset),
    .ZN(_027_)
  );
  INV_X1 _292_ (
    .A(reset),
    .ZN(_028_)
  );
  INV_X1 _293_ (
    .A(reset),
    .ZN(_029_)
  );
  INV_X1 _294_ (
    .A(reset),
    .ZN(_030_)
  );
  INV_X1 _295_ (
    .A(reset),
    .ZN(_031_)
  );
  INV_X1 _296_ (
    .A(reset),
    .ZN(_032_)
  );
  INV_X1 _297_ (
    .A(reset),
    .ZN(_033_)
  );
  SDFFR_X1 _298_ (
    .CK(CK),
    .D(_036_),
    .Q(d_out_0_),
    .RN(_006_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _299_ (
    .CK(CK),
    .D(_035_),
    .Q(d_out_1_),
    .RN(_005_),
    .SE(test_se),
    .SI(d_out_0_)
  );
  SDFFR_X1 _300_ (
    .CK(CK),
    .D(_034_),
    .Q(d_out_2_),
    .RN(_004_),
    .SE(test_se),
    .SI(d_out_1_)
  );
  SDFFR_X1 _301_ (
    .CK(CK),
    .D(_057_),
    .Q(d_out_3_),
    .RN(_031_),
    .SE(test_se),
    .SI(d_out_2_)
  );
  SDFFR_X1 _302_ (
    .CK(CK),
    .D(_055_),
    .Q(d_out_4_),
    .RN(_029_),
    .SE(test_se),
    .SI(d_out_3_)
  );
  SDFFR_X1 _303_ (
    .CK(CK),
    .D(_054_),
    .Q(d_out_5_),
    .RN(_028_),
    .SE(test_se),
    .SI(d_out_4_)
  );
  SDFFR_X1 _304_ (
    .CK(CK),
    .D(_053_),
    .Q(d_out_6_),
    .RN(_027_),
    .SE(test_se),
    .SI(d_out_5_)
  );
  SDFFR_X1 _305_ (
    .CK(CK),
    .D(_044_),
    .Q(d_out_7_),
    .RN(_018_),
    .SE(test_se),
    .SI(d_out_6_)
  );
  SDFFR_X1 _306_ (
    .CK(CK),
    .D(_056_),
    .Q(y),
    .RN(_030_),
    .SE(test_se),
    .SI(d_out_7_)
  );
  SDFFR_X1 _307_ (
    .CK(CK),
    .D(_052_),
    .Q(d_in_0_),
    .RN(_026_),
    .SE(test_se),
    .SI(y)
  );
  SDFFR_X1 _308_ (
    .CK(CK),
    .D(_051_),
    .Q(d_in_1_),
    .RN(_025_),
    .SE(test_se),
    .SI(d_in_0_)
  );
  SDFFR_X1 _309_ (
    .CK(CK),
    .D(_050_),
    .Q(d_in_2_),
    .RN(_024_),
    .SE(test_se),
    .SI(d_in_1_)
  );
  SDFFR_X1 _310_ (
    .CK(CK),
    .D(_049_),
    .Q(d_in_3_),
    .RN(_023_),
    .SE(test_se),
    .SI(d_in_2_)
  );
  SDFFR_X1 _311_ (
    .CK(CK),
    .D(_048_),
    .Q(d_in_4_),
    .RN(_022_),
    .SE(test_se),
    .SI(d_in_3_)
  );
  SDFFR_X1 _312_ (
    .CK(CK),
    .D(_047_),
    .Q(d_in_5_),
    .RN(_021_),
    .SE(test_se),
    .SI(d_in_4_)
  );
  SDFFR_X1 _313_ (
    .CK(CK),
    .D(_046_),
    .Q(d_in_6_),
    .RN(_020_),
    .SE(test_se),
    .SI(d_in_5_)
  );
  SDFFR_X1 _314_ (
    .CK(CK),
    .D(_045_),
    .Q(d_in_7_),
    .RN(_019_),
    .SE(test_se),
    .SI(d_in_6_)
  );
  SDFFR_X1 _315_ (
    .CK(CK),
    .D(_058_),
    .Q(d_in_8_),
    .RN(_032_),
    .SE(test_se),
    .SI(d_in_7_)
  );
  SDFFR_X1 _316_ (
    .CK(CK),
    .D(_043_),
    .Q(old_0_),
    .RN(_015_),
    .SE(test_se),
    .SI(d_in_8_)
  );
  SDFFR_X1 _317_ (
    .CK(CK),
    .D(_042_),
    .Q(old_1_),
    .RN(_014_),
    .SE(test_se),
    .SI(old_0_)
  );
  SDFFR_X1 _318_ (
    .CK(CK),
    .D(_041_),
    .Q(old_2_),
    .RN(_013_),
    .SE(test_se),
    .SI(old_1_)
  );
  SDFFR_X1 _319_ (
    .CK(CK),
    .D(_040_),
    .Q(old_3_),
    .RN(_012_),
    .SE(test_se),
    .SI(old_2_)
  );
  SDFFR_X1 _320_ (
    .CK(CK),
    .D(_039_),
    .Q(old_4_),
    .RN(_011_),
    .SE(test_se),
    .SI(old_3_)
  );
  SDFFR_X1 _321_ (
    .CK(CK),
    .D(_038_),
    .Q(old_5_),
    .RN(_009_),
    .SE(test_se),
    .SI(old_4_)
  );
  SDFFR_X1 _322_ (
    .CK(CK),
    .D(_037_),
    .Q(old_6_),
    .RN(_008_),
    .SE(test_se),
    .SI(old_5_)
  );
  SDFFR_X1 _323_ (
    .CK(CK),
    .D(_059_),
    .Q(old_7_),
    .RN(_033_),
    .SE(test_se),
    .SI(old_6_)
  );
  SDFFS_X1 _324_ (
    .CK(CK),
    .D(_const0_),
    .Q(stato_0_),
    .SN(_016_),
    .SE(test_se),
    .SI(old_7_)
  );
  SDFFR_X1 _325_ (
    .CK(CK),
    .D(_000_),
    .Q(stato_1_),
    .RN(_007_),
    .SE(test_se),
    .SI(stato_0_)
  );
  SDFFR_X1 _326_ (
    .CK(CK),
    .D(_001_),
    .Q(stato_2_),
    .RN(_017_),
    .SE(test_se),
    .SI(stato_1_)
  );
  SDFFR_X1 _327_ (
    .CK(CK),
    .D(_002_),
    .Q(stato_3_),
    .RN(_010_),
    .SE(test_se),
    .SI(stato_2_)
  );

  wire _const0_;
  LOGIC0_X1 _tie_const0 (.Z(_const0_));
  assign test_so = stato_3_;
endmodule