/* Generated by Yosys 0.65 (git sha1 9d0cdb855, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module b13(reset, eoc, soc, load_dato, add_mpx2, canale_0_, canale_1_, canale_2_, canale_3_, mux_en, CK, data_in_0_, data_in_1_, data_in_2_, data_in_3_, data_in_4_, data_in_5_, data_in_6_, data_in_7_, dsr, errorr, data_out, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  input reset;
  wire reset;
  input eoc;
  wire eoc;
  output soc;
  wire soc;
  output load_dato;
  wire load_dato;
  output add_mpx2;
  wire add_mpx2;
    output canale_0_;
  output canale_1_;
  output canale_2_;
  output canale_3_;
    wire canale_0_;
  wire canale_1_;
  wire canale_2_;
  wire canale_3_;
  output mux_en;
  wire mux_en;
  input CK;
  wire CK;
    input data_in_0_;
  input data_in_1_;
  input data_in_2_;
  input data_in_3_;
  input data_in_4_;
  input data_in_5_;
  input data_in_6_;
  input data_in_7_;
    wire data_in_0_;
  wire data_in_1_;
  wire data_in_2_;
  wire data_in_3_;
  wire data_in_4_;
  wire data_in_5_;
  wire data_in_6_;
  wire data_in_7_;
  input dsr;
  wire dsr;
  output errorr;
  wire errorr;
  output data_out;
  wire data_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire S1_0_;
  wire S1_1_;
  wire S1_2_;
  wire S1_3_;
  wire S1_4_;
  wire S1_5_;
  wire S1_6_;
  wire S1_7_;
  wire S2_0_;
  wire S2_1_;
  wire S2_2_;
  wire S2_3_;
  wire confirm;
  wire conta_tmp_4_;
  wire conta_tmp_5_;
  wire conta_tmp_6_;
  wire conta_tmp_7_;
  wire itfc_state_0_;
  wire itfc_state_1_;
  wire itfc_state_2_;
  wire itfc_state_3_;
  wire load;
  wire mpx;
  wire next_bit_0_;
  wire next_bit_1_;
  wire next_bit_2_;
  wire next_bit_3_;
  wire next_bit_4_;
  wire next_bit_5_;
  wire next_bit_6_;
  wire next_bit_7_;
  wire next_bit_8_;
  wire next_bit_9_;
  wire out_reg_0_;
  wire out_reg_1_;
  wire out_reg_2_;
  wire out_reg_3_;
  wire out_reg_4_;
  wire out_reg_5_;
  wire out_reg_6_;
  wire out_reg_7_;
  wire rdy;
  wire send;
  wire send_data;
  wire send_en;
  wire shot;
  wire tre;
  wire tx_conta_0_;
  wire tx_conta_1_;
  wire tx_conta_2_;
  wire tx_conta_3_;
  wire tx_conta_4_;
  wire tx_conta_5_;
  wire tx_conta_6_;
  wire tx_end;
  INV_X1 _264_ (
    .A(load),
    .ZN(_135_)
  );
  INV_X1 _265_ (
    .A(_022_),
    .ZN(_136_)
  );
  INV_X1 _266_ (
    .A(itfc_state_3_),
    .ZN(_137_)
  );
  INV_X1 _267_ (
    .A(send_data),
    .ZN(_138_)
  );
  INV_X1 _268_ (
    .A(canale_2_),
    .ZN(_139_)
  );
  INV_X1 _269_ (
    .A(send_en),
    .ZN(_140_)
  );
  INV_X1 _270_ (
    .A(add_mpx2),
    .ZN(_141_)
  );
  INV_X1 _271_ (
    .A(tx_conta_6_),
    .ZN(_142_)
  );
  INV_X1 _272_ (
    .A(S1_5_),
    .ZN(_143_)
  );
  INV_X1 _273_ (
    .A(S2_1_),
    .ZN(_144_)
  );
  INV_X1 _274_ (
    .A(itfc_state_0_),
    .ZN(_145_)
  );
  INV_X1 _275_ (
    .A(S1_6_),
    .ZN(_146_)
  );
  INV_X1 _276_ (
    .A(S2_0_),
    .ZN(_147_)
  );
  INV_X1 _277_ (
    .A(S2_2_),
    .ZN(_148_)
  );
  INV_X1 _278_ (
    .A(S2_3_),
    .ZN(_149_)
  );
  INV_X1 _279_ (
    .A(tx_end),
    .ZN(_150_)
  );
  INV_X1 _280_ (
    .A(S1_1_),
    .ZN(_151_)
  );
  INV_X1 _281_ (
    .A(reset),
    .ZN(_025_)
  );
  AND2_X1 _282_ (
    .A1(shot),
    .A2(itfc_state_0_),
    .ZN(_011_)
  );
  MUX2_X1 _283_ (
    .A(itfc_state_2_),
    .B(shot),
    .S(itfc_state_0_),
    .Z(_152_)
  );
  MUX2_X1 _284_ (
    .A(load),
    .B(_001_),
    .S(_152_),
    .Z(_134_)
  );
  NAND2_X1 _285_ (
    .A1(confirm),
    .A2(S2_1_),
    .ZN(_153_)
  );
  MUX2_X1 _286_ (
    .A(_022_),
    .B(mpx),
    .S(_153_),
    .Z(_133_)
  );
  NOR2_X1 _287_ (
    .A1(itfc_state_1_),
    .A2(itfc_state_2_),
    .ZN(_154_)
  );
  MUX2_X1 _288_ (
    .A(_005_),
    .B(send),
    .S(_154_),
    .Z(_132_)
  );
  NOR2_X1 _289_ (
    .A1(_143_),
    .A2(eoc),
    .ZN(_014_)
  );
  NAND2_X1 _290_ (
    .A1(S1_5_),
    .A2(eoc),
    .ZN(_155_)
  );
  OAI21_X1 _291_ (
    .A(_155_),
    .B1(S1_0_),
    .B2(S1_5_),
    .ZN(_156_)
  );
  MUX2_X1 _292_ (
    .A(_003_),
    .B(mux_en),
    .S(_156_),
    .Z(_131_)
  );
  NOR2_X1 _293_ (
    .A1(load),
    .A2(send),
    .ZN(_157_)
  );
  NAND2_X1 _294_ (
    .A1(send),
    .A2(dsr),
    .ZN(_158_)
  );
  MUX2_X1 _295_ (
    .A(send),
    .B(_158_),
    .S(tre),
    .Z(_159_)
  );
  MUX2_X1 _296_ (
    .A(_159_),
    .B(errorr),
    .S(_157_),
    .Z(_130_)
  );
  MUX2_X1 _297_ (
    .A(S2_2_),
    .B(_023_),
    .S(S2_1_),
    .Z(_160_)
  );
  MUX2_X1 _298_ (
    .A(shot),
    .B(_004_),
    .S(_160_),
    .Z(_129_)
  );
  AOI21_X1 _299_ (
    .A(confirm),
    .B1(itfc_state_3_),
    .B2(tx_end),
    .ZN(_161_)
  );
  AOI21_X1 _300_ (
    .A(_161_),
    .B1(itfc_state_0_),
    .B2(_137_),
    .ZN(_128_)
  );
  AND4_X1 _301_ (
    .A1(canale_3_),
    .A2(canale_0_),
    .A3(canale_1_),
    .A4(canale_2_),
    .ZN(_162_)
  );
  NAND2_X1 _302_ (
    .A1(conta_tmp_4_),
    .A2(_162_),
    .ZN(_163_)
  );
  NAND3_X1 _303_ (
    .A1(conta_tmp_4_),
    .A2(conta_tmp_5_),
    .A3(_162_),
    .ZN(_164_)
  );
  NAND4_X1 _304_ (
    .A1(conta_tmp_4_),
    .A2(conta_tmp_5_),
    .A3(conta_tmp_6_),
    .A4(_162_),
    .ZN(_165_)
  );
  XOR2_X1 _305_ (
    .A(conta_tmp_7_),
    .B(_165_),
    .Z(_166_)
  );
  NOR2_X1 _306_ (
    .A1(conta_tmp_7_),
    .A2(S1_3_),
    .ZN(_167_)
  );
  AOI21_X1 _307_ (
    .A(_167_),
    .B1(_166_),
    .B2(S1_3_),
    .ZN(_127_)
  );
  NOR2_X1 _308_ (
    .A1(_135_),
    .A2(tre),
    .ZN(_168_)
  );
  MUX2_X1 _309_ (
    .A(out_reg_7_),
    .B(data_in_7_),
    .S(_168_),
    .Z(_126_)
  );
  AND3_X1 _310_ (
    .A1(mpx),
    .A2(confirm),
    .A3(S2_1_),
    .ZN(_012_)
  );
  AOI21_X1 _311_ (
    .A(_012_),
    .B1(S2_0_),
    .B2(_144_),
    .ZN(_169_)
  );
  AOI21_X1 _312_ (
    .A(_169_),
    .B1(S2_0_),
    .B2(_138_),
    .ZN(_170_)
  );
  MUX2_X1 _313_ (
    .A(rdy),
    .B(_004_),
    .S(_170_),
    .Z(_125_)
  );
  OAI21_X1 _314_ (
    .A(_155_),
    .B1(S1_5_),
    .B2(S1_3_),
    .ZN(_171_)
  );
  MUX2_X1 _315_ (
    .A(_002_),
    .B(load_dato),
    .S(_171_),
    .Z(_124_)
  );
  AND2_X1 _316_ (
    .A1(rdy),
    .A2(S1_6_),
    .ZN(_013_)
  );
  MUX2_X1 _317_ (
    .A(S1_7_),
    .B(rdy),
    .S(S1_6_),
    .Z(_172_)
  );
  MUX2_X1 _318_ (
    .A(send_data),
    .B(_006_),
    .S(_172_),
    .Z(_123_)
  );
  OR3_X1 _319_ (
    .A1(tx_conta_0_),
    .A2(tx_conta_1_),
    .A3(tx_conta_2_),
    .ZN(_173_)
  );
  AOI21_X1 _320_ (
    .A(tx_conta_4_),
    .B1(_173_),
    .B2(tx_conta_3_),
    .ZN(_174_)
  );
  NAND3_X1 _321_ (
    .A1(send_en),
    .A2(tx_conta_5_),
    .A3(tx_conta_6_),
    .ZN(_175_)
  );
  NOR2_X1 _322_ (
    .A1(_174_),
    .A2(_175_),
    .ZN(_176_)
  );
  MUX2_X1 _323_ (
    .A(next_bit_2_),
    .B(next_bit_8_),
    .S(_176_),
    .Z(_122_)
  );
  MUX2_X1 _324_ (
    .A(next_bit_3_),
    .B(next_bit_0_),
    .S(_176_),
    .Z(_121_)
  );
  MUX2_X1 _325_ (
    .A(next_bit_4_),
    .B(next_bit_7_),
    .S(_176_),
    .Z(_120_)
  );
  MUX2_X1 _326_ (
    .A(next_bit_5_),
    .B(next_bit_6_),
    .S(_176_),
    .Z(_119_)
  );
  MUX2_X1 _327_ (
    .A(out_reg_0_),
    .B(data_in_0_),
    .S(_168_),
    .Z(_118_)
  );
  MUX2_X1 _328_ (
    .A(out_reg_1_),
    .B(data_in_1_),
    .S(_168_),
    .Z(_117_)
  );
  MUX2_X1 _329_ (
    .A(out_reg_2_),
    .B(data_in_2_),
    .S(_168_),
    .Z(_116_)
  );
  MUX2_X1 _330_ (
    .A(out_reg_3_),
    .B(data_in_3_),
    .S(_168_),
    .Z(_115_)
  );
  MUX2_X1 _331_ (
    .A(out_reg_4_),
    .B(data_in_4_),
    .S(_168_),
    .Z(_114_)
  );
  MUX2_X1 _332_ (
    .A(out_reg_5_),
    .B(data_in_5_),
    .S(_168_),
    .Z(_113_)
  );
  MUX2_X1 _333_ (
    .A(out_reg_6_),
    .B(data_in_6_),
    .S(_168_),
    .Z(_112_)
  );
  MUX2_X1 _334_ (
    .A(next_bit_6_),
    .B(next_bit_1_),
    .S(_176_),
    .Z(_111_)
  );
  MUX2_X1 _335_ (
    .A(next_bit_7_),
    .B(next_bit_2_),
    .S(_176_),
    .Z(_110_)
  );
  NAND2_X1 _336_ (
    .A1(S1_3_),
    .A2(canale_0_),
    .ZN(_177_)
  );
  NAND3_X1 _337_ (
    .A1(S1_3_),
    .A2(canale_0_),
    .A3(canale_1_),
    .ZN(_178_)
  );
  NOR2_X1 _338_ (
    .A1(_139_),
    .A2(_178_),
    .ZN(_179_)
  );
  XOR2_X1 _339_ (
    .A(conta_tmp_6_),
    .B(_164_),
    .Z(_180_)
  );
  XOR2_X1 _340_ (
    .A(conta_tmp_5_),
    .B(_163_),
    .Z(_181_)
  );
  XNOR2_X1 _341_ (
    .A(conta_tmp_4_),
    .B(_162_),
    .ZN(_182_)
  );
  NAND4_X1 _342_ (
    .A1(_166_),
    .A2(_180_),
    .A3(_181_),
    .A4(_182_),
    .ZN(_183_)
  );
  AOI21_X1 _343_ (
    .A(canale_3_),
    .B1(_179_),
    .B2(_183_),
    .ZN(_184_)
  );
  AOI21_X1 _344_ (
    .A(_184_),
    .B1(_179_),
    .B2(canale_3_),
    .ZN(_109_)
  );
  NOR2_X1 _345_ (
    .A1(S1_3_),
    .A2(conta_tmp_4_),
    .ZN(_185_)
  );
  AOI21_X1 _346_ (
    .A(_185_),
    .B1(_182_),
    .B2(S1_3_),
    .ZN(_108_)
  );
  NOR2_X1 _347_ (
    .A1(S1_3_),
    .A2(conta_tmp_5_),
    .ZN(_186_)
  );
  AOI21_X1 _348_ (
    .A(_186_),
    .B1(_181_),
    .B2(S1_3_),
    .ZN(_107_)
  );
  NOR2_X1 _349_ (
    .A1(S1_3_),
    .A2(conta_tmp_6_),
    .ZN(_187_)
  );
  AOI21_X1 _350_ (
    .A(_187_),
    .B1(_180_),
    .B2(S1_3_),
    .ZN(_106_)
  );
  MUX2_X1 _351_ (
    .A(next_bit_8_),
    .B(next_bit_3_),
    .S(_176_),
    .Z(_105_)
  );
  MUX2_X1 _352_ (
    .A(canale_0_),
    .B(_010_),
    .S(S1_3_),
    .Z(_104_)
  );
  XNOR2_X1 _353_ (
    .A(canale_1_),
    .B(_177_),
    .ZN(_103_)
  );
  XNOR2_X1 _354_ (
    .A(canale_2_),
    .B(_178_),
    .ZN(_102_)
  );
  AND2_X1 _355_ (
    .A1(next_bit_5_),
    .A2(_176_),
    .ZN(_009_)
  );
  MUX2_X1 _356_ (
    .A(next_bit_0_),
    .B(next_bit_5_),
    .S(_176_),
    .Z(_101_)
  );
  MUX2_X1 _357_ (
    .A(next_bit_1_),
    .B(next_bit_9_),
    .S(_176_),
    .Z(_100_)
  );
  XNOR2_X1 _358_ (
    .A(tx_conta_0_),
    .B(send_en),
    .ZN(_188_)
  );
  NOR2_X1 _359_ (
    .A1(_176_),
    .A2(_188_),
    .ZN(_099_)
  );
  AOI21_X1 _360_ (
    .A(tx_conta_1_),
    .B1(send_en),
    .B2(tx_conta_0_),
    .ZN(_189_)
  );
  AND3_X1 _361_ (
    .A1(tx_conta_0_),
    .A2(send_en),
    .A3(tx_conta_1_),
    .ZN(_190_)
  );
  NOR3_X1 _362_ (
    .A1(_176_),
    .A2(_189_),
    .A3(_190_),
    .ZN(_098_)
  );
  NOR2_X1 _363_ (
    .A1(S1_3_),
    .A2(S1_2_),
    .ZN(_191_)
  );
  MUX2_X1 _364_ (
    .A(_002_),
    .B(soc),
    .S(_191_),
    .Z(_097_)
  );
  NOR2_X1 _365_ (
    .A1(tx_conta_2_),
    .A2(_190_),
    .ZN(_192_)
  );
  AND2_X1 _366_ (
    .A1(tx_conta_2_),
    .A2(_190_),
    .ZN(_193_)
  );
  NOR3_X1 _367_ (
    .A1(_176_),
    .A2(_192_),
    .A3(_193_),
    .ZN(_096_)
  );
  NOR2_X1 _368_ (
    .A1(tx_conta_3_),
    .A2(_193_),
    .ZN(_194_)
  );
  AND2_X1 _369_ (
    .A1(tx_conta_3_),
    .A2(_193_),
    .ZN(_195_)
  );
  NOR3_X1 _370_ (
    .A1(_176_),
    .A2(_194_),
    .A3(_195_),
    .ZN(_095_)
  );
  OAI22_X1 _371_ (
    .A1(_174_),
    .A2(_175_),
    .B1(_195_),
    .B2(tx_conta_4_),
    .ZN(_196_)
  );
  AOI21_X1 _372_ (
    .A(_196_),
    .B1(_195_),
    .B2(tx_conta_4_),
    .ZN(_094_)
  );
  OAI21_X1 _373_ (
    .A(_141_),
    .B1(_153_),
    .B2(_136_),
    .ZN(_093_)
  );
  NAND3_X1 _374_ (
    .A1(tx_conta_4_),
    .A2(tx_conta_5_),
    .A3(_195_),
    .ZN(_197_)
  );
  AOI21_X1 _375_ (
    .A(tx_conta_5_),
    .B1(_195_),
    .B2(tx_conta_4_),
    .ZN(_198_)
  );
  NOR2_X1 _376_ (
    .A1(_176_),
    .A2(_198_),
    .ZN(_199_)
  );
  AND2_X1 _377_ (
    .A1(_197_),
    .A2(_199_),
    .ZN(_092_)
  );
  AOI21_X1 _378_ (
    .A(_176_),
    .B1(_197_),
    .B2(_142_),
    .ZN(_091_)
  );
  MUX2_X1 _379_ (
    .A(next_bit_9_),
    .B(next_bit_4_),
    .S(_176_),
    .Z(_090_)
  );
  OAI22_X1 _380_ (
    .A1(_138_),
    .A2(_147_),
    .B1(_153_),
    .B2(_136_),
    .ZN(_019_)
  );
  AOI21_X1 _381_ (
    .A(S1_2_),
    .B1(eoc),
    .B2(S1_5_),
    .ZN(_200_)
  );
  INV_X1 _382_ (
    .A(_200_),
    .ZN(_020_)
  );
  OAI21_X1 _383_ (
    .A(_148_),
    .B1(_144_),
    .B2(confirm),
    .ZN(_018_)
  );
  OAI21_X1 _384_ (
    .A(_149_),
    .B1(_147_),
    .B2(send_data),
    .ZN(_017_)
  );
  OAI22_X1 _385_ (
    .A1(shot),
    .A2(_145_),
    .B1(_150_),
    .B2(_137_),
    .ZN(_015_)
  );
  OAI22_X1 _386_ (
    .A1(_140_),
    .A2(tx_end),
    .B1(_024_),
    .B2(_158_),
    .ZN(_007_)
  );
  NAND3_X1 _387_ (
    .A1(_135_),
    .A2(_150_),
    .A3(_024_),
    .ZN(_008_)
  );
  OAI21_X1 _388_ (
    .A(_005_),
    .B1(_137_),
    .B2(tx_end),
    .ZN(_016_)
  );
  OAI21_X1 _389_ (
    .A(_151_),
    .B1(_146_),
    .B2(rdy),
    .ZN(_021_)
  );
  NOR3_X1 _390_ (
    .A1(next_bit_6_),
    .A2(next_bit_1_),
    .A3(next_bit_9_),
    .ZN(_201_)
  );
  OR4_X1 _391_ (
    .A1(next_bit_0_),
    .A2(next_bit_3_),
    .A3(next_bit_7_),
    .A4(next_bit_4_),
    .ZN(_202_)
  );
  NOR3_X1 _392_ (
    .A1(next_bit_8_),
    .A2(next_bit_2_),
    .A3(_202_),
    .ZN(_203_)
  );
  AOI22_X1 _393_ (
    .A1(next_bit_6_),
    .A2(out_reg_0_),
    .B1(out_reg_1_),
    .B2(next_bit_1_),
    .ZN(_204_)
  );
  INV_X1 _394_ (
    .A(_204_),
    .ZN(_205_)
  );
  AOI221_X1 _395_ (
    .A(_205_),
    .B1(out_reg_3_),
    .B2(next_bit_4_),
    .C1(out_reg_7_),
    .C2(next_bit_3_),
    .ZN(_206_)
  );
  AOI22_X1 _396_ (
    .A1(next_bit_8_),
    .A2(out_reg_6_),
    .B1(_201_),
    .B2(_203_),
    .ZN(_207_)
  );
  AOI222_X1 _397_ (
    .A1(next_bit_7_),
    .A2(out_reg_4_),
    .B1(next_bit_9_),
    .B2(out_reg_2_),
    .C1(out_reg_5_),
    .C2(next_bit_2_),
    .ZN(_208_)
  );
  NAND4_X1 _398_ (
    .A1(_176_),
    .A2(_206_),
    .A3(_207_),
    .A4(_208_),
    .ZN(_000_)
  );
  INV_X1 _399_ (
    .A(reset),
    .ZN(_026_)
  );
  INV_X1 _400_ (
    .A(reset),
    .ZN(_027_)
  );
  INV_X1 _401_ (
    .A(reset),
    .ZN(_028_)
  );
  INV_X1 _402_ (
    .A(reset),
    .ZN(_029_)
  );
  INV_X1 _403_ (
    .A(reset),
    .ZN(_030_)
  );
  INV_X1 _404_ (
    .A(reset),
    .ZN(_031_)
  );
  INV_X1 _405_ (
    .A(reset),
    .ZN(_032_)
  );
  INV_X1 _406_ (
    .A(reset),
    .ZN(_033_)
  );
  INV_X1 _407_ (
    .A(reset),
    .ZN(_034_)
  );
  INV_X1 _408_ (
    .A(reset),
    .ZN(_035_)
  );
  INV_X1 _409_ (
    .A(reset),
    .ZN(_036_)
  );
  INV_X1 _410_ (
    .A(reset),
    .ZN(_037_)
  );
  INV_X1 _411_ (
    .A(reset),
    .ZN(_038_)
  );
  INV_X1 _412_ (
    .A(reset),
    .ZN(_039_)
  );
  INV_X1 _413_ (
    .A(reset),
    .ZN(_040_)
  );
  INV_X1 _414_ (
    .A(reset),
    .ZN(_041_)
  );
  INV_X1 _415_ (
    .A(reset),
    .ZN(_042_)
  );
  INV_X1 _416_ (
    .A(reset),
    .ZN(_043_)
  );
  INV_X1 _417_ (
    .A(reset),
    .ZN(_044_)
  );
  INV_X1 _418_ (
    .A(reset),
    .ZN(_045_)
  );
  INV_X1 _419_ (
    .A(reset),
    .ZN(_046_)
  );
  INV_X1 _420_ (
    .A(reset),
    .ZN(_047_)
  );
  INV_X1 _421_ (
    .A(reset),
    .ZN(_048_)
  );
  INV_X1 _422_ (
    .A(reset),
    .ZN(_049_)
  );
  INV_X1 _423_ (
    .A(reset),
    .ZN(_050_)
  );
  INV_X1 _424_ (
    .A(reset),
    .ZN(_051_)
  );
  INV_X1 _425_ (
    .A(reset),
    .ZN(_052_)
  );
  INV_X1 _426_ (
    .A(reset),
    .ZN(_053_)
  );
  INV_X1 _427_ (
    .A(reset),
    .ZN(_054_)
  );
  INV_X1 _428_ (
    .A(reset),
    .ZN(_055_)
  );
  INV_X1 _429_ (
    .A(reset),
    .ZN(_056_)
  );
  INV_X1 _430_ (
    .A(reset),
    .ZN(_057_)
  );
  INV_X1 _431_ (
    .A(reset),
    .ZN(_058_)
  );
  INV_X1 _432_ (
    .A(reset),
    .ZN(_059_)
  );
  INV_X1 _433_ (
    .A(reset),
    .ZN(_060_)
  );
  INV_X1 _434_ (
    .A(reset),
    .ZN(_061_)
  );
  INV_X1 _435_ (
    .A(reset),
    .ZN(_062_)
  );
  INV_X1 _436_ (
    .A(reset),
    .ZN(_063_)
  );
  INV_X1 _437_ (
    .A(reset),
    .ZN(_064_)
  );
  INV_X1 _438_ (
    .A(reset),
    .ZN(_065_)
  );
  INV_X1 _439_ (
    .A(reset),
    .ZN(_066_)
  );
  INV_X1 _440_ (
    .A(reset),
    .ZN(_067_)
  );
  INV_X1 _441_ (
    .A(reset),
    .ZN(_068_)
  );
  INV_X1 _442_ (
    .A(reset),
    .ZN(_069_)
  );
  INV_X1 _443_ (
    .A(reset),
    .ZN(_070_)
  );
  INV_X1 _444_ (
    .A(reset),
    .ZN(_071_)
  );
  INV_X1 _445_ (
    .A(reset),
    .ZN(_072_)
  );
  INV_X1 _446_ (
    .A(reset),
    .ZN(_073_)
  );
  INV_X1 _447_ (
    .A(reset),
    .ZN(_074_)
  );
  INV_X1 _448_ (
    .A(reset),
    .ZN(_075_)
  );
  INV_X1 _449_ (
    .A(reset),
    .ZN(_076_)
  );
  INV_X1 _450_ (
    .A(reset),
    .ZN(_077_)
  );
  INV_X1 _451_ (
    .A(reset),
    .ZN(_078_)
  );
  INV_X1 _452_ (
    .A(reset),
    .ZN(_079_)
  );
  INV_X1 _453_ (
    .A(reset),
    .ZN(_080_)
  );
  INV_X1 _454_ (
    .A(reset),
    .ZN(_081_)
  );
  INV_X1 _455_ (
    .A(reset),
    .ZN(_082_)
  );
  INV_X1 _456_ (
    .A(reset),
    .ZN(_083_)
  );
  INV_X1 _457_ (
    .A(reset),
    .ZN(_084_)
  );
  INV_X1 _458_ (
    .A(reset),
    .ZN(_085_)
  );
  INV_X1 _459_ (
    .A(reset),
    .ZN(_086_)
  );
  INV_X1 _460_ (
    .A(reset),
    .ZN(_087_)
  );
  INV_X1 _461_ (
    .A(reset),
    .ZN(_088_)
  );
  INV_X1 _462_ (
    .A(reset),
    .ZN(_089_)
  );
  SDFFS_X1 _463_ (
    .CK(CK),
    .D(_017_),
    .Q(S2_0_),
    .SN(_056_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _464_ (
    .CK(CK),
    .D(_018_),
    .Q(S2_1_),
    .RN(_051_),
    .SE(test_se),
    .SI(S2_0_)
  );
  SDFFR_X1 _465_ (
    .CK(CK),
    .D(_019_),
    .Q(S2_2_),
    .RN(_050_),
    .SE(test_se),
    .SI(S2_1_)
  );
  SDFFR_X1 _466_ (
    .CK(CK),
    .D(_012_),
    .Q(S2_3_),
    .RN(_068_),
    .SE(test_se),
    .SI(S2_2_)
  );
  SDFFS_X1 _467_ (
    .CK(CK),
    .D(_015_),
    .Q(itfc_state_0_),
    .SN(_048_),
    .SE(test_se),
    .SI(S2_3_)
  );
  SDFFR_X1 _468_ (
    .CK(CK),
    .D(itfc_state_2_),
    .Q(itfc_state_1_),
    .RN(_044_),
    .SE(test_se),
    .SI(itfc_state_0_)
  );
  SDFFR_X1 _469_ (
    .CK(CK),
    .D(_011_),
    .Q(itfc_state_2_),
    .RN(_043_),
    .SE(test_se),
    .SI(itfc_state_1_)
  );
  SDFFR_X1 _470_ (
    .CK(CK),
    .D(_016_),
    .Q(itfc_state_3_),
    .RN(_026_),
    .SE(test_se),
    .SI(itfc_state_2_)
  );
  SDFFR_X1 _471_ (
    .CK(CK),
    .D(_000_),
    .Q(data_out),
    .RN(_074_),
    .SE(test_se),
    .SI(itfc_state_3_)
  );
  SDFFR_X1 _472_ (
    .CK(CK),
    .D(_009_),
    .Q(tx_end),
    .RN(_033_),
    .SE(test_se),
    .SI(data_out)
  );
  SDFFR_X1 _473_ (
    .CK(CK),
    .D(_007_),
    .Q(send_en),
    .RN(_077_),
    .SE(test_se),
    .SI(tx_end)
  );
  SDFFR_X1 _474_ (
    .CK(CK),
    .D(_008_),
    .Q(tre),
    .RN(_079_),
    .SE(test_se),
    .SI(send_en)
  );
  SDFFR_X1 _475_ (
    .CK(CK),
    .D(_122_),
    .Q(next_bit_2_),
    .RN(_070_),
    .SE(test_se),
    .SI(tre)
  );
  SDFFR_X1 _476_ (
    .CK(CK),
    .D(_121_),
    .Q(next_bit_3_),
    .RN(_069_),
    .SE(test_se),
    .SI(next_bit_2_)
  );
  SDFFR_X1 _477_ (
    .CK(CK),
    .D(_120_),
    .Q(next_bit_4_),
    .RN(_067_),
    .SE(test_se),
    .SI(next_bit_3_)
  );
  SDFFR_X1 _478_ (
    .CK(CK),
    .D(_119_),
    .Q(next_bit_5_),
    .RN(_066_),
    .SE(test_se),
    .SI(next_bit_4_)
  );
  SDFFR_X1 _479_ (
    .CK(CK),
    .D(_111_),
    .Q(next_bit_6_),
    .RN(_058_),
    .SE(test_se),
    .SI(next_bit_5_)
  );
  SDFFR_X1 _480_ (
    .CK(CK),
    .D(_110_),
    .Q(next_bit_7_),
    .RN(_057_),
    .SE(test_se),
    .SI(next_bit_6_)
  );
  SDFFR_X1 _481_ (
    .CK(CK),
    .D(_105_),
    .Q(next_bit_8_),
    .RN(_049_),
    .SE(test_se),
    .SI(next_bit_7_)
  );
  SDFFS_X1 _482_ (
    .CK(CK),
    .D(_101_),
    .Q(next_bit_0_),
    .SN(_042_),
    .SE(test_se),
    .SI(next_bit_8_)
  );
  SDFFR_X1 _483_ (
    .CK(CK),
    .D(_100_),
    .Q(next_bit_1_),
    .RN(_041_),
    .SE(test_se),
    .SI(next_bit_0_)
  );
  SDFFR_X1 _484_ (
    .CK(CK),
    .D(_090_),
    .Q(next_bit_9_),
    .RN(_025_),
    .SE(test_se),
    .SI(next_bit_1_)
  );
  SDFFR_X1 _485_ (
    .CK(CK),
    .D(_093_),
    .Q(add_mpx2),
    .RN(_029_),
    .SE(test_se),
    .SI(next_bit_9_)
  );
  SDFFR_X1 _486_ (
    .CK(CK),
    .D(_097_),
    .Q(soc),
    .RN(_034_),
    .SE(test_se),
    .SI(add_mpx2)
  );
  SDFFR_X1 _487_ (
    .CK(CK),
    .D(_123_),
    .Q(send_data),
    .RN(_076_),
    .SE(test_se),
    .SI(soc)
  );
  SDFFR_X1 _488_ (
    .CK(CK),
    .D(_124_),
    .Q(load_dato),
    .RN(_078_),
    .SE(test_se),
    .SI(send_data)
  );
  SDFFR_X1 _489_ (
    .CK(CK),
    .D(_099_),
    .Q(tx_conta_0_),
    .RN(_036_),
    .SE(test_se),
    .SI(load_dato)
  );
  SDFFR_X1 _490_ (
    .CK(CK),
    .D(_098_),
    .Q(tx_conta_1_),
    .RN(_035_),
    .SE(test_se),
    .SI(tx_conta_0_)
  );
  SDFFR_X1 _491_ (
    .CK(CK),
    .D(_096_),
    .Q(tx_conta_2_),
    .RN(_032_),
    .SE(test_se),
    .SI(tx_conta_1_)
  );
  SDFFR_X1 _492_ (
    .CK(CK),
    .D(_095_),
    .Q(tx_conta_3_),
    .RN(_031_),
    .SE(test_se),
    .SI(tx_conta_2_)
  );
  SDFFR_X1 _493_ (
    .CK(CK),
    .D(_094_),
    .Q(tx_conta_4_),
    .RN(_030_),
    .SE(test_se),
    .SI(tx_conta_3_)
  );
  SDFFR_X1 _494_ (
    .CK(CK),
    .D(_092_),
    .Q(tx_conta_5_),
    .RN(_028_),
    .SE(test_se),
    .SI(tx_conta_4_)
  );
  SDFFR_X1 _495_ (
    .CK(CK),
    .D(_091_),
    .Q(tx_conta_6_),
    .RN(_027_),
    .SE(test_se),
    .SI(tx_conta_5_)
  );
  SDFFR_X1 _496_ (
    .CK(CK),
    .D(_125_),
    .Q(rdy),
    .RN(_080_),
    .SE(test_se),
    .SI(tx_conta_6_)
  );
  SDFFR_X1 _497_ (
    .CK(CK),
    .D(_118_),
    .Q(out_reg_0_),
    .RN(_065_),
    .SE(test_se),
    .SI(rdy)
  );
  SDFFR_X1 _498_ (
    .CK(CK),
    .D(_117_),
    .Q(out_reg_1_),
    .RN(_064_),
    .SE(test_se),
    .SI(out_reg_0_)
  );
  SDFFR_X1 _499_ (
    .CK(CK),
    .D(_116_),
    .Q(out_reg_2_),
    .RN(_063_),
    .SE(test_se),
    .SI(out_reg_1_)
  );
  SDFFR_X1 _500_ (
    .CK(CK),
    .D(_115_),
    .Q(out_reg_3_),
    .RN(_062_),
    .SE(test_se),
    .SI(out_reg_2_)
  );
  SDFFR_X1 _501_ (
    .CK(CK),
    .D(_114_),
    .Q(out_reg_4_),
    .RN(_061_),
    .SE(test_se),
    .SI(out_reg_3_)
  );
  SDFFR_X1 _502_ (
    .CK(CK),
    .D(_113_),
    .Q(out_reg_5_),
    .RN(_060_),
    .SE(test_se),
    .SI(out_reg_4_)
  );
  SDFFR_X1 _503_ (
    .CK(CK),
    .D(_112_),
    .Q(out_reg_6_),
    .RN(_059_),
    .SE(test_se),
    .SI(out_reg_5_)
  );
  SDFFR_X1 _504_ (
    .CK(CK),
    .D(_126_),
    .Q(out_reg_7_),
    .RN(_081_),
    .SE(test_se),
    .SI(out_reg_6_)
  );
  SDFFR_X1 _505_ (
    .CK(CK),
    .D(_109_),
    .Q(canale_3_),
    .RN(_055_),
    .SE(test_se),
    .SI(out_reg_7_)
  );
  SDFFR_X1 _506_ (
    .CK(CK),
    .D(_108_),
    .Q(conta_tmp_4_),
    .RN(_054_),
    .SE(test_se),
    .SI(canale_3_)
  );
  SDFFR_X1 _507_ (
    .CK(CK),
    .D(_107_),
    .Q(conta_tmp_5_),
    .RN(_053_),
    .SE(test_se),
    .SI(conta_tmp_4_)
  );
  SDFFR_X1 _508_ (
    .CK(CK),
    .D(_106_),
    .Q(conta_tmp_6_),
    .RN(_052_),
    .SE(test_se),
    .SI(conta_tmp_5_)
  );
  SDFFR_X1 _509_ (
    .CK(CK),
    .D(_127_),
    .Q(conta_tmp_7_),
    .RN(_082_),
    .SE(test_se),
    .SI(conta_tmp_6_)
  );
  SDFFR_X1 _510_ (
    .CK(CK),
    .D(_128_),
    .Q(confirm),
    .RN(_083_),
    .SE(test_se),
    .SI(conta_tmp_7_)
  );
  SDFFR_X1 _511_ (
    .CK(CK),
    .D(_129_),
    .Q(shot),
    .RN(_084_),
    .SE(test_se),
    .SI(confirm)
  );
  SDFFR_X1 _512_ (
    .CK(CK),
    .D(_104_),
    .Q(canale_0_),
    .RN(_047_),
    .SE(test_se),
    .SI(shot)
  );
  SDFFR_X1 _513_ (
    .CK(CK),
    .D(_103_),
    .Q(canale_1_),
    .RN(_046_),
    .SE(test_se),
    .SI(canale_0_)
  );
  SDFFR_X1 _514_ (
    .CK(CK),
    .D(_102_),
    .Q(canale_2_),
    .RN(_045_),
    .SE(test_se),
    .SI(canale_1_)
  );
  SDFFR_X1 _515_ (
    .CK(CK),
    .D(_130_),
    .Q(errorr),
    .RN(_085_),
    .SE(test_se),
    .SI(canale_2_)
  );
  SDFFR_X1 _516_ (
    .CK(CK),
    .D(_131_),
    .Q(mux_en),
    .RN(_086_),
    .SE(test_se),
    .SI(errorr)
  );
  SDFFR_X1 _517_ (
    .CK(CK),
    .D(_132_),
    .Q(send),
    .RN(_087_),
    .SE(test_se),
    .SI(mux_en)
  );
  SDFFR_X1 _518_ (
    .CK(CK),
    .D(_133_),
    .Q(mpx),
    .RN(_088_),
    .SE(test_se),
    .SI(send)
  );
  SDFFR_X1 _519_ (
    .CK(CK),
    .D(_134_),
    .Q(load),
    .RN(_089_),
    .SE(test_se),
    .SI(mpx)
  );
  SDFFS_X1 _520_ (
    .CK(CK),
    .D(_013_),
    .Q(S1_0_),
    .SN(_040_),
    .SE(test_se),
    .SI(load)
  );
  SDFFR_X1 _521_ (
    .CK(CK),
    .D(S1_7_),
    .Q(S1_1_),
    .RN(_039_),
    .SE(test_se),
    .SI(S1_0_)
  );
  SDFFR_X1 _522_ (
    .CK(CK),
    .D(S1_4_),
    .Q(S1_2_),
    .RN(_037_),
    .SE(test_se),
    .SI(S1_1_)
  );
  SDFFR_X1 _523_ (
    .CK(CK),
    .D(_014_),
    .Q(S1_3_),
    .RN(_075_),
    .SE(test_se),
    .SI(S1_2_)
  );
  SDFFR_X1 _524_ (
    .CK(CK),
    .D(S1_0_),
    .Q(S1_4_),
    .RN(_073_),
    .SE(test_se),
    .SI(S1_3_)
  );
  SDFFR_X1 _525_ (
    .CK(CK),
    .D(_020_),
    .Q(S1_5_),
    .RN(_072_),
    .SE(test_se),
    .SI(S1_4_)
  );
  SDFFR_X1 _526_ (
    .CK(CK),
    .D(_021_),
    .Q(S1_6_),
    .RN(_071_),
    .SE(test_se),
    .SI(S1_5_)
  );
  SDFFR_X1 _527_ (
    .CK(CK),
    .D(S1_3_),
    .Q(S1_7_),
    .RN(_038_),
    .SE(test_se),
    .SI(S1_6_)
  );
  assign test_so = S1_7_;
endmodule
