/* Generated by Yosys 0.38 (git sha1 543faed9c, gcc 11.4.0-1ubuntu1~22.04.3 -fPIC -Os) */

module b13(reset, eoc, soc, load_dato, add_mpx2, canale_0_, canale_1_, canale_2_, canale_3_, mux_en, CK, data_in_0_, data_in_1_, data_in_2_, data_in_3_, data_in_4_, data_in_5_, data_in_6_, data_in_7_, dsr, errorr, data_out, test_si, test_so, test_se);
  input test_si;
  input test_se;
  output test_so;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire S1_0_;
  wire S1_1_;
  wire S1_2_;
  wire S1_3_;
  wire S1_4_;
  wire S1_5_;
  wire S1_6_;
  wire S1_7_;
  wire S2_0_;
  wire S2_1_;
  wire S2_2_;
  wire S2_3_;
  output add_mpx2;
  wire add_mpx2;
    output canale_0_;
  output canale_1_;
  output canale_2_;
  output canale_3_;
    wire canale_0_;
  wire canale_1_;
  wire canale_2_;
  wire canale_3_;
  input CK;
  wire CK;
  wire confirm;
  wire conta_tmp_3_;
  wire conta_tmp_4_;
  wire conta_tmp_5_;
  wire conta_tmp_6_;
  wire conta_tmp_7_;
    input data_in_0_;
  input data_in_1_;
  input data_in_2_;
  input data_in_3_;
  input data_in_4_;
  input data_in_5_;
  input data_in_6_;
  input data_in_7_;
    wire data_in_0_;
  wire data_in_1_;
  wire data_in_2_;
  wire data_in_3_;
  wire data_in_4_;
  wire data_in_5_;
  wire data_in_6_;
  wire data_in_7_;
  output data_out;
  wire data_out;
  input dsr;
  wire dsr;
  input eoc;
  wire eoc;
  output errorr;
  wire errorr;
  wire itfc_state_0_;
  wire itfc_state_1_;
  wire itfc_state_2_;
  wire itfc_state_3_;
  wire load;
  output load_dato;
  wire load_dato;
  wire mpx;
  output mux_en;
  wire mux_en;
  wire next_bit_0_;
  wire next_bit_1_;
  wire next_bit_2_;
  wire next_bit_3_;
  wire next_bit_4_;
  wire next_bit_5_;
  wire next_bit_6_;
  wire next_bit_7_;
  wire next_bit_8_;
  wire next_bit_9_;
  wire out_reg_0_;
  wire out_reg_1_;
  wire out_reg_2_;
  wire out_reg_3_;
  wire out_reg_4_;
  wire out_reg_5_;
  wire out_reg_6_;
  wire out_reg_7_;
  wire rdy;
  input reset;
  wire reset;
  wire send;
  wire send_data;
  wire send_en;
  wire shot;
  output soc;
  wire soc;
  wire tre;
  wire tx_conta_0_;
  wire tx_conta_10_;
  wire tx_conta_11_;
  wire tx_conta_12_;
  wire tx_conta_13_;
  wire tx_conta_14_;
  wire tx_conta_15_;
  wire tx_conta_16_;
  wire tx_conta_17_;
  wire tx_conta_18_;
  wire tx_conta_19_;
  wire tx_conta_1_;
  wire tx_conta_20_;
  wire tx_conta_21_;
  wire tx_conta_22_;
  wire tx_conta_23_;
  wire tx_conta_24_;
  wire tx_conta_25_;
  wire tx_conta_26_;
  wire tx_conta_27_;
  wire tx_conta_28_;
  wire tx_conta_29_;
  wire tx_conta_2_;
  wire tx_conta_30_;
  wire tx_conta_31_;
  wire tx_conta_3_;
  wire tx_conta_4_;
  wire tx_conta_5_;
  wire tx_conta_6_;
  wire tx_conta_7_;
  wire tx_conta_8_;
  wire tx_conta_9_;
  wire tx_end;
  INV_X1 _383_ (
    .A(shot),
    .ZN(_184_)
  );
  INV_X1 _384_ (
    .A(load),
    .ZN(_185_)
  );
  INV_X1 _385_ (
    .A(itfc_state_3_),
    .ZN(_186_)
  );
  INV_X1 _386_ (
    .A(send_en),
    .ZN(_187_)
  );
  INV_X1 _387_ (
    .A(tx_conta_3_),
    .ZN(_188_)
  );
  INV_X1 _388_ (
    .A(S2_1_),
    .ZN(_189_)
  );
  INV_X1 _389_ (
    .A(S1_6_),
    .ZN(_190_)
  );
  INV_X1 _390_ (
    .A(S1_5_),
    .ZN(_191_)
  );
  INV_X1 _391_ (
    .A(_032_),
    .ZN(_192_)
  );
  INV_X1 _392_ (
    .A(S2_0_),
    .ZN(_193_)
  );
  INV_X1 _393_ (
    .A(reset),
    .ZN(_034_)
  );
  AND4_X1 _394_ (
    .A1(conta_tmp_3_),
    .A2(canale_2_),
    .A3(canale_1_),
    .A4(canale_0_),
    .ZN(_194_)
  );
  AND2_X1 _395_ (
    .A1(conta_tmp_4_),
    .A2(_194_),
    .ZN(_195_)
  );
  NAND2_X1 _396_ (
    .A1(conta_tmp_5_),
    .A2(_195_),
    .ZN(_196_)
  );
  NAND3_X1 _397_ (
    .A1(conta_tmp_6_),
    .A2(conta_tmp_5_),
    .A3(_195_),
    .ZN(_197_)
  );
  XNOR2_X1 _398_ (
    .A(conta_tmp_7_),
    .B(_197_),
    .ZN(_198_)
  );
  MUX2_X1 _399_ (
    .A(conta_tmp_7_),
    .B(_198_),
    .S(S1_3_),
    .Z(_183_)
  );
  XNOR2_X1 _400_ (
    .A(conta_tmp_6_),
    .B(_196_),
    .ZN(_199_)
  );
  MUX2_X1 _401_ (
    .A(conta_tmp_6_),
    .B(_199_),
    .S(S1_3_),
    .Z(_182_)
  );
  XOR2_X1 _402_ (
    .A(conta_tmp_5_),
    .B(_195_),
    .Z(_200_)
  );
  MUX2_X1 _403_ (
    .A(conta_tmp_5_),
    .B(_200_),
    .S(S1_3_),
    .Z(_181_)
  );
  XOR2_X1 _404_ (
    .A(conta_tmp_4_),
    .B(_194_),
    .Z(_201_)
  );
  MUX2_X1 _405_ (
    .A(conta_tmp_4_),
    .B(_201_),
    .S(S1_3_),
    .Z(_180_)
  );
  NAND2_X1 _406_ (
    .A1(S1_3_),
    .A2(canale_0_),
    .ZN(_202_)
  );
  NAND3_X1 _407_ (
    .A1(S1_3_),
    .A2(canale_1_),
    .A3(canale_0_),
    .ZN(_203_)
  );
  NAND4_X1 _408_ (
    .A1(S1_3_),
    .A2(canale_2_),
    .A3(canale_1_),
    .A4(canale_0_),
    .ZN(_204_)
  );
  NOR4_X1 _409_ (
    .A1(_198_),
    .A2(_199_),
    .A3(_200_),
    .A4(_201_),
    .ZN(_205_)
  );
  NOR2_X1 _410_ (
    .A1(_204_),
    .A2(_205_),
    .ZN(_206_)
  );
  MUX2_X1 _411_ (
    .A(_206_),
    .B(_204_),
    .S(conta_tmp_3_),
    .Z(_179_)
  );
  AND2_X1 _412_ (
    .A1(rdy),
    .A2(S1_6_),
    .ZN(_010_)
  );
  NOR2_X1 _413_ (
    .A1(rdy),
    .A2(_190_),
    .ZN(_207_)
  );
  NOR2_X1 _414_ (
    .A1(S1_6_),
    .A2(S1_7_),
    .ZN(_208_)
  );
  NOR2_X1 _415_ (
    .A1(_207_),
    .A2(_208_),
    .ZN(_209_)
  );
  MUX2_X1 _416_ (
    .A(send_data),
    .B(_006_),
    .S(_209_),
    .Z(_178_)
  );
  XNOR2_X1 _417_ (
    .A(canale_2_),
    .B(_203_),
    .ZN(_177_)
  );
  XNOR2_X1 _418_ (
    .A(canale_1_),
    .B(_202_),
    .ZN(_176_)
  );
  XOR2_X1 _419_ (
    .A(S1_3_),
    .B(canale_0_),
    .Z(_175_)
  );
  NOR2_X1 _420_ (
    .A1(_191_),
    .A2(eoc),
    .ZN(_011_)
  );
  AND2_X1 _421_ (
    .A1(S1_5_),
    .A2(eoc),
    .ZN(_210_)
  );
  NOR2_X1 _422_ (
    .A1(S1_5_),
    .A2(S1_0_),
    .ZN(_211_)
  );
  NOR2_X1 _423_ (
    .A1(_210_),
    .A2(_211_),
    .ZN(_212_)
  );
  MUX2_X1 _424_ (
    .A(mux_en),
    .B(_003_),
    .S(_212_),
    .Z(_174_)
  );
  NOR2_X1 _425_ (
    .A1(S1_3_),
    .A2(S1_5_),
    .ZN(_213_)
  );
  NOR2_X1 _426_ (
    .A1(_210_),
    .A2(_213_),
    .ZN(_214_)
  );
  MUX2_X1 _427_ (
    .A(load_dato),
    .B(_002_),
    .S(_214_),
    .Z(_173_)
  );
  NOR2_X1 _428_ (
    .A1(S1_3_),
    .A2(S1_2_),
    .ZN(_215_)
  );
  MUX2_X1 _429_ (
    .A(_002_),
    .B(soc),
    .S(_215_),
    .Z(_172_)
  );
  MUX2_X1 _430_ (
    .A(S2_2_),
    .B(_033_),
    .S(S2_1_),
    .Z(_216_)
  );
  MUX2_X1 _431_ (
    .A(shot),
    .B(_004_),
    .S(_216_),
    .Z(_171_)
  );
  NAND2_X1 _432_ (
    .A1(confirm),
    .A2(S2_1_),
    .ZN(_217_)
  );
  NOR2_X1 _433_ (
    .A1(mpx),
    .A2(_217_),
    .ZN(_218_)
  );
  NOR2_X1 _434_ (
    .A1(S2_1_),
    .A2(S2_0_),
    .ZN(_219_)
  );
  NOR2_X1 _435_ (
    .A1(send_data),
    .A2(_193_),
    .ZN(_220_)
  );
  NOR2_X1 _436_ (
    .A1(confirm),
    .A2(_189_),
    .ZN(_221_)
  );
  NOR4_X1 _437_ (
    .A1(_218_),
    .A2(_219_),
    .A3(_220_),
    .A4(_221_),
    .ZN(_222_)
  );
  MUX2_X1 _438_ (
    .A(rdy),
    .B(_004_),
    .S(_222_),
    .Z(_170_)
  );
  MUX2_X1 _439_ (
    .A(_029_),
    .B(mpx),
    .S(_217_),
    .Z(_169_)
  );
  OR2_X1 _440_ (
    .A1(add_mpx2),
    .A2(_218_),
    .ZN(_168_)
  );
  AND2_X1 _441_ (
    .A1(shot),
    .A2(itfc_state_0_),
    .ZN(_013_)
  );
  NAND2_X1 _442_ (
    .A1(_184_),
    .A2(itfc_state_0_),
    .ZN(_223_)
  );
  MUX2_X1 _443_ (
    .A(itfc_state_2_),
    .B(shot),
    .S(itfc_state_0_),
    .Z(_224_)
  );
  MUX2_X1 _444_ (
    .A(load),
    .B(_001_),
    .S(_224_),
    .Z(_167_)
  );
  NOR2_X1 _445_ (
    .A1(itfc_state_2_),
    .A2(itfc_state_1_),
    .ZN(_225_)
  );
  MUX2_X1 _446_ (
    .A(_005_),
    .B(send),
    .S(_225_),
    .Z(_166_)
  );
  NAND2_X1 _447_ (
    .A1(_186_),
    .A2(itfc_state_0_),
    .ZN(_226_)
  );
  NAND2_X1 _448_ (
    .A1(itfc_state_3_),
    .A2(tx_end),
    .ZN(_227_)
  );
  NAND2_X1 _449_ (
    .A1(confirm),
    .A2(_226_),
    .ZN(_228_)
  );
  NAND2_X1 _450_ (
    .A1(_227_),
    .A2(_228_),
    .ZN(_165_)
  );
  NOR2_X1 _451_ (
    .A1(_185_),
    .A2(tre),
    .ZN(_229_)
  );
  MUX2_X1 _452_ (
    .A(out_reg_7_),
    .B(data_in_7_),
    .S(_229_),
    .Z(_164_)
  );
  MUX2_X1 _453_ (
    .A(out_reg_6_),
    .B(data_in_6_),
    .S(_229_),
    .Z(_163_)
  );
  MUX2_X1 _454_ (
    .A(out_reg_5_),
    .B(data_in_5_),
    .S(_229_),
    .Z(_162_)
  );
  MUX2_X1 _455_ (
    .A(out_reg_4_),
    .B(data_in_4_),
    .S(_229_),
    .Z(_161_)
  );
  MUX2_X1 _456_ (
    .A(out_reg_3_),
    .B(data_in_3_),
    .S(_229_),
    .Z(_160_)
  );
  MUX2_X1 _457_ (
    .A(out_reg_2_),
    .B(data_in_2_),
    .S(_229_),
    .Z(_159_)
  );
  MUX2_X1 _458_ (
    .A(out_reg_1_),
    .B(data_in_1_),
    .S(_229_),
    .Z(_158_)
  );
  MUX2_X1 _459_ (
    .A(out_reg_0_),
    .B(data_in_0_),
    .S(_229_),
    .Z(_157_)
  );
  AND3_X1 _460_ (
    .A1(send),
    .A2(tre),
    .A3(dsr),
    .ZN(_230_)
  );
  NOR2_X1 _461_ (
    .A1(load),
    .A2(errorr),
    .ZN(_231_)
  );
  NOR2_X1 _462_ (
    .A1(_229_),
    .A2(_231_),
    .ZN(_232_)
  );
  NOR2_X1 _463_ (
    .A1(send),
    .A2(_232_),
    .ZN(_233_)
  );
  NOR2_X1 _464_ (
    .A1(_230_),
    .A2(_233_),
    .ZN(_156_)
  );
  AND2_X1 _465_ (
    .A1(tx_conta_31_),
    .A2(_187_),
    .ZN(_155_)
  );
  AND2_X1 _466_ (
    .A1(_187_),
    .A2(tx_conta_30_),
    .ZN(_154_)
  );
  AND2_X1 _467_ (
    .A1(_187_),
    .A2(tx_conta_29_),
    .ZN(_153_)
  );
  AND2_X1 _468_ (
    .A1(_187_),
    .A2(tx_conta_28_),
    .ZN(_152_)
  );
  AND2_X1 _469_ (
    .A1(_187_),
    .A2(tx_conta_27_),
    .ZN(_151_)
  );
  AND2_X1 _470_ (
    .A1(_187_),
    .A2(tx_conta_26_),
    .ZN(_150_)
  );
  AND2_X1 _471_ (
    .A1(_187_),
    .A2(tx_conta_25_),
    .ZN(_149_)
  );
  AND2_X1 _472_ (
    .A1(_187_),
    .A2(tx_conta_24_),
    .ZN(_148_)
  );
  AND2_X1 _473_ (
    .A1(_187_),
    .A2(tx_conta_23_),
    .ZN(_147_)
  );
  AND2_X1 _474_ (
    .A1(_187_),
    .A2(tx_conta_22_),
    .ZN(_146_)
  );
  AND2_X1 _475_ (
    .A1(_187_),
    .A2(tx_conta_21_),
    .ZN(_145_)
  );
  AND2_X1 _476_ (
    .A1(_187_),
    .A2(tx_conta_20_),
    .ZN(_144_)
  );
  AND2_X1 _477_ (
    .A1(_187_),
    .A2(tx_conta_19_),
    .ZN(_143_)
  );
  AND2_X1 _478_ (
    .A1(_187_),
    .A2(tx_conta_18_),
    .ZN(_142_)
  );
  AND2_X1 _479_ (
    .A1(_187_),
    .A2(tx_conta_17_),
    .ZN(_141_)
  );
  AND2_X1 _480_ (
    .A1(_187_),
    .A2(tx_conta_16_),
    .ZN(_140_)
  );
  AND2_X1 _481_ (
    .A1(_187_),
    .A2(tx_conta_15_),
    .ZN(_139_)
  );
  AND2_X1 _482_ (
    .A1(_187_),
    .A2(tx_conta_14_),
    .ZN(_138_)
  );
  AND2_X1 _483_ (
    .A1(_187_),
    .A2(tx_conta_13_),
    .ZN(_137_)
  );
  AND2_X1 _484_ (
    .A1(_187_),
    .A2(tx_conta_12_),
    .ZN(_136_)
  );
  AND2_X1 _485_ (
    .A1(_187_),
    .A2(tx_conta_11_),
    .ZN(_135_)
  );
  AND2_X1 _486_ (
    .A1(_187_),
    .A2(tx_conta_10_),
    .ZN(_134_)
  );
  AND2_X1 _487_ (
    .A1(_187_),
    .A2(tx_conta_9_),
    .ZN(_133_)
  );
  AND2_X1 _488_ (
    .A1(_187_),
    .A2(tx_conta_8_),
    .ZN(_132_)
  );
  AND2_X1 _489_ (
    .A1(_187_),
    .A2(tx_conta_7_),
    .ZN(_131_)
  );
  NOR3_X1 _490_ (
    .A1(tx_conta_2_),
    .A2(tx_conta_1_),
    .A3(tx_conta_0_),
    .ZN(_234_)
  );
  NOR2_X1 _491_ (
    .A1(_188_),
    .A2(_234_),
    .ZN(_235_)
  );
  OR2_X1 _492_ (
    .A1(tx_conta_4_),
    .A2(_235_),
    .ZN(_236_)
  );
  NAND3_X1 _493_ (
    .A1(tx_conta_6_),
    .A2(tx_conta_5_),
    .A3(_236_),
    .ZN(_237_)
  );
  NOR4_X1 _494_ (
    .A1(tx_conta_13_),
    .A2(tx_conta_12_),
    .A3(tx_conta_11_),
    .A4(tx_conta_10_),
    .ZN(_238_)
  );
  NOR4_X1 _495_ (
    .A1(tx_conta_17_),
    .A2(tx_conta_16_),
    .A3(tx_conta_15_),
    .A4(tx_conta_14_),
    .ZN(_239_)
  );
  NAND2_X1 _496_ (
    .A1(_238_),
    .A2(_239_),
    .ZN(_240_)
  );
  NOR4_X1 _497_ (
    .A1(tx_conta_9_),
    .A2(tx_conta_8_),
    .A3(tx_conta_7_),
    .A4(_240_),
    .ZN(_241_)
  );
  NOR2_X1 _498_ (
    .A1(tx_conta_31_),
    .A2(tx_conta_30_),
    .ZN(_242_)
  );
  NOR4_X1 _499_ (
    .A1(tx_conta_29_),
    .A2(tx_conta_28_),
    .A3(tx_conta_27_),
    .A4(tx_conta_26_),
    .ZN(_243_)
  );
  NOR4_X1 _500_ (
    .A1(tx_conta_21_),
    .A2(tx_conta_20_),
    .A3(tx_conta_19_),
    .A4(tx_conta_18_),
    .ZN(_244_)
  );
  NOR4_X1 _501_ (
    .A1(tx_conta_25_),
    .A2(tx_conta_24_),
    .A3(tx_conta_23_),
    .A4(tx_conta_22_),
    .ZN(_245_)
  );
  AND4_X1 _502_ (
    .A1(_242_),
    .A2(_243_),
    .A3(_244_),
    .A4(_245_),
    .ZN(_246_)
  );
  NAND3_X1 _503_ (
    .A1(_237_),
    .A2(_241_),
    .A3(_246_),
    .ZN(_247_)
  );
  AND2_X1 _504_ (
    .A1(send_en),
    .A2(_247_),
    .ZN(_248_)
  );
  NAND2_X1 _505_ (
    .A1(send_en),
    .A2(_247_),
    .ZN(_249_)
  );
  AND2_X1 _506_ (
    .A1(send_en),
    .A2(tx_conta_0_),
    .ZN(_250_)
  );
  AND2_X1 _507_ (
    .A1(tx_conta_1_),
    .A2(_250_),
    .ZN(_251_)
  );
  AND2_X1 _508_ (
    .A1(tx_conta_2_),
    .A2(_251_),
    .ZN(_252_)
  );
  AND2_X1 _509_ (
    .A1(tx_conta_3_),
    .A2(_252_),
    .ZN(_253_)
  );
  AND2_X1 _510_ (
    .A1(tx_conta_4_),
    .A2(_253_),
    .ZN(_254_)
  );
  AND2_X1 _511_ (
    .A1(tx_conta_5_),
    .A2(_254_),
    .ZN(_255_)
  );
  NOR2_X1 _512_ (
    .A1(tx_conta_6_),
    .A2(_255_),
    .ZN(_256_)
  );
  NOR2_X1 _513_ (
    .A1(_248_),
    .A2(_256_),
    .ZN(_130_)
  );
  NOR2_X1 _514_ (
    .A1(tx_conta_5_),
    .A2(_254_),
    .ZN(_257_)
  );
  NOR3_X1 _515_ (
    .A1(_248_),
    .A2(_255_),
    .A3(_257_),
    .ZN(_129_)
  );
  NOR2_X1 _516_ (
    .A1(tx_conta_4_),
    .A2(_253_),
    .ZN(_258_)
  );
  NOR3_X1 _517_ (
    .A1(_248_),
    .A2(_254_),
    .A3(_258_),
    .ZN(_128_)
  );
  NOR2_X1 _518_ (
    .A1(tx_conta_3_),
    .A2(_252_),
    .ZN(_259_)
  );
  NOR3_X1 _519_ (
    .A1(_248_),
    .A2(_253_),
    .A3(_259_),
    .ZN(_127_)
  );
  NOR2_X1 _520_ (
    .A1(tx_conta_2_),
    .A2(_251_),
    .ZN(_260_)
  );
  NOR3_X1 _521_ (
    .A1(_248_),
    .A2(_252_),
    .A3(_260_),
    .ZN(_126_)
  );
  NOR2_X1 _522_ (
    .A1(tx_conta_1_),
    .A2(_250_),
    .ZN(_261_)
  );
  NOR3_X1 _523_ (
    .A1(_248_),
    .A2(_251_),
    .A3(_261_),
    .ZN(_125_)
  );
  NOR2_X1 _524_ (
    .A1(send_en),
    .A2(tx_conta_0_),
    .ZN(_262_)
  );
  NOR3_X1 _525_ (
    .A1(_248_),
    .A2(_250_),
    .A3(_262_),
    .ZN(_124_)
  );
  OR2_X1 _526_ (
    .A1(S2_2_),
    .A2(_221_),
    .ZN(_015_)
  );
  OR2_X1 _527_ (
    .A1(S1_2_),
    .A2(_210_),
    .ZN(_030_)
  );
  AND2_X1 _528_ (
    .A1(_192_),
    .A2(_247_),
    .ZN(_263_)
  );
  NAND2_X1 _529_ (
    .A1(next_bit_0_),
    .A2(_263_),
    .ZN(_264_)
  );
  NAND2_X1 _530_ (
    .A1(next_bit_3_),
    .A2(_249_),
    .ZN(_265_)
  );
  NAND2_X1 _531_ (
    .A1(_264_),
    .A2(_265_),
    .ZN(_022_)
  );
  NAND2_X1 _532_ (
    .A1(next_bit_9_),
    .A2(_263_),
    .ZN(_266_)
  );
  NAND2_X1 _533_ (
    .A1(next_bit_1_),
    .A2(_249_),
    .ZN(_267_)
  );
  NAND2_X1 _534_ (
    .A1(_266_),
    .A2(_267_),
    .ZN(_020_)
  );
  AND2_X1 _535_ (
    .A1(send_data),
    .A2(S2_0_),
    .ZN(_268_)
  );
  OR2_X1 _536_ (
    .A1(_218_),
    .A2(_268_),
    .ZN(_016_)
  );
  NAND2_X1 _537_ (
    .A1(next_bit_4_),
    .A2(_263_),
    .ZN(_269_)
  );
  NAND2_X1 _538_ (
    .A1(next_bit_9_),
    .A2(_249_),
    .ZN(_270_)
  );
  NAND2_X1 _539_ (
    .A1(_269_),
    .A2(_270_),
    .ZN(_028_)
  );
  NAND2_X1 _540_ (
    .A1(next_bit_3_),
    .A2(_263_),
    .ZN(_271_)
  );
  NAND2_X1 _541_ (
    .A1(next_bit_8_),
    .A2(_249_),
    .ZN(_272_)
  );
  NAND2_X1 _542_ (
    .A1(_271_),
    .A2(_272_),
    .ZN(_027_)
  );
  NAND2_X1 _543_ (
    .A1(next_bit_2_),
    .A2(_263_),
    .ZN(_273_)
  );
  NAND2_X1 _544_ (
    .A1(next_bit_7_),
    .A2(_249_),
    .ZN(_274_)
  );
  NAND2_X1 _545_ (
    .A1(_273_),
    .A2(_274_),
    .ZN(_026_)
  );
  NAND2_X1 _546_ (
    .A1(next_bit_5_),
    .A2(_263_),
    .ZN(_275_)
  );
  NAND2_X1 _547_ (
    .A1(next_bit_0_),
    .A2(_249_),
    .ZN(_276_)
  );
  NAND2_X1 _548_ (
    .A1(_275_),
    .A2(_276_),
    .ZN(_019_)
  );
  NAND2_X1 _549_ (
    .A1(next_bit_1_),
    .A2(_263_),
    .ZN(_277_)
  );
  NAND2_X1 _550_ (
    .A1(next_bit_6_),
    .A2(_249_),
    .ZN(_278_)
  );
  NAND2_X1 _551_ (
    .A1(_277_),
    .A2(_278_),
    .ZN(_025_)
  );
  NOR2_X1 _552_ (
    .A1(_186_),
    .A2(tx_end),
    .ZN(_279_)
  );
  OR2_X1 _553_ (
    .A1(itfc_state_1_),
    .A2(_279_),
    .ZN(_018_)
  );
  OR2_X1 _554_ (
    .A1(S2_3_),
    .A2(_220_),
    .ZN(_014_)
  );
  NAND2_X1 _555_ (
    .A1(next_bit_6_),
    .A2(_263_),
    .ZN(_280_)
  );
  NAND2_X1 _556_ (
    .A1(next_bit_5_),
    .A2(_249_),
    .ZN(_281_)
  );
  NAND2_X1 _557_ (
    .A1(_280_),
    .A2(_281_),
    .ZN(_024_)
  );
  NAND2_X1 _558_ (
    .A1(next_bit_8_),
    .A2(_263_),
    .ZN(_282_)
  );
  NAND2_X1 _559_ (
    .A1(next_bit_2_),
    .A2(_249_),
    .ZN(_283_)
  );
  NAND2_X1 _560_ (
    .A1(_282_),
    .A2(_283_),
    .ZN(_021_)
  );
  NAND2_X1 _561_ (
    .A1(_223_),
    .A2(_227_),
    .ZN(_017_)
  );
  NAND2_X1 _562_ (
    .A1(next_bit_7_),
    .A2(_263_),
    .ZN(_284_)
  );
  NAND2_X1 _563_ (
    .A1(next_bit_4_),
    .A2(_249_),
    .ZN(_285_)
  );
  NAND2_X1 _564_ (
    .A1(_284_),
    .A2(_285_),
    .ZN(_023_)
  );
  OR2_X1 _565_ (
    .A1(S1_1_),
    .A2(_207_),
    .ZN(_031_)
  );
  NOR3_X1 _566_ (
    .A1(next_bit_2_),
    .A2(next_bit_7_),
    .A3(next_bit_6_),
    .ZN(_286_)
  );
  NOR4_X1 _567_ (
    .A1(next_bit_3_),
    .A2(next_bit_0_),
    .A3(next_bit_1_),
    .A4(next_bit_8_),
    .ZN(_287_)
  );
  NAND2_X1 _568_ (
    .A1(_286_),
    .A2(_287_),
    .ZN(_288_)
  );
  NOR3_X1 _569_ (
    .A1(next_bit_9_),
    .A2(next_bit_4_),
    .A3(_288_),
    .ZN(_289_)
  );
  NAND2_X1 _570_ (
    .A1(out_reg_2_),
    .A2(next_bit_9_),
    .ZN(_290_)
  );
  NAND2_X1 _571_ (
    .A1(out_reg_3_),
    .A2(next_bit_4_),
    .ZN(_291_)
  );
  NAND2_X1 _572_ (
    .A1(out_reg_7_),
    .A2(next_bit_3_),
    .ZN(_292_)
  );
  NAND2_X1 _573_ (
    .A1(out_reg_4_),
    .A2(next_bit_7_),
    .ZN(_293_)
  );
  NAND4_X1 _574_ (
    .A1(_290_),
    .A2(_291_),
    .A3(_292_),
    .A4(_293_),
    .ZN(_294_)
  );
  NAND2_X1 _575_ (
    .A1(out_reg_6_),
    .A2(next_bit_8_),
    .ZN(_295_)
  );
  NAND2_X1 _576_ (
    .A1(out_reg_1_),
    .A2(next_bit_1_),
    .ZN(_296_)
  );
  NAND2_X1 _577_ (
    .A1(out_reg_0_),
    .A2(next_bit_6_),
    .ZN(_297_)
  );
  NAND2_X1 _578_ (
    .A1(out_reg_5_),
    .A2(next_bit_2_),
    .ZN(_298_)
  );
  NAND4_X1 _579_ (
    .A1(_295_),
    .A2(_296_),
    .A3(_297_),
    .A4(_298_),
    .ZN(_299_)
  );
  NOR3_X1 _580_ (
    .A1(_289_),
    .A2(_294_),
    .A3(_299_),
    .ZN(_300_)
  );
  NAND2_X1 _581_ (
    .A1(_263_),
    .A2(_300_),
    .ZN(_000_)
  );
  OR3_X1 _582_ (
    .A1(load),
    .A2(tx_end),
    .A3(tre),
    .ZN(_008_)
  );
  NOR2_X1 _583_ (
    .A1(_187_),
    .A2(tx_end),
    .ZN(_301_)
  );
  OR2_X1 _584_ (
    .A1(_230_),
    .A2(_301_),
    .ZN(_007_)
  );
  AND3_X1 _585_ (
    .A1(mpx),
    .A2(confirm),
    .A3(S2_1_),
    .ZN(_012_)
  );
  AND2_X1 _586_ (
    .A1(next_bit_5_),
    .A2(_248_),
    .ZN(_009_)
  );
  INV_X1 _587_ (
    .A(reset),
    .ZN(_035_)
  );
  INV_X1 _588_ (
    .A(reset),
    .ZN(_036_)
  );
  INV_X1 _589_ (
    .A(reset),
    .ZN(_037_)
  );
  INV_X1 _590_ (
    .A(reset),
    .ZN(_038_)
  );
  INV_X1 _591_ (
    .A(reset),
    .ZN(_039_)
  );
  INV_X1 _592_ (
    .A(reset),
    .ZN(_040_)
  );
  INV_X1 _593_ (
    .A(reset),
    .ZN(_041_)
  );
  INV_X1 _594_ (
    .A(reset),
    .ZN(_042_)
  );
  INV_X1 _595_ (
    .A(reset),
    .ZN(_043_)
  );
  INV_X1 _596_ (
    .A(reset),
    .ZN(_044_)
  );
  INV_X1 _597_ (
    .A(reset),
    .ZN(_045_)
  );
  INV_X1 _598_ (
    .A(reset),
    .ZN(_046_)
  );
  INV_X1 _599_ (
    .A(reset),
    .ZN(_047_)
  );
  INV_X1 _600_ (
    .A(reset),
    .ZN(_048_)
  );
  INV_X1 _601_ (
    .A(reset),
    .ZN(_049_)
  );
  INV_X1 _602_ (
    .A(reset),
    .ZN(_050_)
  );
  INV_X1 _603_ (
    .A(reset),
    .ZN(_051_)
  );
  INV_X1 _604_ (
    .A(reset),
    .ZN(_052_)
  );
  INV_X1 _605_ (
    .A(reset),
    .ZN(_053_)
  );
  INV_X1 _606_ (
    .A(reset),
    .ZN(_054_)
  );
  INV_X1 _607_ (
    .A(reset),
    .ZN(_055_)
  );
  INV_X1 _608_ (
    .A(reset),
    .ZN(_056_)
  );
  INV_X1 _609_ (
    .A(reset),
    .ZN(_057_)
  );
  INV_X1 _610_ (
    .A(reset),
    .ZN(_058_)
  );
  INV_X1 _611_ (
    .A(reset),
    .ZN(_059_)
  );
  INV_X1 _612_ (
    .A(reset),
    .ZN(_060_)
  );
  INV_X1 _613_ (
    .A(reset),
    .ZN(_061_)
  );
  INV_X1 _614_ (
    .A(reset),
    .ZN(_062_)
  );
  INV_X1 _615_ (
    .A(reset),
    .ZN(_063_)
  );
  INV_X1 _616_ (
    .A(reset),
    .ZN(_064_)
  );
  INV_X1 _617_ (
    .A(reset),
    .ZN(_065_)
  );
  INV_X1 _618_ (
    .A(reset),
    .ZN(_066_)
  );
  INV_X1 _619_ (
    .A(reset),
    .ZN(_067_)
  );
  INV_X1 _620_ (
    .A(reset),
    .ZN(_068_)
  );
  INV_X1 _621_ (
    .A(reset),
    .ZN(_069_)
  );
  INV_X1 _622_ (
    .A(reset),
    .ZN(_070_)
  );
  INV_X1 _623_ (
    .A(reset),
    .ZN(_071_)
  );
  INV_X1 _624_ (
    .A(reset),
    .ZN(_072_)
  );
  INV_X1 _625_ (
    .A(reset),
    .ZN(_073_)
  );
  INV_X1 _626_ (
    .A(reset),
    .ZN(_074_)
  );
  INV_X1 _627_ (
    .A(reset),
    .ZN(_075_)
  );
  INV_X1 _628_ (
    .A(reset),
    .ZN(_076_)
  );
  INV_X1 _629_ (
    .A(reset),
    .ZN(_077_)
  );
  INV_X1 _630_ (
    .A(reset),
    .ZN(_078_)
  );
  INV_X1 _631_ (
    .A(reset),
    .ZN(_079_)
  );
  INV_X1 _632_ (
    .A(reset),
    .ZN(_080_)
  );
  INV_X1 _633_ (
    .A(reset),
    .ZN(_081_)
  );
  INV_X1 _634_ (
    .A(reset),
    .ZN(_082_)
  );
  INV_X1 _635_ (
    .A(reset),
    .ZN(_083_)
  );
  INV_X1 _636_ (
    .A(reset),
    .ZN(_084_)
  );
  INV_X1 _637_ (
    .A(reset),
    .ZN(_085_)
  );
  INV_X1 _638_ (
    .A(reset),
    .ZN(_086_)
  );
  INV_X1 _639_ (
    .A(reset),
    .ZN(_087_)
  );
  INV_X1 _640_ (
    .A(reset),
    .ZN(_088_)
  );
  INV_X1 _641_ (
    .A(reset),
    .ZN(_089_)
  );
  INV_X1 _642_ (
    .A(reset),
    .ZN(_090_)
  );
  INV_X1 _643_ (
    .A(reset),
    .ZN(_091_)
  );
  INV_X1 _644_ (
    .A(reset),
    .ZN(_092_)
  );
  INV_X1 _645_ (
    .A(reset),
    .ZN(_093_)
  );
  INV_X1 _646_ (
    .A(reset),
    .ZN(_094_)
  );
  INV_X1 _647_ (
    .A(reset),
    .ZN(_095_)
  );
  INV_X1 _648_ (
    .A(reset),
    .ZN(_096_)
  );
  INV_X1 _649_ (
    .A(reset),
    .ZN(_097_)
  );
  INV_X1 _650_ (
    .A(reset),
    .ZN(_098_)
  );
  INV_X1 _651_ (
    .A(reset),
    .ZN(_099_)
  );
  INV_X1 _652_ (
    .A(reset),
    .ZN(_100_)
  );
  INV_X1 _653_ (
    .A(reset),
    .ZN(_101_)
  );
  INV_X1 _654_ (
    .A(reset),
    .ZN(_102_)
  );
  INV_X1 _655_ (
    .A(reset),
    .ZN(_103_)
  );
  INV_X1 _656_ (
    .A(reset),
    .ZN(_104_)
  );
  INV_X1 _657_ (
    .A(reset),
    .ZN(_105_)
  );
  INV_X1 _658_ (
    .A(reset),
    .ZN(_106_)
  );
  INV_X1 _659_ (
    .A(reset),
    .ZN(_107_)
  );
  INV_X1 _660_ (
    .A(reset),
    .ZN(_108_)
  );
  INV_X1 _661_ (
    .A(reset),
    .ZN(_109_)
  );
  INV_X1 _662_ (
    .A(reset),
    .ZN(_110_)
  );
  INV_X1 _663_ (
    .A(reset),
    .ZN(_111_)
  );
  INV_X1 _664_ (
    .A(reset),
    .ZN(_112_)
  );
  INV_X1 _665_ (
    .A(reset),
    .ZN(_113_)
  );
  INV_X1 _666_ (
    .A(reset),
    .ZN(_114_)
  );
  INV_X1 _667_ (
    .A(reset),
    .ZN(_115_)
  );
  INV_X1 _668_ (
    .A(reset),
    .ZN(_116_)
  );
  INV_X1 _669_ (
    .A(reset),
    .ZN(_117_)
  );
  INV_X1 _670_ (
    .A(reset),
    .ZN(_118_)
  );
  INV_X1 _671_ (
    .A(reset),
    .ZN(_119_)
  );
  INV_X1 _672_ (
    .A(reset),
    .ZN(_120_)
  );
  INV_X1 _673_ (
    .A(reset),
    .ZN(_121_)
  );
  INV_X1 _674_ (
    .A(reset),
    .ZN(_122_)
  );
  INV_X1 _675_ (
    .A(reset),
    .ZN(_123_)
  );
  SDFFRS_X1 _676_ (
    .CK(CK),
    .D(_017_),
    .Q(itfc_state_0_),
    .RN(_const1_),
    .SN(_034_),
    .SE(test_se),
    .SI(test_si)
  );
  SDFFR_X1 _677_ (
    .CK(CK),
    .D(itfc_state_2_),
    .Q(itfc_state_1_),
    .QN(_005_),
    .RN(_035_),
    .SE(test_se),
    .SI(itfc_state_0_)
  );
  SDFFR_X1 _678_ (
    .CK(CK),
    .D(_013_),
    .Q(itfc_state_2_),
    .QN(_001_),
    .RN(_036_),
    .SE(test_se),
    .SI(itfc_state_1_)
  );
  SDFFR_X1 _679_ (
    .CK(CK),
    .D(_018_),
    .Q(itfc_state_3_),
    .RN(_037_),
    .SE(test_se),
    .SI(itfc_state_2_)
  );
  SDFFR_X1 _680_ (
    .CK(CK),
    .D(_000_),
    .Q(data_out),
    .RN(_038_),
    .SE(test_se),
    .SI(itfc_state_3_)
  );
  SDFFR_X1 _681_ (
    .CK(CK),
    .D(_009_),
    .Q(tx_end),
    .RN(_039_),
    .SE(test_se),
    .SI(data_out)
  );
  SDFFR_X1 _682_ (
    .CK(CK),
    .D(_124_),
    .Q(tx_conta_0_),
    .RN(_040_),
    .SE(test_se),
    .SI(tx_end)
  );
  SDFFR_X1 _683_ (
    .CK(CK),
    .D(_125_),
    .Q(tx_conta_1_),
    .RN(_041_),
    .SE(test_se),
    .SI(tx_conta_0_)
  );
  SDFFR_X1 _684_ (
    .CK(CK),
    .D(_126_),
    .Q(tx_conta_2_),
    .RN(_042_),
    .SE(test_se),
    .SI(tx_conta_1_)
  );
  SDFFR_X1 _685_ (
    .CK(CK),
    .D(_127_),
    .Q(tx_conta_3_),
    .RN(_043_),
    .SE(test_se),
    .SI(tx_conta_2_)
  );
  SDFFR_X1 _686_ (
    .CK(CK),
    .D(_128_),
    .Q(tx_conta_4_),
    .RN(_044_),
    .SE(test_se),
    .SI(tx_conta_3_)
  );
  SDFFR_X1 _687_ (
    .CK(CK),
    .D(_129_),
    .Q(tx_conta_5_),
    .RN(_045_),
    .SE(test_se),
    .SI(tx_conta_4_)
  );
  SDFFR_X1 _688_ (
    .CK(CK),
    .D(_130_),
    .Q(tx_conta_6_),
    .RN(_046_),
    .SE(test_se),
    .SI(tx_conta_5_)
  );
  SDFFR_X1 _689_ (
    .CK(CK),
    .D(_131_),
    .Q(tx_conta_7_),
    .RN(_047_),
    .SE(test_se),
    .SI(tx_conta_6_)
  );
  SDFFR_X1 _690_ (
    .CK(CK),
    .D(_132_),
    .Q(tx_conta_8_),
    .RN(_048_),
    .SE(test_se),
    .SI(tx_conta_7_)
  );
  SDFFR_X1 _691_ (
    .CK(CK),
    .D(_133_),
    .Q(tx_conta_9_),
    .RN(_049_),
    .SE(test_se),
    .SI(tx_conta_8_)
  );
  SDFFR_X1 _692_ (
    .CK(CK),
    .D(_134_),
    .Q(tx_conta_10_),
    .RN(_050_),
    .SE(test_se),
    .SI(tx_conta_9_)
  );
  SDFFR_X1 _693_ (
    .CK(CK),
    .D(_135_),
    .Q(tx_conta_11_),
    .RN(_051_),
    .SE(test_se),
    .SI(tx_conta_10_)
  );
  SDFFR_X1 _694_ (
    .CK(CK),
    .D(_136_),
    .Q(tx_conta_12_),
    .RN(_052_),
    .SE(test_se),
    .SI(tx_conta_11_)
  );
  SDFFR_X1 _695_ (
    .CK(CK),
    .D(_137_),
    .Q(tx_conta_13_),
    .RN(_053_),
    .SE(test_se),
    .SI(tx_conta_12_)
  );
  SDFFR_X1 _696_ (
    .CK(CK),
    .D(_138_),
    .Q(tx_conta_14_),
    .RN(_054_),
    .SE(test_se),
    .SI(tx_conta_13_)
  );
  SDFFR_X1 _697_ (
    .CK(CK),
    .D(_139_),
    .Q(tx_conta_15_),
    .RN(_055_),
    .SE(test_se),
    .SI(tx_conta_14_)
  );
  SDFFR_X1 _698_ (
    .CK(CK),
    .D(_140_),
    .Q(tx_conta_16_),
    .RN(_056_),
    .SE(test_se),
    .SI(tx_conta_15_)
  );
  SDFFR_X1 _699_ (
    .CK(CK),
    .D(_141_),
    .Q(tx_conta_17_),
    .RN(_057_),
    .SE(test_se),
    .SI(tx_conta_16_)
  );
  SDFFR_X1 _700_ (
    .CK(CK),
    .D(_142_),
    .Q(tx_conta_18_),
    .RN(_058_),
    .SE(test_se),
    .SI(tx_conta_17_)
  );
  SDFFR_X1 _701_ (
    .CK(CK),
    .D(_143_),
    .Q(tx_conta_19_),
    .RN(_059_),
    .SE(test_se),
    .SI(tx_conta_18_)
  );
  SDFFR_X1 _702_ (
    .CK(CK),
    .D(_144_),
    .Q(tx_conta_20_),
    .RN(_060_),
    .SE(test_se),
    .SI(tx_conta_19_)
  );
  SDFFR_X1 _703_ (
    .CK(CK),
    .D(_145_),
    .Q(tx_conta_21_),
    .RN(_061_),
    .SE(test_se),
    .SI(tx_conta_20_)
  );
  SDFFR_X1 _704_ (
    .CK(CK),
    .D(_146_),
    .Q(tx_conta_22_),
    .RN(_062_),
    .SE(test_se),
    .SI(tx_conta_21_)
  );
  SDFFR_X1 _705_ (
    .CK(CK),
    .D(_147_),
    .Q(tx_conta_23_),
    .RN(_063_),
    .SE(test_se),
    .SI(tx_conta_22_)
  );
  SDFFR_X1 _706_ (
    .CK(CK),
    .D(_148_),
    .Q(tx_conta_24_),
    .RN(_064_),
    .SE(test_se),
    .SI(tx_conta_23_)
  );
  SDFFR_X1 _707_ (
    .CK(CK),
    .D(_149_),
    .Q(tx_conta_25_),
    .RN(_065_),
    .SE(test_se),
    .SI(tx_conta_24_)
  );
  SDFFR_X1 _708_ (
    .CK(CK),
    .D(_150_),
    .Q(tx_conta_26_),
    .RN(_066_),
    .SE(test_se),
    .SI(tx_conta_25_)
  );
  SDFFR_X1 _709_ (
    .CK(CK),
    .D(_151_),
    .Q(tx_conta_27_),
    .RN(_067_),
    .SE(test_se),
    .SI(tx_conta_26_)
  );
  SDFFR_X1 _710_ (
    .CK(CK),
    .D(_152_),
    .Q(tx_conta_28_),
    .RN(_068_),
    .SE(test_se),
    .SI(tx_conta_27_)
  );
  SDFFR_X1 _711_ (
    .CK(CK),
    .D(_153_),
    .Q(tx_conta_29_),
    .RN(_069_),
    .SE(test_se),
    .SI(tx_conta_28_)
  );
  SDFFR_X1 _712_ (
    .CK(CK),
    .D(_154_),
    .Q(tx_conta_30_),
    .RN(_070_),
    .SE(test_se),
    .SI(tx_conta_29_)
  );
  SDFFR_X1 _713_ (
    .CK(CK),
    .D(_155_),
    .Q(tx_conta_31_),
    .RN(_071_),
    .SE(test_se),
    .SI(tx_conta_30_)
  );
  SDFFR_X1 _714_ (
    .CK(CK),
    .D(_007_),
    .Q(send_en),
    .QN(_032_),
    .RN(_072_),
    .SE(test_se),
    .SI(tx_conta_31_)
  );
  SDFFR_X1 _715_ (
    .CK(CK),
    .D(_008_),
    .Q(tre),
    .RN(_073_),
    .SE(test_se),
    .SI(send_en)
  );
  SDFFR_X1 _716_ (
    .CK(CK),
    .D(_156_),
    .Q(errorr),
    .RN(_074_),
    .SE(test_se),
    .SI(tre)
  );
  SDFFR_X1 _717_ (
    .CK(CK),
    .D(_157_),
    .Q(out_reg_0_),
    .RN(_075_),
    .SE(test_se),
    .SI(errorr)
  );
  SDFFR_X1 _718_ (
    .CK(CK),
    .D(_158_),
    .Q(out_reg_1_),
    .RN(_076_),
    .SE(test_se),
    .SI(out_reg_0_)
  );
  SDFFR_X1 _719_ (
    .CK(CK),
    .D(_159_),
    .Q(out_reg_2_),
    .RN(_077_),
    .SE(test_se),
    .SI(out_reg_1_)
  );
  SDFFR_X1 _720_ (
    .CK(CK),
    .D(_160_),
    .Q(out_reg_3_),
    .RN(_078_),
    .SE(test_se),
    .SI(out_reg_2_)
  );
  SDFFR_X1 _721_ (
    .CK(CK),
    .D(_161_),
    .Q(out_reg_4_),
    .RN(_079_),
    .SE(test_se),
    .SI(out_reg_3_)
  );
  SDFFR_X1 _722_ (
    .CK(CK),
    .D(_162_),
    .Q(out_reg_5_),
    .RN(_080_),
    .SE(test_se),
    .SI(out_reg_4_)
  );
  SDFFR_X1 _723_ (
    .CK(CK),
    .D(_163_),
    .Q(out_reg_6_),
    .RN(_081_),
    .SE(test_se),
    .SI(out_reg_5_)
  );
  SDFFR_X1 _724_ (
    .CK(CK),
    .D(_164_),
    .Q(out_reg_7_),
    .RN(_082_),
    .SE(test_se),
    .SI(out_reg_6_)
  );
  SDFFR_X1 _725_ (
    .CK(CK),
    .D(_165_),
    .Q(confirm),
    .QN(_033_),
    .RN(_083_),
    .SE(test_se),
    .SI(out_reg_7_)
  );
  SDFFR_X1 _726_ (
    .CK(CK),
    .D(_166_),
    .Q(send),
    .RN(_084_),
    .SE(test_se),
    .SI(confirm)
  );
  SDFFR_X1 _727_ (
    .CK(CK),
    .D(_167_),
    .Q(load),
    .RN(_085_),
    .SE(test_se),
    .SI(send)
  );
  SDFFR_X1 _728_ (
    .CK(CK),
    .D(_168_),
    .Q(add_mpx2),
    .RN(_086_),
    .SE(test_se),
    .SI(load)
  );
  SDFFR_X1 _729_ (
    .CK(CK),
    .D(_169_),
    .Q(mpx),
    .QN(_029_),
    .RN(_087_),
    .SE(test_se),
    .SI(add_mpx2)
  );
  SDFFR_X1 _730_ (
    .CK(CK),
    .D(_170_),
    .Q(rdy),
    .RN(_088_),
    .SE(test_se),
    .SI(mpx)
  );
  SDFFR_X1 _731_ (
    .CK(CK),
    .D(_171_),
    .Q(shot),
    .RN(_089_),
    .SE(test_se),
    .SI(rdy)
  );
  SDFFR_X1 _732_ (
    .CK(CK),
    .D(_172_),
    .Q(soc),
    .RN(_090_),
    .SE(test_se),
    .SI(shot)
  );
  SDFFR_X1 _733_ (
    .CK(CK),
    .D(_173_),
    .Q(load_dato),
    .RN(_091_),
    .SE(test_se),
    .SI(soc)
  );
  SDFFR_X1 _734_ (
    .CK(CK),
    .D(_174_),
    .Q(mux_en),
    .RN(_092_),
    .SE(test_se),
    .SI(load_dato)
  );
  SDFFR_X1 _735_ (
    .CK(CK),
    .D(_175_),
    .Q(canale_0_),
    .RN(_093_),
    .SE(test_se),
    .SI(mux_en)
  );
  SDFFR_X1 _736_ (
    .CK(CK),
    .D(_176_),
    .Q(canale_1_),
    .RN(_094_),
    .SE(test_se),
    .SI(canale_0_)
  );
  SDFFR_X1 _737_ (
    .CK(CK),
    .D(_177_),
    .Q(canale_2_),
    .RN(_095_),
    .SE(test_se),
    .SI(canale_1_)
  );
  SDFFR_X1 _738_ (
    .CK(CK),
    .D(_178_),
    .Q(send_data),
    .RN(_096_),
    .SE(test_se),
    .SI(canale_2_)
  );
  SDFFR_X1 _739_ (
    .CK(CK),
    .D(_179_),
    .Q(conta_tmp_3_),
    .RN(_097_),
    .SE(test_se),
    .SI(send_data)
  );
  SDFFR_X1 _740_ (
    .CK(CK),
    .D(_180_),
    .Q(conta_tmp_4_),
    .RN(_098_),
    .SE(test_se),
    .SI(conta_tmp_3_)
  );
  SDFFR_X1 _741_ (
    .CK(CK),
    .D(_181_),
    .Q(conta_tmp_5_),
    .RN(_099_),
    .SE(test_se),
    .SI(conta_tmp_4_)
  );
  SDFFR_X1 _742_ (
    .CK(CK),
    .D(_182_),
    .Q(conta_tmp_6_),
    .RN(_100_),
    .SE(test_se),
    .SI(conta_tmp_5_)
  );
  SDFFR_X1 _743_ (
    .CK(CK),
    .D(_183_),
    .Q(conta_tmp_7_),
    .RN(_101_),
    .SE(test_se),
    .SI(conta_tmp_6_)
  );
  SDFFRS_X1 _744_ (
    .CK(CK),
    .D(_010_),
    .Q(S1_0_),
    .RN(_const1_),
    .SN(_102_),
    .SE(test_se),
    .SI(conta_tmp_7_)
  );
  SDFFR_X1 _745_ (
    .CK(CK),
    .D(S1_7_),
    .Q(S1_1_),
    .RN(_103_),
    .SE(test_se),
    .SI(S1_0_)
  );
  SDFFR_X1 _746_ (
    .CK(CK),
    .D(S1_4_),
    .Q(S1_2_),
    .RN(_104_),
    .SE(test_se),
    .SI(S1_1_)
  );
  SDFFR_X1 _747_ (
    .CK(CK),
    .D(_011_),
    .Q(S1_3_),
    .QN(_002_),
    .RN(_105_),
    .SE(test_se),
    .SI(S1_2_)
  );
  SDFFR_X1 _748_ (
    .CK(CK),
    .D(S1_0_),
    .Q(S1_4_),
    .RN(_106_),
    .SE(test_se),
    .SI(S1_3_)
  );
  SDFFR_X1 _749_ (
    .CK(CK),
    .D(_030_),
    .Q(S1_5_),
    .QN(_003_),
    .RN(_107_),
    .SE(test_se),
    .SI(S1_4_)
  );
  SDFFR_X1 _750_ (
    .CK(CK),
    .D(_031_),
    .Q(S1_6_),
    .QN(_006_),
    .RN(_108_),
    .SE(test_se),
    .SI(S1_5_)
  );
  SDFFR_X1 _751_ (
    .CK(CK),
    .D(S1_3_),
    .Q(S1_7_),
    .RN(_109_),
    .SE(test_se),
    .SI(S1_6_)
  );
  SDFFRS_X1 _752_ (
    .CK(CK),
    .D(_019_),
    .Q(next_bit_0_),
    .RN(_const1_),
    .SN(_110_),
    .SE(test_se),
    .SI(S1_7_)
  );
  SDFFR_X1 _753_ (
    .CK(CK),
    .D(_020_),
    .Q(next_bit_1_),
    .RN(_111_),
    .SE(test_se),
    .SI(next_bit_0_)
  );
  SDFFR_X1 _754_ (
    .CK(CK),
    .D(_021_),
    .Q(next_bit_2_),
    .RN(_112_),
    .SE(test_se),
    .SI(next_bit_1_)
  );
  SDFFR_X1 _755_ (
    .CK(CK),
    .D(_022_),
    .Q(next_bit_3_),
    .RN(_113_),
    .SE(test_se),
    .SI(next_bit_2_)
  );
  SDFFR_X1 _756_ (
    .CK(CK),
    .D(_023_),
    .Q(next_bit_4_),
    .RN(_114_),
    .SE(test_se),
    .SI(next_bit_3_)
  );
  SDFFR_X1 _757_ (
    .CK(CK),
    .D(_024_),
    .Q(next_bit_5_),
    .RN(_115_),
    .SE(test_se),
    .SI(next_bit_4_)
  );
  SDFFR_X1 _758_ (
    .CK(CK),
    .D(_025_),
    .Q(next_bit_6_),
    .RN(_116_),
    .SE(test_se),
    .SI(next_bit_5_)
  );
  SDFFR_X1 _759_ (
    .CK(CK),
    .D(_026_),
    .Q(next_bit_7_),
    .RN(_117_),
    .SE(test_se),
    .SI(next_bit_6_)
  );
  SDFFR_X1 _760_ (
    .CK(CK),
    .D(_027_),
    .Q(next_bit_8_),
    .RN(_118_),
    .SE(test_se),
    .SI(next_bit_7_)
  );
  SDFFR_X1 _761_ (
    .CK(CK),
    .D(_028_),
    .Q(next_bit_9_),
    .RN(_119_),
    .SE(test_se),
    .SI(next_bit_8_)
  );
  SDFFRS_X1 _762_ (
    .CK(CK),
    .D(_014_),
    .Q(S2_0_),
    .RN(_const1_),
    .SN(_120_),
    .SE(test_se),
    .SI(next_bit_9_)
  );
  SDFFR_X1 _763_ (
    .CK(CK),
    .D(_015_),
    .Q(S2_1_),
    .QN(_004_),
    .RN(_121_),
    .SE(test_se),
    .SI(S2_0_)
  );
  SDFFR_X1 _764_ (
    .CK(CK),
    .D(_016_),
    .Q(S2_2_),
    .RN(_122_),
    .SE(test_se),
    .SI(S2_1_)
  );
  SDFFR_X1 _765_ (
    .CK(CK),
    .D(_012_),
    .Q(S2_3_),
    .RN(_123_),
    .SE(test_se),
    .SI(S2_2_)
  );
  assign canale_3_ = conta_tmp_3_;

  wire _const1_;
  LOGIC1_X1 _tie__const1_ (.Z(_const1_));
  assign test_so = S2_3_;
endmodule