read_lib techlib/mod_nangate45.mdt
read_netlist mod_netlist/s5378.v
set_nonscan_ff DFF_0
DFF_1
DFF_10
DFF_100
DFF_101
DFF_102
DFF_103
DFF_104
DFF_105
DFF_106
DFF_107
DFF_108
DFF_109
DFF_11
DFF_110
DFF_111
DFF_112
DFF_113
build_circuit --frame 4
set_fault_type saf
add_fault -f /mnt/c/Users/Rueilian/OneDrive/Desktop/NTU/積體電路測試/final/ScanForge/results/residual_faults/exp_s5378_x10_no_tp_T2_after_T1_T2.faults
set_per_target_timeout 5
set_two_phase_justification on
set_static_compression off
set_dynamic_compression off
run_atpg
report_statistics > /mnt/c/Users/Rueilian/OneDrive/Desktop/NTU/積體電路測試/final/ScanForge/FAN_ATPG/rpt/exp_s5378_x10_no_tp_T2_t4.rpt
report_fault > /mnt/c/Users/Rueilian/OneDrive/Desktop/NTU/積體電路測試/final/ScanForge/FAN_ATPG/rpt/exp_s5378_x10_no_tp_T2_t4_faults.txt
exit
